import {
  PrebuiltSystem,
  GameRequirement,
  HardwareComponent,
  StreamerSetup,
  DealAlert,
  MonitorRecommendation,
  GamingGear
} from "./types";

export const MONITORS_DATABASE: MonitorRecommendation[] = [
  {
    id: "asus-tuf-vg249ql3a",
    name: "ASUS TUF Gaming VG249QL3A 24\"",
    brand: "ASUS",
    sizeInch: "23.8 inç",
    resolution: "1920x1080 (FHD)",
    refreshRate: "180Hz 1ms",
    panelType: "Fast IPS",
    price: 4999,
    dealTag: "F/P Kralı",
    imageUrl: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=600&q=80",
    buyUrl: "https://www.hepsiburada.com/ara?q=ASUS+TUF+VG249QL3A&utm_source=kasaradar",
    idealForGpu: "RTX 4060 / RX 6600"
  },
  {
    id: "viewsonic-vx2780-2k",
    name: "ViewSonic VX2780-2K-PRO 27\"",
    brand: "ViewSonic",
    sizeInch: "27 inç",
    resolution: "2560x1440 (2K QHD)",
    refreshRate: "170Hz 1ms",
    panelType: "Fast IPS",
    price: 7899,
    dealTag: "En Çok Satan 2K",
    imageUrl: "https://images.unsplash.com/photo-1547119957-637f8679db1e?auto=format&fit=crop&w=600&q=80",
    buyUrl: "https://www.amazon.com.tr/s?k=ViewSonic+VX2780-2K-PRO&tag=kasaradar-21",
    idealForGpu: "RTX 4060 Ti / RTX 4070 SUPER"
  },
  {
    id: "benq-zowie-xl2566k",
    name: "BenQ ZOWIE XL2566K 24.5\" DyAc+",
    brand: "BenQ ZOWIE",
    sizeInch: "24.5 inç",
    resolution: "1920x1080 (FHD)",
    refreshRate: "360Hz 0.5ms DyAc+",
    panelType: "Fast IPS",
    price: 24999,
    dealTag: "Espor Standardı",
    imageUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=600&q=80",
    buyUrl: "https://www.itopya.com/AramaSonuclari/?q=ZOWIE+XL2566K&ref=kasaradar",
    idealForGpu: "RTX 4060 Ti / RTX 4070 / Espor"
  },
  {
    id: "dell-alienware-aw2725df",
    name: "Dell Alienware AW2725DF 27\" QD-OLED",
    brand: "Dell Alienware",
    sizeInch: "27 inç",
    resolution: "2560x1440 (2K)",
    refreshRate: "360Hz 0.03ms",
    panelType: "OLED",
    price: 31999,
    dealTag: "OLED Zirvesi",
    imageUrl: "https://images.unsplash.com/photo-1585792180666-f7347c490ee2?auto=format&fit=crop&w=600&q=80",
    buyUrl: "https://www.itopya.com/AramaSonuclari/?q=Alienware+AW2725DF&ref=kasaradar",
    idealForGpu: "RTX 4070 Super / RTX 4080 Super"
  }
];

export const GAMING_GEAR_DATABASE: GamingGear[] = [
  // Mice
  {
    id: "logitech-g-pro-x-superlight-2",
    name: "Logitech G PRO X Superlight 2 Lightspeed",
    category: "mouse",
    categoryLabel: "Oyuncu Mouse",
    brand: "Logitech G",
    price: 5299,
    tag: "Dünyanın 1 Numaralı E-Spor Mouse'u",
    specs: "60 gram tüy siklet, HERO 2 sensör (32.000 DPI), LIGHTFORCE optik-mekanik hibrit anahtarlar, 95 saat pil",
    imageUrl: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=600&q=80",
    buyUrl: "https://www.amazon.com.tr/s?k=Logitech+G+PRO+X+Superlight+2&tag=kasaradar-21",
    proPlayersUsing: ["s1mple", "NiKo", "Elraenn"]
  },
  {
    id: "razer-viper-v3-pro",
    name: "Razer Viper V3 Pro Wireless",
    category: "mouse",
    categoryLabel: "Oyuncu Mouse",
    brand: "Razer",
    price: 5799,
    tag: "8000Hz Gerçek Polling Rate",
    specs: "54 gram ultra hafif, Focus Pro 35K Gen-2 sensör, Gerçek 8000Hz kablosuz HyperPolling dongle dahil",
    imageUrl: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=600&q=80",
    buyUrl: "https://www.hepsiburada.com/ara?q=Razer+Viper+V3+Pro&utm_source=kasaradar",
    proPlayersUsing: ["wtcN", "shroud", "Mithrain"]
  },
  {
    id: "razer-deathadder-v3-pro",
    name: "Razer DeathAdder V3 Pro Wireless (Ergonomik)",
    category: "mouse",
    categoryLabel: "Oyuncu Mouse",
    brand: "Razer",
    price: 5499,
    tag: "Ergonomik Efsane (63g)",
    specs: "63 gram hafif tasarım, Focus Pro 30K optik sensör, Gen-3 optik anahtarlar, 90 saat pil",
    imageUrl: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=600&q=80",
    buyUrl: "https://www.itopya.com/AramaSonuclari/?q=DeathAdder+V3+Pro&ref=kasaradar",
    proPlayersUsing: ["s1mple", "NiKo"]
  },
  {
    id: "finalmouse-ultralightx",
    name: "Finalmouse UltralightX TenZ Edition",
    category: "mouse",
    categoryLabel: "Oyuncu Mouse",
    brand: "Finalmouse",
    price: 9800,
    tag: "31 Gram Karbon Fiber Kompozit",
    specs: "Dünyanın en hafif espor faresi (31g), TenZ özel tasarımı, PixArt son nesil sensör",
    imageUrl: "https://images.unsplash.com/photo-1626218174358-7769486c4b79?auto=format&fit=crop&w=600&q=80",
    buyUrl: "https://www.amazon.com.tr/s?k=Finalmouse+UltralightX&tag=kasaradar-21",
    proPlayersUsing: ["TenZ"]
  },

  // Keyboards
  {
    id: "wooting-60he-plus",
    name: "Wooting 60HE+ (Hall Effect Analog Klavye)",
    category: "keyboard",
    categoryLabel: "Oyuncu Klavyesi",
    brand: "Wooting",
    price: 7999,
    tag: "Rapid Trigger Kralı (Hile Gibi Tepki)",
    specs: "0.1mm ayarlanabilir basış noktası, Lekker manyetik anahtarlar, CS2 ve Valorant için anında durma (Snap Tap)",
    imageUrl: "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=600&q=80",
    buyUrl: "https://www.amazon.com.tr/s?k=Wooting+60HE&tag=kasaradar-21",
    proPlayersUsing: ["TenZ", "wtcN", "NiKo"]
  },
  {
    id: "steelseries-apex-pro-tkl",
    name: "SteelSeries Apex Pro TKL Gen 3",
    category: "keyboard",
    categoryLabel: "Oyuncu Klavyesi",
    brand: "SteelSeries",
    price: 6899,
    tag: "OmniPoint 3.0 Manyetik Switch",
    specs: "OLED akıllı ekran, 0.1mm - 4.0mm ayarlanabilir aktivasyon mesafesi, havacılık sınıfı alüminyum gövde",
    imageUrl: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=600&q=80",
    buyUrl: "https://www.itopya.com/AramaSonuclari/?q=Apex+Pro+TKL&ref=kasaradar",
    proPlayersUsing: ["Elraenn", "s1mple"]
  },
  {
    id: "akko-5075s-via",
    name: "Akko 5075S VIA Özel Mekanik Klavye",
    category: "keyboard",
    categoryLabel: "Oyuncu Klavyesi",
    brand: "Akko",
    price: 3499,
    tag: "Gasket Mount & Hotswap F/P",
    specs: "Gasket montaj tasarımı, ses yalıtım pedleri, çalışırken değiştirilebilir (hotswap) switchler, RGB ses tekerleği",
    imageUrl: "https://images.unsplash.com/photo-1595044426077-d36d9236d54a?auto=format&fit=crop&w=600&q=80",
    buyUrl: "https://www.amazon.com.tr/s?k=Akko+5075S&tag=kasaradar-21",
    proPlayersUsing: ["Kendine Müzisyen"]
  },

  // Headsets
  {
    id: "hyperx-cloud-3-wireless",
    name: "HyperX Cloud III Wireless 120 Saat Pil",
    category: "headset",
    categoryLabel: "Oyuncu Kulaklığı",
    brand: "HyperX",
    price: 4899,
    tag: "120 Saat Kesintisiz Pil Ömrü",
    specs: "53mm açılı sürücüler, DTS Headphone:X uzamsal ses, gürültü engelleyici LED göstergeli kristal mikrofon",
    imageUrl: "https://images.unsplash.com/photo-1599669454699-248893623440?auto=format&fit=crop&w=600&q=80",
    buyUrl: "https://www.hepsiburada.com/ara?q=HyperX+Cloud+III+Wireless&utm_source=kasaradar",
    proPlayersUsing: ["wtcN", "Mithrain", "Unlost"]
  },
  {
    id: "razer-blackshark-v2-pro",
    name: "Razer BlackShark V2 Pro 2023 Edition",
    category: "headset",
    categoryLabel: "Oyuncu Kulaklığı",
    brand: "Razer",
    price: 6499,
    tag: "HyperClear Süper Geniş Bant Mikrofon",
    specs: "TriForce Titanyum 50mm sürücüler, 70 saat pil, ultra net mikrofon kalitesi, espor ses profilleri",
    imageUrl: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&w=600&q=80",
    buyUrl: "https://www.itopya.com/AramaSonuclari/?q=BlackShark+V2+Pro&ref=kasaradar",
    proPlayersUsing: ["shroud", "NiKo"]
  },
  {
    id: "sennheiser-hd-660s2",
    name: "Sennheiser HD 660S2 Açık Akustik Odiofil",
    category: "headset",
    categoryLabel: "Oyuncu Kulaklığı",
    brand: "Sennheiser",
    price: 18999,
    tag: "Yayıncıların Kusursuz Ses Tercihi",
    specs: "300 Ohm empedans, açık arkalı akustik tasarım, oyundaki her ayak sesini milimetrik konumlandırma",
    imageUrl: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=600&q=80",
    buyUrl: "https://www.amazon.com.tr/s?k=Sennheiser+HD+660S&tag=kasaradar-21",
    proPlayersUsing: ["Elraenn", "Jahrein"]
  },

  // Mousepads
  {
    id: "artisan-ninja-fx-zero-soft",
    name: "Artisan Ninja FX Zero Soft (Japon Efsanesi)",
    category: "mousepad",
    categoryLabel: "Espor Mousepad",
    brand: "Artisan Japan",
    price: 2999,
    tag: "Esporcuların 1 Numaralı Kumaş Yüzeyi",
    specs: "Japonya el üretimi, mikrofiber doku, neme karşı sıfır sürtünme kaybı, kaymaz özel doğal sünger taban",
    imageUrl: "https://images.unsplash.com/photo-1616440347437-b1c73416efc2?auto=format&fit=crop&w=600&q=80",
    buyUrl: "https://www.amazon.com.tr/s?k=Artisan+Zero+FX+Soft&tag=kasaradar-21",
    proPlayersUsing: ["TenZ", "NiKo", "s1mple"]
  },
  {
    id: "benq-zowie-gsr-2",
    name: "BenQ ZOWIE G-SR-II Espor Mousepad",
    category: "mousepad",
    categoryLabel: "Espor Mousepad",
    brand: "BenQ ZOWIE",
    price: 1899,
    tag: "CS2 & Valorant Kontrol Standardı",
    specs: "Neme karşı güçlendirilmiş yoğun kumaş dokusu, mikro-durdurma gücü, 3.5mm dikişli yumuşak kauçuk taban",
    imageUrl: "https://images.unsplash.com/photo-1616440347437-b1c73416efc2?auto=format&fit=crop&w=600&q=80",
    buyUrl: "https://www.itopya.com/AramaSonuclari/?q=Zowie+G-SR-II&ref=kasaradar",
    proPlayersUsing: ["s1mple", "NiKo"]
  },
  {
    id: "steelseries-qck-heavy",
    name: "SteelSeries QcK Heavy XXL (6mm Kalınlık)",
    category: "mousepad",
    categoryLabel: "Espor Mousepad",
    brand: "SteelSeries",
    price: 999,
    tag: "F/P Espor Klasiği",
    specs: "6mm ekstra kalın mikrodokuma kumaş yüzey, bilek konforu ve hassas optik takip optimizasyonu",
    imageUrl: "https://images.unsplash.com/photo-1616440347437-b1c73416efc2?auto=format&fit=crop&w=600&q=80",
    buyUrl: "https://www.hepsiburada.com/ara?q=SteelSeries+QcK+Heavy&utm_source=kasaradar",
    proPlayersUsing: ["Unlost", "Kendine Müzisyen"]
  }
];

export const PREBUILT_SYSTEMS: PrebuiltSystem[] = [
  // 1. İTOPYA MODART
  {
    id: "itopya-modart-pc",
    title: "ModArt-X1 V2 Gaming Sistem",
    seller: "İtopya",
    sellerLogo: "🟢",
    sellerColor: "#10b981",
    price: 22999,
    oldPrice: 25499,
    installmentsText: "Peşin Fiyatına 3 Taksit: 7.666 TL x 3 (Axess, World, Maximum)",
    cpuBrand: "AMD",
    gpuBrand: "Nvidia",
    listedDate: "Bugün 01:30 eklendi",
    cpu: "AMD Ryzen 5 5600 (4.4GHz 6C/12T 32MB L3)",
    cpuTier: 65,
    gpu: "Nvidia GeForce RTX 4060 Dual OC 8GB",
    gpuTier: 72,
    gpuVram: "8GB GDDR6",
    ram: "16GB (2x8GB) G.Skill Ripjaws 3200MHz",
    ramType: "DDR4",
    ramSizeGb: 16,
    ssd: "1TB Kioxia Exceria Plus G3 Gen4 NVMe (5000MB/s)",
    ssdSizeGb: 1000,
    motherboard: "ASUS Prime B450M-K II",
    psu: "FSP Hyper Pro 650W 80+ Bronze",
    caseModel: "Vento VG15FE 4x ARGB Fanlı Mesh Kasa",
    cooling: "AMD Wraith Stealth Stok Soğutucu",
    imageUrl: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=800&q=80",
    directUrl: "https://www.itopya.com/AramaSonuclari/?q=modart&ref=kasaradar",
    fpScore: 9.4,
    individualZeroPrice: 27850,
    individualSecondHandPrice: 19400,
    badge: "F/P Kralı",
    highlight: "1080p Ultra ayarlarda tüm rekabetçi ve AAA oyunları 100+ FPS çalıştırır. Tek tek toplamaya göre 4.851 TL kâr!",
    targetResolution: "1080p Ultra",
    warranty: "2 Yıl Resmi İtopya Garantili",
    tdpWatts: 280,
    partsBreakdown: [
      { name: "Nvidia GeForce RTX 4060 8GB", category: "Ekran Kartı", individualNewPrice: 12900, buyUrl: "https://www.amazon.com.tr/s?k=RTX+4060&tag=kasaradar-21", store: "Amazon TR" },
      { name: "AMD Ryzen 5 5600 4.4GHz", category: "İşlemci", individualNewPrice: 4100, buyUrl: "https://www.hepsiburada.com/ara?q=Ryzen+5+5600&utm_source=kasaradar", store: "Hepsiburada" },
      { name: "ASUS Prime B450M-K II", category: "Anakart", individualNewPrice: 2450, buyUrl: "https://www.itopya.com/AramaSonuclari/?q=ASUS+B450M-K+II&ref=kasaradar", store: "İtopya" },
      { name: "G.Skill Ripjaws 16GB (2x8) 3200MHz", category: "RAM", individualNewPrice: 1650, buyUrl: "https://www.amazon.com.tr/s?k=G.Skill+Ripjaws+16GB&tag=kasaradar-21", store: "Amazon TR" },
      { name: "Kioxia Exceria Plus G3 1TB NVMe", category: "SSD", individualNewPrice: 2750, buyUrl: "https://www.hepsiburada.com/ara?q=Kioxia+Exceria+G3+1TB&utm_source=kasaradar", store: "Hepsiburada" },
      { name: "Vento VG15FE + FSP 650W Kasa & PSU", category: "Kasa", individualNewPrice: 4000, buyUrl: "https://www.itopya.com/AramaSonuclari/?q=Vento+VG15FE&ref=kasaradar", store: "İtopya" }
    ],
    recommendedMonitors: [MONITORS_DATABASE[0]]
  },

  // 2. GAMİNG.GEN.TR BLADE 7500F
  {
    id: "gaminggen-blade-7500f",
    title: "BLADE-7500F / RTX 4060 Ti DDR5",
    seller: "Gaming.Gen.TR",
    sellerLogo: "🔴",
    sellerColor: "#ef4444",
    price: 31499,
    oldPrice: 34999,
    installmentsText: "Peşin Fiyatına 3 Taksit: 10.499 TL x 3 (Bonus, Maximum, World)",
    cpuBrand: "AMD",
    gpuBrand: "Nvidia",
    listedDate: "Bugün 00:45 eklendi",
    cpu: "AMD Ryzen 5 7500F (5.0GHz AM5 DDR5)",
    cpuTier: 82,
    gpu: "ASUS Dual GeForce RTX 4060 Ti EVO OC 8GB",
    gpuTier: 79,
    gpuVram: "8GB GDDR6",
    ram: "16GB Kingston Fury Beast 5600MHz CL36",
    ramType: "DDR5",
    ramSizeGb: 16,
    ssd: "1TB Kingston NV2 NVMe M.2 (3500MB/s)",
    ssdSizeGb: 1000,
    motherboard: "ASUS Prime A620M-K AM5 DDR5",
    psu: "Enermax MarbleBron 650W 80+ Bronze",
    caseModel: "Vento VG07F Tempered Glass ARGB",
    cooling: "Thermalright Assassin King 120 SE Kule Tipi",
    imageUrl: "https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=800&q=80",
    directUrl: "https://www.gaming.gen.tr/?s=blade-7500f&ref=kasaradar",
    fpScore: 9.6,
    individualZeroPrice: 37900,
    individualSecondHandPrice: 27200,
    badge: "En Çok Satan",
    highlight: "Yeni nesil AM5 DDR5 platformu! Gelecekte işlemci yükseltmeye açık, 2K çözünürlük için ideal.",
    targetResolution: "1440p 2K",
    warranty: "2 Yıl Birebir Değişim Garantisi",
    tdpWatts: 340,
    partsBreakdown: [
      { name: "ASUS Dual RTX 4060 Ti 8GB OC", category: "Ekran Kartı", individualNewPrice: 16900, buyUrl: "https://www.amazon.com.tr/s?k=ASUS+Dual+RTX+4060+Ti&tag=kasaradar-21", store: "Amazon TR" },
      { name: "AMD Ryzen 5 7500F Tray AM5", category: "İşlemci", individualNewPrice: 5800, buyUrl: "https://www.hepsiburada.com/ara?q=Ryzen+5+7500F&utm_source=kasaradar", store: "Hepsiburada" },
      { name: "ASUS Prime A620M-K DDR5", category: "Anakart", individualNewPrice: 3600, buyUrl: "https://www.itopya.com/AramaSonuclari/?q=ASUS+Prime+A620M-K&ref=kasaradar", store: "İtopya" },
      { name: "Kingston Fury Beast 16GB 5600MHz DDR5", category: "RAM", individualNewPrice: 2200, buyUrl: "https://www.amazon.com.tr/s?k=Kingston+Fury+16GB+DDR5&tag=kasaradar-21", store: "Amazon TR" },
      { name: "Kingston NV2 1TB Gen4 NVMe", category: "SSD", individualNewPrice: 2600, buyUrl: "https://www.hepsiburada.com/ara?q=Kingston+NV2+1TB&utm_source=kasaradar", store: "Hepsiburada" },
      { name: "Thermalright Assassin King 120", category: "Soğutucu", individualNewPrice: 1100, buyUrl: "https://www.gaming.gen.tr?ref=kasaradar", store: "Gaming.Gen.TR" },
      { name: "Vento VG07F + 650W Bronze Kasa & PSU", category: "Kasa", individualNewPrice: 4200, buyUrl: "https://www.gaming.gen.tr?ref=kasaradar", store: "Gaming.Gen.TR" }
    ],
    recommendedMonitors: [MONITORS_DATABASE[0], MONITORS_DATABASE[1]]
  },

  // 3. GAMEGARAJ HERO 4070 SUPER
  {
    id: "gamegaraj-hero-4070super",
    title: "HERO 7A-RTX4070 Super Beast",
    seller: "GameGaraj",
    sellerLogo: "🟡",
    sellerColor: "#f59e0b",
    price: 45999,
    oldPrice: 49999,
    installmentsText: "Peşin Fiyatına 6 Taksit: 7.666 TL x 6 (Tüm Bankalar)",
    cpuBrand: "AMD",
    gpuBrand: "Nvidia",
    listedDate: "Dün eklendi",
    cpu: "AMD Ryzen 5 7600X (5.3GHz 6C/12T AM5)",
    cpuTier: 85,
    gpu: "Palit GeForce RTX 4070 SUPER Dual 12GB",
    gpuTier: 89,
    gpuVram: "12GB GDDR6X",
    ram: "32GB (2x16GB) G.Skill Flare X5 6000MHz CL30",
    ramType: "DDR5",
    ramSizeGb: 32,
    ssd: "1TB Kingston KC3000 Gen4x4 (7000MB/s)",
    ssdSizeGb: 1000,
    motherboard: "MSI Pro B650M-P DDR5",
    psu: "GameGaraj 750W 80+ Gold Modüler",
    caseModel: "DarkFlash DLX21 Mesh White",
    cooling: "Thermalright Peerless Assassin 120 Çift Kule",
    imageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
    directUrl: "https://www.gamegaraj.com/?s=hero+7a&ref=kasaradar",
    fpScore: 9.3,
    individualZeroPrice: 53800,
    individualSecondHandPrice: 39500,
    badge: "Haftanın Fırsatı",
    highlight: "12GB VRAM + DLSS 3 Frame Gen ile Cyberpunk ve GTA 6'yı 2K ve 4K'da uçurur. 32GB RAM ile yayın ve render için canavar.",
    targetResolution: "1440p 2K",
    warranty: "2 Yıl GameGaraj Garantisi",
    tdpWatts: 420,
    partsBreakdown: [
      { name: "Palit GeForce RTX 4070 SUPER 12GB", category: "Ekran Kartı", individualNewPrice: 26500, buyUrl: "https://www.gamegaraj.com?ref=kasaradar", store: "GameGaraj" },
      { name: "AMD Ryzen 5 7600X 5.3GHz AM5", category: "İşlemci", individualNewPrice: 7800, buyUrl: "https://www.amazon.com.tr/s?k=Ryzen+5+7600X&tag=kasaradar-21", store: "Amazon TR" },
      { name: "MSI Pro B650M-P AM5 DDR5", category: "Anakart", individualNewPrice: 4800, buyUrl: "https://www.hepsiburada.com/ara?q=MSI+Pro+B650M-P&utm_source=kasaradar", store: "Hepsiburada" },
      { name: "G.Skill Flare X5 32GB (2x16) 6000MHz", category: "RAM", individualNewPrice: 4400, buyUrl: "https://www.amazon.com.tr/s?k=G.Skill+Flare+X5+32GB&tag=kasaradar-21", store: "Amazon TR" },
      { name: "Kingston KC3000 1TB PCIe 4.0 NVMe", category: "SSD", individualNewPrice: 3800, buyUrl: "https://www.hepsiburada.com/ara?q=Kingston+KC3000+1TB&utm_source=kasaradar", store: "Hepsiburada" },
      { name: "Thermalright Peerless Assassin 120", category: "Soğutucu", individualNewPrice: 1800, buyUrl: "https://www.gaming.gen.tr?ref=kasaradar", store: "Gaming.Gen.TR" },
      { name: "DarkFlash DLX21 + 750W Gold Modüler Kasa", category: "Kasa", individualNewPrice: 4700, buyUrl: "https://www.gamegaraj.com?ref=kasaradar", store: "GameGaraj" }
    ],
    recommendedMonitors: [MONITORS_DATABASE[1], MONITORS_DATABASE[2]]
  },

  // 4. VATAN BİLGİSAYAR OEM RTX 3050 (Doğru Kasa Fotoğrafı & Direkt Link)
  {
    id: "vatan-oem-rtx3050",
    title: "Vatan OEM Entry / RTX 3050 8GB",
    seller: "Vatan Bilgisayar",
    sellerLogo: "🔷",
    sellerColor: "#0284c7",
    price: 16999,
    oldPrice: 19500,
    installmentsText: "Peşin Fiyatına 3 Taksit: 5.666 TL x 3 (Maximum, World, Axess)",
    cpuBrand: "Intel",
    gpuBrand: "Nvidia",
    listedDate: "Bugün 02:00 eklendi",
    cpu: "Intel Core i3 12100F (4.3GHz 4C/8T)",
    cpuTier: 50,
    gpu: "ZOTAC GeForce RTX 3050 Twin Edge 8GB",
    gpuTier: 55,
    gpuVram: "8GB GDDR6",
    ram: "16GB (2x8GB) Crucial 3200MHz DDR4",
    ramType: "DDR4",
    ramSizeGb: 16,
    ssd: "500GB Crucial P3 M.2 NVMe SSD",
    ssdSizeGb: 500,
    motherboard: "MSI PRO H610M-E DDR4",
    psu: "Rampage 500W 80+ Kasa & PSU",
    caseModel: "Rampage Sailor Temperli Cam Mid-Tower",
    cooling: "Intel Orijinal Stok Fan",
    imageUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80",
    directUrl: "https://www.vatanbilgisayar.com/arama/rtx%203050%20hazir%20sistem/",
    fpScore: 9.2,
    individualZeroPrice: 20900,
    individualSecondHandPrice: 13800,
    badge: "Fiyatı Düştü",
    highlight: "17.000 TL altına 8GB VRAM ve DLSS desteği! CS2, Valorant, GTA 5 ve LoL'de akıcı 144+ FPS.",
    targetResolution: "1080p Ultra",
    warranty: "2 Yıl Vatan Bilgisayar Garantili",
    tdpWatts: 220,
    partsBreakdown: [
      { name: "ZOTAC GeForce RTX 3050 8GB", category: "Ekran Kartı", individualNewPrice: 8600, buyUrl: "https://www.amazon.com.tr/s?k=RTX+3050+8GB&tag=kasaradar-21", store: "Amazon TR" },
      { name: "Intel Core i3 12100F", category: "İşlemci", individualNewPrice: 3200, buyUrl: "https://www.hepsiburada.com/ara?q=i3+12100F&utm_source=kasaradar", store: "Hepsiburada" },
      { name: "MSI PRO H610M-E DDR4", category: "Anakart", individualNewPrice: 2400, buyUrl: "https://www.vatanbilgisayar.com/arama/MSI+H610M/", store: "Vatan Bilgisayar" },
      { name: "Crucial 16GB (2x8) 3200MHz", category: "RAM", individualNewPrice: 1500, buyUrl: "https://www.amazon.com.tr/s?k=Crucial+16GB+3200&tag=kasaradar-21", store: "Amazon TR" },
      { name: "Crucial P3 500GB NVMe", category: "SSD", individualNewPrice: 1700, buyUrl: "https://www.hepsiburada.com/ara?q=Crucial+P3+500GB&utm_source=kasaradar", store: "Hepsiburada" },
      { name: "Rampage 500W Kasa & Güç Kaynağı", category: "Kasa", individualNewPrice: 3500, buyUrl: "https://www.vatanbilgisayar.com/arama/Rampage+Kasa/", store: "Vatan Bilgisayar" }
    ],
    recommendedMonitors: [MONITORS_DATABASE[0]]
  },

  // 5. TEBİLON ZENİTH 4060
  {
    id: "tebilon-zenith-4060",
    title: "Tebilon Zenith-X / i5 12400F",
    seller: "Tebilon",
    sellerLogo: "🔵",
    sellerColor: "#3b82f6",
    price: 20499,
    oldPrice: 22800,
    installmentsText: "Peşin Fiyatına 3 Taksit: 6.833 TL x 3",
    cpuBrand: "Intel",
    gpuBrand: "Nvidia",
    listedDate: "2 gün önce eklendi",
    cpu: "Intel Core i5 12400F (4.4GHz 6C/12T)",
    cpuTier: 64,
    gpu: "Gigabyte GeForce RTX 4060 Eagle OC",
    gpuTier: 72,
    gpuVram: "8GB GDDR6",
    ram: "16GB (2x8GB) Corsair Vengeance 3200MHz",
    ramType: "DDR4",
    ramSizeGb: 16,
    ssd: "500GB Kingston NV2 M.2 NVMe",
    ssdSizeGb: 500,
    motherboard: "Gigabyte H610M H V2 DDR4",
    psu: "DeepCool PK550D 550W 80+ Bronze",
    caseModel: "DeepCool CC560 V2 Mesh 4x Fan",
    cooling: "Intel Orijinal Stok Fan",
    imageUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80",
    directUrl: "https://www.tebilon.com/arama?q=zenith",
    fpScore: 9.5,
    individualZeroPrice: 25100,
    individualSecondHandPrice: 17800,
    badge: "Fiyatı Düştü",
    highlight: "20.000 TL bandında RTX 40 serisi arayanlar için en ucuz geçerli sistem! DLSS 3 desteğiyle güncel.",
    targetResolution: "1080p Ultra",
    warranty: "2 Yıl Tebilon Güvencesi",
    tdpWatts: 270,
    partsBreakdown: [
      { name: "Gigabyte RTX 4060 Eagle OC 8GB", category: "Ekran Kartı", individualNewPrice: 12800, buyUrl: "https://www.amazon.com.tr/s?k=RTX+4060+Gigabyte&tag=kasaradar-21", store: "Amazon TR" },
      { name: "Intel Core i5 12400F 4.4GHz", category: "İşlemci", individualNewPrice: 4200, buyUrl: "https://www.hepsiburada.com/ara?q=i5+12400F&utm_source=kasaradar", store: "Hepsiburada" },
      { name: "Gigabyte H610M H V2 DDR4", category: "Anakart", individualNewPrice: 2500, buyUrl: "https://www.itopya.com/AramaSonuclari/?q=Gigabyte+H610M&ref=kasaradar", store: "İtopya" },
      { name: "Corsair Vengeance 16GB (2x8) 3200MHz", category: "RAM", individualNewPrice: 1550, buyUrl: "https://www.amazon.com.tr/s?k=Corsair+Vengeance+16GB&tag=kasaradar-21", store: "Amazon TR" },
      { name: "Kingston NV2 500GB NVMe M.2", category: "SSD", individualNewPrice: 1650, buyUrl: "https://www.hepsiburada.com/ara?q=Kingston+NV2+500GB&utm_source=kasaradar", store: "Hepsiburada" },
      { name: "DeepCool CC560 + 550W Bronze Kasa & PSU", category: "Kasa", individualNewPrice: 3400, buyUrl: "https://www.tebilon.com/arama?q=DeepCool+CC560", store: "Tebilon" }
    ],
    recommendedMonitors: [MONITORS_DATABASE[0]]
  },

  // 6. İNCEHESAP FALCON RX 7700 XT
  {
    id: "incehesap-falcon-7700xt",
    title: "Falcon AMD Pure Power / RX 7700 XT",
    seller: "İncehesap",
    sellerLogo: "🟣",
    sellerColor: "#a855f7",
    price: 34999,
    oldPrice: 38500,
    installmentsText: "Peşin Fiyatına 3 Taksit: 11.666 TL x 3",
    cpuBrand: "AMD",
    gpuBrand: "AMD",
    listedDate: "3 gün önce eklendi",
    cpu: "AMD Ryzen 5 7500F AM5 Tray",
    cpuTier: 82,
    gpu: "Sapphire Pulse Radeon RX 7700 XT 12GB",
    gpuTier: 84,
    gpuVram: "12GB GDDR6",
    ram: "16GB Team T-Force Vulcan 5600MHz DDR5",
    ramType: "DDR5",
    ramSizeGb: 16,
    ssd: "1TB Lexar NM620 M.2 SSD",
    ssdSizeGb: 1000,
    motherboard: "ASRock B650M-HDV/M.2 AM5",
    psu: "Cougar XTC 650W 80+",
    caseModel: "Lian Li Lancool 205 Mesh ARGB",
    cooling: "ID-Cooling SE-214-XT ARGB",
    imageUrl: "https://images.unsplash.com/photo-1552831388-6a0b3575b35a?auto=format&fit=crop&w=800&q=80",
    directUrl: "https://www.incehesap.com/ara/?q=falcon",
    fpScore: 9.1,
    individualZeroPrice: 41200,
    individualSecondHandPrice: 30500,
    badge: "F/P Kralı",
    highlight: "12GB Saf Kas Gücü! Saf oyun performansında RTX 4060 Ti'ı ezip geçer, 2K çözünürlükte tam canavar.",
    targetResolution: "1440p 2K",
    warranty: "2 Yıl İncehesap Garantisi",
    tdpWatts: 380,
    partsBreakdown: [
      { name: "Sapphire Pulse RX 7700 XT 12GB", category: "Ekran Kartı", individualNewPrice: 19500, buyUrl: "https://www.hepsiburada.com/ara?q=RX+7700+XT&utm_source=kasaradar", store: "Hepsiburada" },
      { name: "AMD Ryzen 5 7500F AM5", category: "İşlemci", individualNewPrice: 5800, buyUrl: "https://www.amazon.com.tr/s?k=Ryzen+5+7500F&tag=kasaradar-21", store: "Amazon TR" },
      { name: "ASRock B650M-HDV/M.2 AM5", category: "Anakart", individualNewPrice: 4200, buyUrl: "https://www.incehesap.com/ara/?q=ASRock+B650M", store: "İncehesap" },
      { name: "Team T-Force 16GB 5600MHz DDR5", category: "RAM", individualNewPrice: 2200, buyUrl: "https://www.amazon.com.tr/s?k=Team+T-Force+DDR5&tag=kasaradar-21", store: "Amazon TR" },
      { name: "Lexar NM620 1TB M.2 NVMe", category: "SSD", individualNewPrice: 2400, buyUrl: "https://www.hepsiburada.com/ara?q=Lexar+NM620+1TB&utm_source=kasaradar", store: "Hepsiburada" },
      { name: "ID-Cooling SE-214-XT Kule Tipi", category: "Soğutucu", individualNewPrice: 1100, buyUrl: "https://www.incehesap.com/ara/?q=SE-214-XT", store: "İncehesap" },
      { name: "Lian Li Lancool 205 + 650W PSU", category: "Kasa", individualNewPrice: 6000, buyUrl: "https://www.incehesap.com/ara/?q=Lancool+205", store: "İncehesap" }
    ],
    recommendedMonitors: [MONITORS_DATABASE[1]]
  },

  // 7. TEKNOBİYOTİK DARK MAXIMA V30 (Doğru Masaüstü Kasa Görseli)
  {
    id: "teknobiyotik-dark-rx7800xt",
    title: "Dark Diamond Pro / RX 7800 XT 16GB",
    seller: "Teknobiyotik",
    sellerLogo: "⬛",
    sellerColor: "#64748b",
    price: 39999,
    oldPrice: 43500,
    installmentsText: "Peşin Fiyatına 4 Taksit: 9.999 TL x 4",
    cpuBrand: "AMD",
    gpuBrand: "AMD",
    listedDate: "Bugün 01:10 eklendi",
    cpu: "AMD Ryzen 5 7600 (5.1GHz 6C/12T AM5)",
    cpuTier: 84,
    gpu: "Sapphire Nitro+ Radeon RX 7800 XT 16GB",
    gpuTier: 88,
    gpuVram: "16GB GDDR6",
    ram: "32GB (2x16GB) Kingston Fury Beast 5600MHz",
    ramType: "DDR5",
    ramSizeGb: 32,
    ssd: "1TB Kioxia Exceria Plus G3 Gen4 NVMe",
    ssdSizeGb: 1000,
    motherboard: "ASRock B650M PG Lightning",
    psu: "High Power 750W 80+ Gold",
    caseModel: "Dark Maxima V30 Temperli Cam ARGB",
    cooling: "Dark AquaForce W242 240mm Sıvı Soğutma",
    imageUrl: "https://images.unsplash.com/photo-1587202372634-32705e3bf49c?auto=format&fit=crop&w=800&q=80",
    directUrl: "https://www.teknobiyotik.com/arama?q=dark+diamond",
    fpScore: 9.3,
    individualZeroPrice: 47200,
    individualSecondHandPrice: 34500,
    badge: "Haftanın Fırsatı",
    highlight: "16GB VRAM ile 2K ve 4K'da VRAM darboğazına son! 240mm sıvı soğutmalı ve 32GB RAM'li tam paket canavar.",
    targetResolution: "1440p 2K",
    warranty: "2 Yıl Teknobiyotik Garantisi",
    tdpWatts: 430,
    partsBreakdown: [
      { name: "Sapphire Nitro+ RX 7800 XT 16GB", category: "Ekran Kartı", individualNewPrice: 22500, buyUrl: "https://www.teknobiyotik.com/arama?q=RX+7800+XT", store: "Teknobiyotik" },
      { name: "AMD Ryzen 5 7600 AM5", category: "İşlemci", individualNewPrice: 7200, buyUrl: "https://www.amazon.com.tr/s?k=Ryzen+5+7600&tag=kasaradar-21", store: "Amazon TR" },
      { name: "ASRock B650M PG Lightning", category: "Anakart", individualNewPrice: 4800, buyUrl: "https://www.teknobiyotik.com/arama?q=B650M+Lightning", store: "Teknobiyotik" },
      { name: "Kingston Fury 32GB (2x16) DDR5", category: "RAM", individualNewPrice: 4200, buyUrl: "https://www.amazon.com.tr/s?k=Kingston+Fury+32GB+DDR5&tag=kasaradar-21", store: "Amazon TR" },
      { name: "Kioxia Exceria G3 1TB NVMe", category: "SSD", individualNewPrice: 2750, buyUrl: "https://www.hepsiburada.com/ara?q=Kioxia+Exceria+G3+1TB&utm_source=kasaradar", store: "Hepsiburada" },
      { name: "Dark AquaForce 240mm Sıvı Soğutma", category: "Soğutucu", individualNewPrice: 2200, buyUrl: "https://www.teknobiyotik.com/arama?q=Dark+AquaForce", store: "Teknobiyotik" },
      { name: "Dark Maxima V30 + 750W Gold PSU", category: "Kasa", individualNewPrice: 4500, buyUrl: "https://www.teknobiyotik.com/arama?q=Dark+Maxima+V30", store: "Teknobiyotik" }
    ],
    recommendedMonitors: [MONITORS_DATABASE[1]]
  },

  // 8. SİNERJİ VESPER 7800X3D + 4080 SUPER
  {
    id: "sinerji-vesper-7800x3d",
    title: "Sinerji Vesper Ultimate / RTX 4080 Super",
    seller: "Sinerji",
    sellerLogo: "🟠",
    sellerColor: "#f97316",
    price: 79999,
    oldPrice: 87500,
    installmentsText: "Peşin Fiyatına 6 Taksit: 13.333 TL x 6",
    cpuBrand: "AMD",
    gpuBrand: "Nvidia",
    listedDate: "Bugün 02:10 eklendi",
    cpu: "AMD Ryzen 7 7800X3D (Dünyanın 1 Numaralı Oyun İşlemcisi)",
    cpuTier: 98,
    gpu: "MSI GeForce RTX 4080 SUPER 16G Ventus 3X OC",
    gpuTier: 96,
    gpuVram: "16GB GDDR6X",
    ram: "32GB (2x16GB) Corsair Vengeance RGB 6000MHz CL30",
    ramType: "DDR5",
    ramSizeGb: 32,
    ssd: "2TB Samsung 990 PRO NVMe (7450MB/s)",
    ssdSizeGb: 2000,
    motherboard: "ASUS TUF Gaming B650-Plus WiFi",
    psu: "MSI MAG A850GL 850W PCIe5 80+ Gold",
    caseModel: "NZXT H9 Flow Akvaryum Cam Kasa",
    cooling: "DeepCool LT720 360mm Sıvı Soğutma",
    imageUrl: "https://images.unsplash.com/photo-1624705002806-5d72df19c3ad?auto=format&fit=crop&w=800&q=80",
    directUrl: "https://www.sinerji.gen.tr/arama?q=vesper",
    fpScore: 8.8,
    individualZeroPrice: 94500,
    individualSecondHandPrice: 69000,
    badge: "Üst Düzey Güç",
    highlight: "4K'da tüm oyunları Ray Tracing açık 120+ FPS oynatan, sınır tanımayan tepe model espor & içerik üretim kasası.",
    targetResolution: "4K Gaming",
    warranty: "2 Yıl Resmi Distribütör Garantisi",
    tdpWatts: 540,
    partsBreakdown: [
      { name: "MSI RTX 4080 SUPER 16G Ventus 3X", category: "Ekran Kartı", individualNewPrice: 46500, buyUrl: "https://www.itopya.com/AramaSonuclari/?q=RTX+4080+Super&ref=kasaradar", store: "İtopya" },
      { name: "AMD Ryzen 7 7800X3D 3D V-Cache", category: "İşlemci", individualNewPrice: 15800, buyUrl: "https://www.amazon.com.tr/s?k=Ryzen+7+7800X3D&tag=kasaradar-21", store: "Amazon TR" },
      { name: "ASUS TUF B650-Plus WiFi AM5", category: "Anakart", individualNewPrice: 7900, buyUrl: "https://www.hepsiburada.com/ara?q=ASUS+TUF+B650-Plus&utm_source=kasaradar", store: "Hepsiburada" },
      { name: "Corsair Vengeance RGB 32GB 6000MHz CL30", category: "RAM", individualNewPrice: 5200, buyUrl: "https://www.amazon.com.tr/s?k=Corsair+Vengeance+32GB+6000&tag=kasaradar-21", store: "Amazon TR" },
      { name: "Samsung 990 PRO 2TB 7450MB/s Gen4", category: "SSD", individualNewPrice: 6900, buyUrl: "https://www.amazon.com.tr/s?k=Samsung+990+PRO+2TB&tag=kasaradar-21", store: "Amazon TR" },
      { name: "DeepCool LT720 360mm Sıvı Soğutma", category: "Soğutucu", individualNewPrice: 4200, buyUrl: "https://www.sinerji.gen.tr/arama?q=LT720", store: "Sinerji" },
      { name: "NZXT H9 Flow + MSI 850W Gold PCIe5", category: "Kasa", individualNewPrice: 8000, buyUrl: "https://www.sinerji.gen.tr/arama?q=NZXT+H9", store: "Sinerji" }
    ],
    recommendedMonitors: [MONITORS_DATABASE[2], MONITORS_DATABASE[3]]
  },

  // 9. İTOPYA FRENZY RX 6600 (15.000 TL Bütçe Şampiyonu)
  {
    id: "itopya-frenzy-rx6600",
    title: "Frenzy-V1 / RX 6600 8GB F/P",
    seller: "İtopya",
    sellerLogo: "🟢",
    sellerColor: "#10b981",
    price: 15499,
    oldPrice: 17900,
    installmentsText: "Peşin Fiyatına 3 Taksit: 5.166 TL x 3",
    cpuBrand: "AMD",
    gpuBrand: "AMD",
    listedDate: "Bugün 02:40 eklendi",
    cpu: "AMD Ryzen 5 5500 (4.2GHz 6C/12T 19MB L3)",
    cpuTier: 58,
    gpu: "Sapphire Pulse AMD Radeon RX 6600 8GB",
    gpuTier: 66,
    gpuVram: "8GB GDDR6",
    ram: "16GB (2x8GB) G.Skill Ripjaws 3200MHz DDR4",
    ramType: "DDR4",
    ramSizeGb: 16,
    ssd: "512GB GoodRam PX500 Gen3 M.2 NVMe",
    ssdSizeGb: 512,
    motherboard: "Gigabyte A520M K V2",
    psu: "BitFenix BPA 600W 80+",
    caseModel: "BitFenix Nova Mesh SE 4x ARGB Fanlı Kasa",
    cooling: "AMD Wraith Stealth Orijinal Fan",
    imageUrl: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=800&q=80",
    directUrl: "https://www.itopya.com/AramaSonuclari/?q=frenzy&ref=kasaradar",
    fpScore: 9.7,
    individualZeroPrice: 19800,
    individualSecondHandPrice: 13200,
    badge: "F/P Kralı",
    highlight: "15.000 TL bandının tartışmasız kralı! CS2, Valorant, GTA 5 ve PUBG'de 1080p yüksek ayarlarda 140+ FPS.",
    targetResolution: "1080p Ultra",
    warranty: "2 Yıl Resmi İtopya Garantili",
    tdpWatts: 240,
    partsBreakdown: [
      { name: "Sapphire Pulse RX 6600 8GB", category: "Ekran Kartı", individualNewPrice: 8500, buyUrl: "https://www.amazon.com.tr/s?k=RX+6600+8GB&tag=kasaradar-21", store: "Amazon TR" },
      { name: "AMD Ryzen 5 5500 4.2GHz", category: "İşlemci", individualNewPrice: 3200, buyUrl: "https://www.hepsiburada.com/ara?q=Ryzen+5+5500&utm_source=kasaradar", store: "Hepsiburada" },
      { name: "Gigabyte A520M K V2 AM4", category: "Anakart", individualNewPrice: 2100, buyUrl: "https://www.itopya.com/AramaSonuclari/?q=A520M&ref=kasaradar", store: "İtopya" },
      { name: "G.Skill Ripjaws 16GB (2x8) 3200MHz", category: "RAM", individualNewPrice: 1650, buyUrl: "https://www.amazon.com.tr/s?k=G.Skill+16GB+3200&tag=kasaradar-21", store: "Amazon TR" },
      { name: "GoodRam PX500 512GB NVMe M.2", category: "SSD", individualNewPrice: 1400, buyUrl: "https://www.hepsiburada.com/ara?q=GoodRam+512GB&utm_source=kasaradar", store: "Hepsiburada" },
      { name: "BitFenix Nova Mesh + 600W Kasa & PSU", category: "Kasa", individualNewPrice: 2950, buyUrl: "https://www.itopya.com/AramaSonuclari/?q=Bitfenix+Nova&ref=kasaradar", store: "İtopya" }
    ],
    recommendedMonitors: [MONITORS_DATABASE[0]]
  },

  // 10. VATAN BİLGİSAYAR INTEL 14400F + RTX 4070 DDR5
  {
    id: "vatan-intel-14400f-4070",
    title: "Vatan Pro Gamer / i5 14400F & RTX 4070 DDR5",
    seller: "Vatan Bilgisayar",
    sellerLogo: "🔷",
    sellerColor: "#0284c7",
    price: 41999,
    oldPrice: 46500,
    installmentsText: "Peşin Fiyatına 4 Taksit: 10.499 TL x 4",
    cpuBrand: "Intel",
    gpuBrand: "Nvidia",
    listedDate: "Bugün 02:25 eklendi",
    cpu: "Intel Core i5 14400F (14. Nesil 10C/16T 4.7GHz)",
    cpuTier: 83,
    gpu: "ZOTAC Gaming GeForce RTX 4070 Twin Edge 12GB",
    gpuTier: 87,
    gpuVram: "12GB GDDR6X",
    ram: "16GB Crucial 5200MHz DDR5",
    ramType: "DDR5",
    ramSizeGb: 16,
    ssd: "1TB Kioxia Exceria Plus G3 Gen4 NVMe (5000MB/s)",
    ssdSizeGb: 1000,
    motherboard: "MSI PRO B760M-P DDR5",
    psu: "Thermaltake TR2 S 650W 80+",
    caseModel: "Thermaltake S200 TG ARGB Aydınlatmalı Mesh",
    cooling: "Thermaltake UX200 SE ARGB Kule Tipi Soğutucu",
    imageUrl: "https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=800&q=80",
    directUrl: "https://www.vatanbilgisayar.com/arama/rtx%204070%20hazir%20sistem/",
    fpScore: 9.4,
    individualZeroPrice: 49200,
    individualSecondHandPrice: 36000,
    badge: "En Çok Satan",
    highlight: "14. Nesil Intel işlemci + 12GB RTX 4070 ekran kartı ile 2K Ultra ayarlarda tüm yeni nesil oyunlar için tam canavar.",
    targetResolution: "1440p 2K",
    warranty: "2 Yıl Resmi Vatan Bilgisayar Garantili",
    tdpWatts: 390,
    partsBreakdown: [
      { name: "ZOTAC GeForce RTX 4070 12GB", category: "Ekran Kartı", individualNewPrice: 24500, buyUrl: "https://www.vatanbilgisayar.com/arama/RTX+4070/", store: "Vatan Bilgisayar" },
      { name: "Intel Core i5 14400F 14. Nesil", category: "İşlemci", individualNewPrice: 7200, buyUrl: "https://www.amazon.com.tr/s?k=i5+14400F&tag=kasaradar-21", store: "Amazon TR" },
      { name: "MSI PRO B760M-P DDR5", category: "Anakart", individualNewPrice: 4600, buyUrl: "https://www.hepsiburada.com/ara?q=MSI+B760M-P&utm_source=kasaradar", store: "Hepsiburada" },
      { name: "Crucial 16GB 5200MHz DDR5", category: "RAM", individualNewPrice: 2100, buyUrl: "https://www.amazon.com.tr/s?k=Crucial+16GB+DDR5&tag=kasaradar-21", store: "Amazon TR" },
      { name: "Kioxia Exceria G3 1TB NVMe", category: "SSD", individualNewPrice: 2750, buyUrl: "https://www.hepsiburada.com/ara?q=Kioxia+Exceria+G3&utm_source=kasaradar", store: "Hepsiburada" },
      { name: "Thermaltake S200 + 650W PSU", category: "Kasa", individualNewPrice: 4800, buyUrl: "https://www.vatanbilgisayar.com/arama/Thermaltake+S200/", store: "Vatan Bilgisayar" }
    ],
    recommendedMonitors: [MONITORS_DATABASE[1]]
  },

  // 11. GENÇER GAMİNG PHANTOM
  {
    id: "gencer-phantom-4060ti",
    title: "Gençer Phantom V1 / RTX 4060 Ti",
    seller: "Gençer Gaming",
    sellerLogo: "🟢",
    sellerColor: "#10b981",
    price: 27999,
    oldPrice: 30500,
    installmentsText: "Peşin Fiyatına 3 Taksit: 9.333 TL x 3",
    cpuBrand: "AMD",
    gpuBrand: "Nvidia",
    listedDate: "Bugün 03:00 eklendi",
    cpu: "AMD Ryzen 5 5600 (4.4GHz 6C/12T 32MB L3)",
    cpuTier: 65,
    gpu: "Gainward GeForce RTX 4060 Ti Ghost 8GB",
    gpuTier: 79,
    gpuVram: "8GB GDDR6",
    ram: "16GB (2x8GB) Lexar Thor 3200MHz DDR4",
    ramType: "DDR4",
    ramSizeGb: 16,
    ssd: "1TB Agi High Speed Gen3 NVMe M.2 (3500MB/s)",
    ssdSizeGb: 1000,
    motherboard: "ASUS Prime B450M-K II",
    psu: "FSP Hydro K PRO 600W 80+ Bronze",
    caseModel: "Vento VG10F Temperli Cam ARGB",
    cooling: "AMD Wraith Stealth Orijinal Fan",
    imageUrl: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=800&q=80",
    directUrl: "https://www.gencergaming.com/?s=phantom&ref=kasaradar",
    fpScore: 9.6,
    individualZeroPrice: 33400,
    individualSecondHandPrice: 24000,
    badge: "F/P Kralı",
    highlight: "28.000 TL altına RTX 4060 Ti ve 1TB NVMe depolama! DLSS 3 Kare Oluşturma ile 2K ve 1080p Ultra espor canavarı.",
    targetResolution: "1080p Ultra",
    warranty: "2 Yıl Gençer Gaming Garantili",
    tdpWatts: 310,
    partsBreakdown: [
      { name: "Gainward RTX 4060 Ti Ghost 8GB", category: "Ekran Kartı", individualNewPrice: 16200, buyUrl: "https://www.gencergaming.com/?s=Gainward+4060+Ti", store: "Gençer Gaming" },
      { name: "AMD Ryzen 5 5600 4.4GHz", category: "İşlemci", individualNewPrice: 4100, buyUrl: "https://www.amazon.com.tr/s?k=Ryzen+5+5600&tag=kasaradar-21", store: "Amazon TR" },
      { name: "ASUS Prime B450M-K II", category: "Anakart", individualNewPrice: 2450, buyUrl: "https://www.hepsiburada.com/ara?q=ASUS+B450M-K&utm_source=kasaradar", store: "Hepsiburada" },
      { name: "Lexar Thor 16GB (2x8) 3200MHz", category: "RAM", individualNewPrice: 1600, buyUrl: "https://www.gencergaming.com/?s=Lexar+Thor", store: "Gençer Gaming" },
      { name: "Agi 1TB Gen3 NVMe M.2", category: "SSD", individualNewPrice: 2350, buyUrl: "https://www.gencergaming.com/?s=Agi+1TB", store: "Gençer Gaming" },
      { name: "Vento VG10F + FSP 600W Bronze Kasa & PSU", category: "Kasa", individualNewPrice: 3800, buyUrl: "https://www.gencergaming.com/?s=Vento+VG10F", store: "Gençer Gaming" }
    ],
    recommendedMonitors: [MONITORS_DATABASE[0]]
  },

  // 12. PCKOLİK GHOST
  {
    id: "pckolik-ghost-4070super",
    title: "Pckolik Ghost / i5 13400F & RTX 4070 Super",
    seller: "Pckolik",
    sellerLogo: "🟣",
    sellerColor: "#a855f7",
    price: 44499,
    oldPrice: 48900,
    installmentsText: "Peşin Fiyatına 4 Taksit: 11.124 TL x 4",
    cpuBrand: "Intel",
    gpuBrand: "Nvidia",
    listedDate: "Bugün 03:15 eklendi",
    cpu: "Intel Core i5 13400F (10C/16T 4.6GHz)",
    cpuTier: 78,
    gpu: "Inno3D GeForce RTX 4070 SUPER Twin X2 12GB",
    gpuTier: 89,
    gpuVram: "12GB GDDR6X",
    ram: "32GB (2x16GB) G.Skill Ripjaws 3200MHz DDR4",
    ramType: "DDR4",
    ramSizeGb: 32,
    ssd: "1TB Kingston NV2 Gen4 M.2 NVMe (3500MB/s)",
    ssdSizeGb: 1000,
    motherboard: "Gigabyte B760M DS3H DDR4",
    psu: "Xigmatek 700W 80+ Gold",
    caseModel: "Xigmatek Master X ARGB Aydınlatmalı Mesh",
    cooling: "Thermalright Assassin Spirit 120 V2 Kule Tipi",
    imageUrl: "https://images.unsplash.com/photo-1587202372634-32705e3bf49c?auto=format&fit=crop&w=800&q=80",
    directUrl: "https://pckolik.com/arama?q=ghost&ref=kasaradar",
    fpScore: 9.5,
    individualZeroPrice: 52100,
    individualSecondHandPrice: 38500,
    badge: "Haftanın Fırsatı",
    highlight: "12GB GDDR6X RTX 4070 SUPER gücü! 32GB RAM ile 2K ve 4K'da tüm güncel oyunları ultra ayarlarda 120+ FPS akıcı oynatır.",
    targetResolution: "1440p 2K",
    warranty: "2 Yıl Pckolik Garantili",
    tdpWatts: 410,
    partsBreakdown: [
      { name: "Inno3D RTX 4070 SUPER 12GB", category: "Ekran Kartı", individualNewPrice: 26000, buyUrl: "https://pckolik.com/arama?q=Inno3D+4070+Super", store: "Pckolik" },
      { name: "Intel Core i5 13400F", category: "İşlemci", individualNewPrice: 6800, buyUrl: "https://www.amazon.com.tr/s?k=i5+13400F&tag=kasaradar-21", store: "Amazon TR" },
      { name: "Gigabyte B760M DS3H DDR4", category: "Anakart", individualNewPrice: 4200, buyUrl: "https://www.hepsiburada.com/ara?q=Gigabyte+B760M&utm_source=kasaradar", store: "Hepsiburada" },
      { name: "G.Skill Ripjaws 32GB (2x16) 3200MHz", category: "RAM", individualNewPrice: 3100, buyUrl: "https://www.amazon.com.tr/s?k=G.Skill+32GB+DDR4&tag=kasaradar-21", store: "Amazon TR" },
      { name: "Kingston NV2 1TB Gen4 NVMe", category: "SSD", individualNewPrice: 2600, buyUrl: "https://www.hepsiburada.com/ara?q=Kingston+NV2+1TB&utm_source=kasaradar", store: "Hepsiburada" },
      { name: "Thermalright Assassin Spirit 120 V2", category: "Soğutucu", individualNewPrice: 1100, buyUrl: "https://pckolik.com/arama?q=Thermalright", store: "Pckolik" },
      { name: "Xigmatek Master X + 700W Gold Kasa & PSU", category: "Kasa", individualNewPrice: 4300, buyUrl: "https://pckolik.com/arama?q=Xigmatek+Master", store: "Pckolik" }
    ],
    recommendedMonitors: [MONITORS_DATABASE[1], MONITORS_DATABASE[2]]
  },

  // 13. QP BİLİŞİM ECLIPSE
  {
    id: "qp-eclipse-ryzen7-7700x",
    title: "QP Eclipse Pro / Ryzen 7 7700X & RX 7800 XT",
    seller: "QP Bilişim",
    sellerLogo: "🔴",
    sellerColor: "#ef4444",
    price: 49999,
    oldPrice: 55000,
    installmentsText: "Peşin Fiyatına 4 Taksit: 12.499 TL x 4",
    cpuBrand: "AMD",
    gpuBrand: "AMD",
    listedDate: "Bugün 04:00 eklendi",
    cpu: "AMD Ryzen 7 7700X AM5 (5.4GHz 8C/16T)",
    cpuTier: 89,
    gpu: "Sapphire Nitro+ Radeon RX 7800 XT 16GB",
    gpuTier: 88,
    gpuVram: "16GB GDDR6",
    ram: "32GB (2x16GB) Corsair Vengeance 6000MHz CL30 DDR5",
    ramType: "DDR5",
    ramSizeGb: 32,
    ssd: "1TB Kingston KC3000 Gen4 M.2 NVMe (7000MB/s)",
    ssdSizeGb: 1000,
    motherboard: "ASUS TUF Gaming B650-PLUS WIFI",
    psu: "Corsair RM750e 750W 80+ Gold Tam Modüler",
    caseModel: "Corsair 4000D Airflow Temperli Cam Mesh",
    cooling: "DeepCool LT520 240mm RGB Sıvı Soğutma",
    imageUrl: "https://images.unsplash.com/photo-1587202372634-32705e3bf49c?auto=format&fit=crop&w=800&q=80",
    directUrl: "https://www.qp.com.tr/catalogsearch/result/?q=eclipse&ref=kasaradar",
    fpScore: 9.6,
    individualZeroPrice: 58200,
    individualSecondHandPrice: 42000,
    badge: "2K & 4K Canavarı",
    highlight: "16GB VRAM + Ryzen 7 7700X ve 32GB 6000MHz CL30 RAM! 240mm sıvı soğutmalı komple espor ve render istasyonu.",
    targetResolution: "1440p 2K",
    warranty: "2 Yıl QP Bilişim Garantili",
    tdpWatts: 420,
    partsBreakdown: [
      { name: "Sapphire Nitro+ RX 7800 XT 16GB", category: "Ekran Kartı", individualNewPrice: 22500, buyUrl: "https://www.qp.com.tr/catalogsearch/result/?q=RX+7800+XT", store: "QP Bilişim" },
      { name: "AMD Ryzen 7 7700X AM5", category: "İşlemci", individualNewPrice: 11500, buyUrl: "https://www.amazon.com.tr/s?k=Ryzen+7+7700X&tag=kasaradar-21", store: "Amazon TR" },
      { name: "ASUS TUF B650-PLUS WIFI", category: "Anakart", individualNewPrice: 8200, buyUrl: "https://www.hepsiburada.com/ara?q=ASUS+TUF+B650&utm_source=kasaradar", store: "Hepsiburada" },
      { name: "Corsair Vengeance 32GB 6000MHz", category: "RAM", individualNewPrice: 4600, buyUrl: "https://www.amazon.com.tr/s?k=Corsair+32GB+6000MHz&tag=kasaradar-21", store: "Amazon TR" },
      { name: "Kingston KC3000 1TB Gen4 NVMe", category: "SSD", individualNewPrice: 3800, buyUrl: "https://www.hepsiburada.com/ara?q=Kingston+KC3000+1TB&utm_source=kasaradar", store: "Hepsiburada" },
      { name: "DeepCool LT520 240mm Sıvı Soğutma", category: "Soğutucu", individualNewPrice: 3100, buyUrl: "https://www.qp.com.tr/catalogsearch/result/?q=LT520", store: "QP Bilişim" },
      { name: "Corsair 4000D + RM750e Gold PSU", category: "Kasa", individualNewPrice: 6500, buyUrl: "https://www.qp.com.tr/catalogsearch/result/?q=4000D", store: "QP Bilişim" }
    ],
    recommendedMonitors: [MONITORS_DATABASE[1], MONITORS_DATABASE[2]]
  },

  // 14. INVENTUS ARES
  {
    id: "inventus-ares-4060ti",
    title: "Inventus Ares / i5 13400F & RTX 4060 Ti DDR5",
    seller: "Inventus",
    sellerLogo: "🔵",
    sellerColor: "#2563eb",
    price: 33499,
    oldPrice: 36999,
    installmentsText: "Peşin Fiyatına 3 Taksit: 11.166 TL x 3",
    cpuBrand: "Intel",
    gpuBrand: "Nvidia",
    listedDate: "Bugün 04:30 eklendi",
    cpu: "Intel Core i5 13400F (10C/16T 4.6GHz)",
    cpuTier: 78,
    gpu: "ASUS Dual GeForce RTX 4060 Ti OC 8GB",
    gpuTier: 79,
    gpuVram: "8GB GDDR6",
    ram: "16GB (2x8GB) Kingston Fury Beast 5600MHz DDR5",
    ramType: "DDR5",
    ramSizeGb: 16,
    ssd: "1TB Kioxia Exceria Plus G3 Gen4 (5000MB/s)",
    ssdSizeGb: 1000,
    motherboard: "ASUS Prime B760M-K DDR5",
    psu: "FSP Hyper Pro 650W 80+",
    caseModel: "Vento VG15FE ARGB Mesh Kasa",
    cooling: "ID-Cooling SE-214-XT ARGB",
    imageUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80",
    directUrl: "https://inventus.com.tr/mi_products/ProductList.aspx?DT=ares",
    fpScore: 9.4,
    individualZeroPrice: 38800,
    individualSecondHandPrice: 28500,
    badge: "DDR5 Tavsiye",
    highlight: "Inventus mühendisleri tarafından montaj ve 24 saat stres testi onaylı. Yeni nesil DDR5 platform.",
    targetResolution: "1080p Ultra",
    warranty: "2 Yıl Birebir Değişim Inventus Garantisi",
    tdpWatts: 320,
    partsBreakdown: [
      { name: "ASUS Dual RTX 4060 Ti 8GB", category: "Ekran Kartı", individualNewPrice: 17500, buyUrl: "https://inventus.com.tr/mi_products/ProductList.aspx?DT=4060+Ti", store: "Inventus" },
      { name: "Intel Core i5 13400F", category: "İşlemci", individualNewPrice: 6800, buyUrl: "https://www.amazon.com.tr/s?k=i5+13400F&tag=kasaradar-21", store: "Amazon TR" },
      { name: "ASUS Prime B760M-K DDR5", category: "Anakart", individualNewPrice: 4400, buyUrl: "https://inventus.com.tr/mi_products/ProductList.aspx?DT=B760M-K", store: "Inventus" },
      { name: "Kingston Fury 16GB DDR5", category: "RAM", individualNewPrice: 2200, buyUrl: "https://www.amazon.com.tr/s?k=Kingston+Fury+16GB+DDR5&tag=kasaradar-21", store: "Amazon TR" },
      { name: "Kioxia Exceria G3 1TB NVMe", category: "SSD", individualNewPrice: 2750, buyUrl: "https://www.hepsiburada.com/ara?q=Kioxia+Exceria+G3&utm_source=kasaradar", store: "Hepsiburada" },
      { name: "ID-Cooling SE-214-XT", category: "Soğutucu", individualNewPrice: 1100, buyUrl: "https://inventus.com.tr/mi_products/ProductList.aspx?DT=SE-214-XT", store: "Inventus" },
      { name: "Vento VG15FE + FSP 650W PSU", category: "Kasa", individualNewPrice: 4050, buyUrl: "https://inventus.com.tr/mi_products/ProductList.aspx?DT=VG15FE", store: "Inventus" }
    ],
    recommendedMonitors: [MONITORS_DATABASE[0]]
  },

  // 15. MOLEKÜL PC QUANTUM
  {
    id: "molekul-quantum-rx7700xt",
    title: "Molekül Quantum V2 / Ryzen 5 7600 & RX 7700 XT",
    seller: "Molekül PC",
    sellerLogo: "🧪",
    sellerColor: "#06b6d4",
    price: 36499,
    oldPrice: 40500,
    installmentsText: "Peşin Fiyatına 3 Taksit: 12.166 TL x 3",
    cpuBrand: "AMD",
    gpuBrand: "AMD",
    listedDate: "Bugün 05:00 eklendi",
    cpu: "AMD Ryzen 5 7600 AM5 (5.1GHz 6C/12T)",
    cpuTier: 84,
    gpu: "XFX Speedster QICK 319 Radeon RX 7700 XT 12GB",
    gpuTier: 84,
    gpuVram: "12GB GDDR6",
    ram: "16GB Kingston Fury Beast 5600MHz DDR5",
    ramType: "DDR5",
    ramSizeGb: 16,
    ssd: "1TB Kingston NV2 Gen4 M.2 (3500MB/s)",
    ssdSizeGb: 1000,
    motherboard: "MSI PRO A620M-E AM5",
    psu: "High Power 700W 80+ Bronze",
    caseModel: "Zalman i3 Neo ARGB Mesh Kasa",
    cooling: "Dark Freezer X127 ARGB Kule Tipi",
    imageUrl: "https://images.unsplash.com/photo-1552831388-6a0b3575b35a?auto=format&fit=crop&w=800&q=80",
    directUrl: "https://molekulpc.com/arama?q=quantum",
    fpScore: 9.3,
    individualZeroPrice: 42600,
    individualSecondHandPrice: 31200,
    badge: "F/P Canavarı",
    highlight: "12GB GDDR6 bellek genişliğiyle 2K çözünürlükte VRAM sıkıntısı yaşamayan, AM5 soket ömürlü sistem.",
    targetResolution: "1440p 2K",
    warranty: "2 Yıl Molekül PC Garantili",
    tdpWatts: 370,
    partsBreakdown: [
      { name: "XFX RX 7700 XT 12GB QICK 319", category: "Ekran Kartı", individualNewPrice: 19800, buyUrl: "https://molekulpc.com/arama?q=RX+7700+XT", store: "Molekül PC" },
      { name: "AMD Ryzen 5 7600 AM5", category: "İşlemci", individualNewPrice: 7200, buyUrl: "https://www.amazon.com.tr/s?k=Ryzen+5+7600&tag=kasaradar-21", store: "Amazon TR" },
      { name: "MSI PRO A620M-E AM5", category: "Anakart", individualNewPrice: 3800, buyUrl: "https://molekulpc.com/arama?q=A620M-E", store: "Molekül PC" },
      { name: "Kingston Fury 16GB DDR5", category: "RAM", individualNewPrice: 2200, buyUrl: "https://www.amazon.com.tr/s?k=Kingston+Fury+16GB&tag=kasaradar-21", store: "Amazon TR" },
      { name: "Kingston NV2 1TB Gen4", category: "SSD", individualNewPrice: 2600, buyUrl: "https://www.hepsiburada.com/ara?q=Kingston+NV2+1TB&utm_source=kasaradar", store: "Hepsiburada" },
      { name: "Dark Freezer X127 Soğutucu", category: "Soğutucu", individualNewPrice: 1100, buyUrl: "https://molekulpc.com/arama?q=Freezer+X127", store: "Molekül PC" },
      { name: "Zalman i3 Neo + 700W Bronze PSU", category: "Kasa", individualNewPrice: 3900, buyUrl: "https://molekulpc.com/arama?q=Zalman+i3", store: "Molekül PC" }
    ],
    recommendedMonitors: [MONITORS_DATABASE[1]]
  },

  // 16. NOVABİLGİSAYAR TİTAN
  {
    id: "nova-titan-4070ti-super",
    title: "Nova Titan Ultra / 7800X3D & RTX 4070 Ti Super",
    seller: "Novabilgisayar",
    sellerLogo: "🌟",
    sellerColor: "#eab308",
    price: 64999,
    oldPrice: 71500,
    installmentsText: "Peşin Fiyatına 6 Taksit: 10.833 TL x 6",
    cpuBrand: "AMD",
    gpuBrand: "Nvidia",
    listedDate: "Bugün 05:20 eklendi",
    cpu: "AMD Ryzen 7 7800X3D (3D V-Cache Espor Şampiyonu)",
    cpuTier: 96,
    gpu: "Palit GeForce RTX 4070 Ti SUPER GamingPro 16GB",
    gpuTier: 94,
    gpuVram: "16GB GDDR6X",
    ram: "32GB (2x16GB) G.Skill Flare X5 6000MHz CL32 DDR5",
    ramType: "DDR5",
    ramSizeGb: 32,
    ssd: "1TB Samsung 980 Pro NVMe (7000MB/s)",
    ssdSizeGb: 1000,
    motherboard: "Gigabyte B650 Gaming X AX WIFI AM5",
    psu: "Enermax Revolution D.F. 850W 80+ Gold",
    caseModel: "Lian Li Lancool III RGB Temperli Cam",
    cooling: "Thermalright Frozen Prism 360mm Sıvı Soğutma",
    imageUrl: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=800&q=80",
    directUrl: "https://www.novabilgisayar.com/arama.asp?kelime=titan",
    fpScore: 9.7,
    individualZeroPrice: 74800,
    individualSecondHandPrice: 56000,
    badge: "Espor Zirvesi",
    highlight: "Dünyanın en iyi oyun işlemcisi Ryzen 7 7800X3D + 16GB RTX 4070 Ti SUPER! 360mm sıvı soğutmalı tavizsiz amiral gemisi.",
    targetResolution: "4K Gaming",
    warranty: "2 Yıl Novabilgisayar Garantisi",
    tdpWatts: 450,
    partsBreakdown: [
      { name: "Palit RTX 4070 Ti SUPER 16GB", category: "Ekran Kartı", individualNewPrice: 35000, buyUrl: "https://www.novabilgisayar.com/arama.asp?kelime=4070+Ti+Super", store: "Novabilgisayar" },
      { name: "AMD Ryzen 7 7800X3D", category: "İşlemci", individualNewPrice: 16500, buyUrl: "https://www.amazon.com.tr/s?k=Ryzen+7+7800X3D&tag=kasaradar-21", store: "Amazon TR" },
      { name: "Gigabyte B650 Gaming X AX WIFI", category: "Anakart", individualNewPrice: 7800, buyUrl: "https://www.novabilgisayar.com/arama.asp?kelime=B650+Gaming+X", store: "Novabilgisayar" },
      { name: "G.Skill Flare X5 32GB 6000MHz", category: "RAM", individualNewPrice: 4600, buyUrl: "https://www.amazon.com.tr/s?k=G.Skill+Flare+X5&tag=kasaradar-21", store: "Amazon TR" },
      { name: "Samsung 980 Pro 1TB NVMe", category: "SSD", individualNewPrice: 4200, buyUrl: "https://www.hepsiburada.com/ara?q=Samsung+980+Pro+1TB&utm_source=kasaradar", store: "Hepsiburada" },
      { name: "Thermalright 360mm Sıvı Soğutma", category: "Soğutucu", individualNewPrice: 3200, buyUrl: "https://www.novabilgisayar.com/arama.asp?kelime=Frozen+Prism", store: "Novabilgisayar" },
      { name: "Lian Li Lancool III + 850W Gold PSU", category: "Kasa", individualNewPrice: 7500, buyUrl: "https://www.novabilgisayar.com/arama.asp?kelime=Lancool+III", store: "Novabilgisayar" }
    ],
    recommendedMonitors: [MONITORS_DATABASE[2], MONITORS_DATABASE[3]]
  },

  // 17. DFS BİLGİSAYAR GLADIATOR
  {
    id: "dfs-gladiator-4060",
    title: "DFS Gladiator / Ryzen 5 5600 & RTX 4060",
    seller: "DFS Bilgisayar",
    sellerLogo: "🛡️",
    sellerColor: "#14b8a6",
    price: 21999,
    oldPrice: 24500,
    installmentsText: "Peşin Fiyatına 3 Taksit: 7.333 TL x 3",
    cpuBrand: "AMD",
    gpuBrand: "Nvidia",
    listedDate: "Bugün 05:40 eklendi",
    cpu: "AMD Ryzen 5 5600 (4.4GHz 6C/12T 32MB L3)",
    cpuTier: 65,
    gpu: "PNY GeForce RTX 4060 Verto Dual 8GB",
    gpuTier: 72,
    gpuVram: "8GB GDDR6",
    ram: "16GB (2x8GB) Lexar Thor 3200MHz DDR4",
    ramType: "DDR4",
    ramSizeGb: 16,
    ssd: "500GB Kingston NV2 NVMe M.2",
    ssdSizeGb: 500,
    motherboard: "Gigabyte A520M K V2",
    psu: "FSP 550W 80+ Bronze",
    caseModel: "Gametech Colder Mesh 4x Fan ARGB",
    cooling: "AMD Orijinal Wraith Stealth",
    imageUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80",
    directUrl: "https://www.dfsbilgisayar.com/arama?q=gladiator",
    fpScore: 9.5,
    individualZeroPrice: 26400,
    individualSecondHandPrice: 18500,
    badge: "F/P Yıldızı",
    highlight: "22.000 TL bandında DLSS 3 Kare Oluşturma destekli en uygun fiyatlı ve sessiz çalışan hazır sistem.",
    targetResolution: "1080p Ultra",
    warranty: "2 Yıl DFS Bilgisayar Güvencesi",
    tdpWatts: 275,
    partsBreakdown: [
      { name: "PNY RTX 4060 Verto Dual 8GB", category: "Ekran Kartı", individualNewPrice: 12900, buyUrl: "https://www.dfsbilgisayar.com/arama?q=PNY+4060", store: "DFS Bilgisayar" },
      { name: "AMD Ryzen 5 5600", category: "İşlemci", individualNewPrice: 4100, buyUrl: "https://www.amazon.com.tr/s?k=Ryzen+5+5600&tag=kasaradar-21", store: "Amazon TR" },
      { name: "Gigabyte A520M K V2", category: "Anakart", individualNewPrice: 2200, buyUrl: "https://www.dfsbilgisayar.com/arama?q=A520M", store: "DFS Bilgisayar" },
      { name: "Lexar Thor 16GB DDR4", category: "RAM", individualNewPrice: 1550, buyUrl: "https://www.dfsbilgisayar.com/arama?q=Lexar+Thor", store: "DFS Bilgisayar" },
      { name: "Kingston NV2 500GB NVMe", category: "SSD", individualNewPrice: 1650, buyUrl: "https://www.hepsiburada.com/ara?q=Kingston+NV2+500GB&utm_source=kasaradar", store: "Hepsiburada" },
      { name: "Gametech Colder + FSP 550W PSU", category: "Kasa", individualNewPrice: 3400, buyUrl: "https://www.dfsbilgisayar.com/arama?q=Gametech+Colder", store: "DFS Bilgisayar" }
    ],
    recommendedMonitors: [MONITORS_DATABASE[0]]
  },

  // 18. ADEKS STORE ESPORTS
  {
    id: "adeks-esports-4060ti",
    title: "Adeks Pro Esports / i5 14400F & RTX 4060 Ti 16GB",
    seller: "Adeks Store",
    sellerLogo: "🏆",
    sellerColor: "#f43f5e",
    price: 37999,
    oldPrice: 42000,
    installmentsText: "Peşin Fiyatına 4 Taksit: 9.499 TL x 4",
    cpuBrand: "Intel",
    gpuBrand: "Nvidia",
    listedDate: "Bugün 06:00 eklendi",
    cpu: "Intel Core i5 14400F (14. Nesil 10C/16T)",
    cpuTier: 83,
    gpu: "Gigabyte GeForce RTX 4060 Ti Gaming OC 16GB",
    gpuTier: 80,
    gpuVram: "16GB GDDR6",
    ram: "32GB (2x16GB) Corsair Vengeance 3600MHz DDR4",
    ramType: "DDR4",
    ramSizeGb: 32,
    ssd: "1TB WD Black SN770 Gen4 NVMe (5150MB/s)",
    ssdSizeGb: 1000,
    motherboard: "MSI PRO B760M-E DDR4",
    psu: "DeepCool PK650D 650W 80+ Bronze",
    caseModel: "DeepCool CC560 WH V2 Beyaz Mesh",
    cooling: "DeepCool AG400 ARGB Kule Tipi Soğutucu",
    imageUrl: "https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=800&q=80",
    directUrl: "https://www.adeksstore.com/arama?q=esports",
    fpScore: 9.5,
    individualZeroPrice: 44200,
    individualSecondHandPrice: 32500,
    badge: "16GB VRAM Özel",
    highlight: "16GB dev VRAM kapasitesiyle RTX 4060 Ti! Ağır dokulu oyunlar ve yapay zeka render için tam profesyonel Adeks konfigürasyonu.",
    targetResolution: "1080p Ultra",
    warranty: "2 Yıl Adeks Store Garantili",
    tdpWatts: 340,
    partsBreakdown: [
      { name: "Gigabyte RTX 4060 Ti 16GB Gaming OC", category: "Ekran Kartı", individualNewPrice: 20500, buyUrl: "https://www.adeksstore.com/arama?q=4060+Ti+16GB", store: "Adeks Store" },
      { name: "Intel Core i5 14400F", category: "İşlemci", individualNewPrice: 7200, buyUrl: "https://www.amazon.com.tr/s?k=i5+14400F&tag=kasaradar-21", store: "Amazon TR" },
      { name: "MSI PRO B760M-E DDR4", category: "Anakart", individualNewPrice: 3900, buyUrl: "https://www.adeksstore.com/arama?q=B760M-E", store: "Adeks Store" },
      { name: "Corsair Vengeance 32GB 3600MHz", category: "RAM", individualNewPrice: 3300, buyUrl: "https://www.amazon.com.tr/s?k=Corsair+32GB+3600&tag=kasaradar-21", store: "Amazon TR" },
      { name: "WD Black SN770 1TB NVMe", category: "SSD", individualNewPrice: 3200, buyUrl: "https://www.hepsiburada.com/ara?q=WD+SN770+1TB&utm_source=kasaradar", store: "Hepsiburada" },
      { name: "DeepCool AG400 ARGB", category: "Soğutucu", individualNewPrice: 1100, buyUrl: "https://www.adeksstore.com/arama?q=AG400", store: "Adeks Store" },
      { name: "DeepCool CC560 WH + 650W PSU", category: "Kasa", individualNewPrice: 4400, buyUrl: "https://www.adeksstore.com/arama?q=CC560", store: "Adeks Store" }
    ],
    recommendedMonitors: [MONITORS_DATABASE[0], MONITORS_DATABASE[2]]
  }
];

export const GAMES: GameRequirement[] = [
  {
    id: "cs2",
    title: "Counter-Strike 2",
    genre: "Rekabetçi E-Spor FPS",
    coverImage: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=600&q=80",
    releaseYear: 2023,
    description: "Valve'ın Source 2 motoruyla yenilenen rekabetçi FPS devi. İşlemci önbelleğine (L3 Cache) ve tek çekirdek gücüne aşırı duyarlıdır.",
    minCpuTier: 45,
    recCpuTier: 75,
    minGpuTier: 40,
    recGpuTier: 68,
    minRamGb: 8,
    recRamGb: 16,
    storageGb: 85,
    cpuWeight: 0.65,
    gpuWeight: 0.35,
    ramWeight: 0.1,
    baseFps1080pLow: 240
  },
  {
    id: "valorant",
    title: "Valorant",
    genre: "Taktiksel E-Spor Nişancı",
    coverImage: "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=600&q=80",
    releaseYear: 2020,
    description: "Riot Games'in taktiksel nişancı oyunu. Neredeyse tamamen işlemciye bakar, iyi bir CPU ile 300+ FPS görmek çok kolaydır.",
    minCpuTier: 35,
    recCpuTier: 65,
    minGpuTier: 30,
    recGpuTier: 50,
    minRamGb: 8,
    recRamGb: 16,
    storageGb: 45,
    cpuWeight: 0.80,
    gpuWeight: 0.20,
    ramWeight: 0.05,
    baseFps1080pLow: 320
  },
  {
    id: "gta6",
    title: "Grand Theft Auto VI",
    genre: "Açık Dünya / Yeni Nesil Aksiyon",
    coverImage: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80",
    releaseYear: 2025,
    description: "Rockstar Games'in yeni nesil RAGE motoru. Yoğun NPC yapay zekası, gelişmiş ışın izleme ve devasa harita nedeniyle hem güçlü CPU hem 12GB+ GPU VRAM isteyecek.",
    minCpuTier: 70,
    recCpuTier: 88,
    minGpuTier: 68,
    recGpuTier: 86,
    minRamGb: 16,
    recRamGb: 32,
    storageGb: 150,
    cpuWeight: 0.45,
    gpuWeight: 0.55,
    ramWeight: 0.20,
    baseFps1080pLow: 75
  },
  {
    id: "cyberpunk",
    title: "Cyberpunk 2077: Phantom Liberty",
    genre: "Açık Dünya / Ray Tracing RPG",
    coverImage: "https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=600&q=80",
    releaseYear: 2023,
    description: "Grafik teknolojisinin zirvesi. Path Tracing ve DLSS 3 testlerinin vazgeçilmez kıyaslama oyunu. Ekran kartını son damlasına kadar zorlar.",
    minCpuTier: 60,
    recCpuTier: 82,
    minGpuTier: 60,
    recGpuTier: 85,
    minRamGb: 16,
    recRamGb: 32,
    storageGb: 90,
    cpuWeight: 0.35,
    gpuWeight: 0.65,
    ramWeight: 0.15,
    baseFps1080pLow: 85
  },
  {
    id: "warzone",
    title: "Call of Duty: Warzone",
    genre: "Battle Royale / E-Spor",
    coverImage: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=600&q=80",
    releaseYear: 2024,
    description: "Aşırı RAM ve VRAM tüketen, optimizasyon gerektiren devasa haritalı savaş oyunu. 16GB RAM yetersiz kalabilmektedir.",
    minCpuTier: 60,
    recCpuTier: 80,
    minGpuTier: 62,
    recGpuTier: 80,
    minRamGb: 16,
    recRamGb: 32,
    storageGb: 120,
    cpuWeight: 0.50,
    gpuWeight: 0.50,
    ramWeight: 0.25,
    baseFps1080pLow: 110
  },
  {
    id: "wukong",
    title: "Black Myth: Wukong",
    genre: "Unreal Engine 5 Aksiyon",
    coverImage: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80",
    releaseYear: 2024,
    description: "Unreal Engine 5 Lumen ve Nanite motorunu kullanan yeni nesil başyapıt. Ekran kartının shader birimlerini yoğun kullanır.",
    minCpuTier: 65,
    recCpuTier: 84,
    minGpuTier: 65,
    recGpuTier: 86,
    minRamGb: 16,
    recRamGb: 32,
    storageGb: 130,
    cpuWeight: 0.40,
    gpuWeight: 0.60,
    ramWeight: 0.15,
    baseFps1080pLow: 80
  }
];

export const HARDWARE_DATABASE: HardwareComponent[] = [
  // GPUs
  {
    id: "rtx-4060",
    name: "Nvidia GeForce RTX 4060 8GB",
    type: "gpu",
    tier: 72,
    brand: "Nvidia",
    newPriceAvg: 12900,
    secondHandAvg: 9500,
    dealPriceThreshold: 8500,
    secondHandRisk: "Düşük Risk",
    riskReason: "Yeni nesil olduğu için mining dönemine denk gelmedi. Garantili bulma şansı çok yüksek.",
    specsSummary: "8GB GDDR6, 115W TDP, DLSS 3 Frame Gen",
    directBuyUrl: "https://www.amazon.com.tr/s?k=RTX+4060&tag=kasaradar-21",
    direct2ndHandUrl: "https://www.sahibinden.com/kelime-ile-arama?query_text=RTX+4060"
  },
  {
    id: "rtx-3050",
    name: "Nvidia GeForce RTX 3050 8GB",
    type: "gpu",
    tier: 55,
    brand: "Nvidia",
    newPriceAvg: 8600,
    secondHandAvg: 5400,
    dealPriceThreshold: 4700,
    secondHandRisk: "Düşük Risk",
    riskReason: "Bütçe dostu 1080p kartı. DLSS desteğiyle popüler e-spor oyunlarında stabil çalışır.",
    specsSummary: "8GB GDDR6, 130W TDP, DLSS Desteği",
    directBuyUrl: "https://www.amazon.com.tr/s?k=RTX+3050+8GB&tag=kasaradar-21",
    direct2ndHandUrl: "https://www.sahibinden.com/kelime-ile-arama?query_text=RTX+3050"
  },
  {
    id: "rtx-4070-super",
    name: "Nvidia GeForce RTX 4070 SUPER 12GB",
    type: "gpu",
    tier: 89,
    brand: "Nvidia",
    newPriceAvg: 26500,
    secondHandAvg: 21500,
    dealPriceThreshold: 19500,
    secondHandRisk: "Düşük Risk",
    riskReason: "2K çözünürlüğün en popüler kartı. Kutulu/faturalı ilanları tercih et.",
    specsSummary: "12GB GDDR6X, 220W TDP, 2K/4K Canavarı",
    directBuyUrl: "https://www.amazon.com.tr/s?k=RTX+4070+SUPER&tag=kasaradar-21",
    direct2ndHandUrl: "https://www.sahibinden.com/kelime-ile-arama?query_text=RTX+4070+Super"
  },
  {
    id: "rtx-3060",
    name: "Nvidia GeForce RTX 3060 12GB",
    type: "gpu",
    tier: 60,
    brand: "Nvidia",
    newPriceAvg: 10500,
    secondHandAvg: 6800,
    dealPriceThreshold: 5900,
    secondHandRisk: "Orta Risk",
    riskReason: "Mining döneminde yoğun kullanılmış olabilir. Furmark testi ve termal pad kontrolü şarttır.",
    specsSummary: "12GB GDDR6, F/P 2. El Tercihi",
    directBuyUrl: "https://www.hepsiburada.com/ara?q=RTX+3060+12GB&utm_source=kasaradar",
    direct2ndHandUrl: "https://www.sahibinden.com/kelime-ile-arama?query_text=RTX+3060"
  },
  {
    id: "rx-6600",
    name: "AMD Radeon RX 6600 8GB",
    type: "gpu",
    tier: 62,
    brand: "AMD",
    newPriceAvg: 8900,
    secondHandAvg: 5200,
    dealPriceThreshold: 4500,
    secondHandRisk: "Düşük Risk",
    riskReason: "Az güç tüketir (100W), soğuk çalışır. 5.000 TL altına 2. elde rakipsizdir.",
    specsSummary: "8GB GDDR6, 100W Düşük Güç Tüketimi",
    directBuyUrl: "https://www.amazon.com.tr/s?k=Radeon+RX+6600&tag=kasaradar-21",
    direct2ndHandUrl: "https://www.sahibinden.com/kelime-ile-arama?query_text=RX+6600"
  },
  {
    id: "rx-7800-xt",
    name: "AMD Radeon RX 7800 XT 16GB",
    type: "gpu",
    tier: 88,
    brand: "AMD",
    newPriceAvg: 20900,
    secondHandAvg: 16800,
    dealPriceThreshold: 15200,
    secondHandRisk: "Düşük Risk",
    riskReason: "16GB devasa VRAM ile geleceğe yatırım. Temiz piyasası geniştir.",
    specsSummary: "16GB GDDR6, 256-bit, 2K/4K Gücü",
    directBuyUrl: "https://www.hepsiburada.com/ara?q=RX+7800+XT&utm_source=kasaradar",
    direct2ndHandUrl: "https://www.sahibinden.com/kelime-ile-arama?query_text=RX+7800+XT"
  },
  // CPUs
  {
    id: "ryzen-5-5600",
    name: "AMD Ryzen 5 5600 (6C/12T 32MB L3)",
    type: "cpu",
    tier: 65,
    brand: "AMD",
    newPriceAvg: 4100,
    secondHandAvg: 2900,
    dealPriceThreshold: 2500,
    secondHandRisk: "Düşük Risk",
    riskReason: "İşlemcilerde mekanik parça yoktur, pinleri yamuk değilse 2. el güvenle alınabilir.",
    specsSummary: "AM4 Soket, 6 Çekirdek, 32MB L3 Cache",
    directBuyUrl: "https://www.hepsiburada.com/ara?q=Ryzen+5+5600&utm_source=kasaradar",
    direct2ndHandUrl: "https://www.sahibinden.com/kelime-ile-arama?query_text=Ryzen+5+5600"
  },
  {
    id: "ryzen-5-7500f",
    name: "AMD Ryzen 5 7500F (AM5 DDR5)",
    type: "cpu",
    tier: 82,
    brand: "AMD",
    newPriceAvg: 5800,
    secondHandAvg: 4400,
    dealPriceThreshold: 3900,
    secondHandRisk: "Düşük Risk",
    riskReason: "AM5 sokette pinler anakartta olduğu için işlemciye zarar gelmesi çok zordur.",
    specsSummary: "AM5 Soket, 5.0 GHz, DDR5 Desteği",
    directBuyUrl: "https://www.amazon.com.tr/s?k=Ryzen+5+7500F&tag=kasaradar-21",
    direct2ndHandUrl: "https://www.sahibinden.com/kelime-ile-arama?query_text=Ryzen+5+7500F"
  },
  {
    id: "ryzen-7-7800x3d",
    name: "AMD Ryzen 7 7800X3D (3D V-Cache)",
    type: "cpu",
    tier: 98,
    brand: "AMD",
    newPriceAvg: 15800,
    secondHandAvg: 12800,
    dealPriceThreshold: 11500,
    secondHandRisk: "Düşük Risk",
    riskReason: "Dünyanın en iyi oyun işlemcisi. İkinci elde piyasası altın gibidir, anında satılır.",
    specsSummary: "96MB 3D V-Cache, Oyun Kralı",
    directBuyUrl: "https://www.amazon.com.tr/s?k=Ryzen+7+7800X3D&tag=kasaradar-21",
    direct2ndHandUrl: "https://www.sahibinden.com/kelime-ile-arama?query_text=Ryzen+7+7800X3D"
  },
  {
    id: "i5-12400f",
    name: "Intel Core i5 12400F",
    type: "cpu",
    tier: 64,
    brand: "Intel",
    newPriceAvg: 4200,
    secondHandAvg: 2800,
    dealPriceThreshold: 2400,
    secondHandRisk: "Düşük Risk",
    riskReason: "Intel LGA1700 soket. İkinci elde uygun fiyatlı bütçe dostu işlemci.",
    specsSummary: "6 Çekirdek / 12 İzlek, 4.4 GHz Turbo",
    directBuyUrl: "https://www.itopya.com/AramaSonuclari/?q=Core+i5+12400F&ref=kasaradar",
    direct2ndHandUrl: "https://www.sahibinden.com/kelime-ile-arama?query_text=i5+12400F"
  },
  // Gaming Gear & Ekipmanlar (2. El Borsası)
  {
    id: "wooting-60he-arbitrage",
    name: "Wooting 60HE+ (Hall Effect Analog)",
    type: "gear",
    tier: 99,
    brand: "Wooting",
    newPriceAvg: 7999,
    secondHandAvg: 5800,
    dealPriceThreshold: 5200,
    secondHandRisk: "Düşük Risk",
    riskReason: "Manyetik switch yapısı sebebiyle mekanik aşınma sıfırdır, ikinci elde oldukça sağlamdır.",
    specsSummary: "Rapid Trigger, 0.1mm Hassasiyet, Lekker Manyetik",
    directBuyUrl: "https://www.amazon.com.tr/s?k=Wooting+60HE&tag=kasaradar-21",
    direct2ndHandUrl: "https://www.sahibinden.com/kelime-ile-arama?query_text=Wooting+60HE"
  },
  {
    id: "logitech-superlight-2-arbitrage",
    name: "Logitech G PRO X Superlight 2",
    type: "gear",
    tier: 96,
    brand: "Logitech G",
    newPriceAvg: 5299,
    secondHandAvg: 3400,
    dealPriceThreshold: 2950,
    secondHandRisk: "Düşük Risk",
    riskReason: "Alırken sol/sağ tık switch hissiyatı ve alt skatez aşınmasını kontrol edin.",
    specsSummary: "60g Tüy Siklet, HERO 2 Sensör, 95 Saat Pil",
    directBuyUrl: "https://www.amazon.com.tr/s?k=Logitech+G+PRO+X+Superlight+2&tag=kasaradar-21",
    direct2ndHandUrl: "https://www.sahibinden.com/kelime-ile-arama?query_text=Superlight+2"
  },
  {
    id: "apex-pro-tkl-arbitrage",
    name: "SteelSeries Apex Pro TKL Gen 3",
    type: "gear",
    tier: 95,
    brand: "SteelSeries",
    newPriceAvg: 6899,
    secondHandAvg: 4500,
    dealPriceThreshold: 3900,
    secondHandRisk: "Düşük Risk",
    riskReason: "OLED ekranının sağlamlığını ve OmniPoint manyetik basış ayarını yazılımdan test edin.",
    specsSummary: "OmniPoint Manyetik, OLED Ekran, Alüminyum Gövde",
    directBuyUrl: "https://www.itopya.com/AramaSonuclari/?q=Apex+Pro+TKL&ref=kasaradar",
    direct2ndHandUrl: "https://www.sahibinden.com/kelime-ile-arama?query_text=Apex+Pro+TKL"
  },
  {
    id: "hyperx-cloud3-arbitrage",
    name: "HyperX Cloud III Wireless",
    type: "gear",
    tier: 91,
    brand: "HyperX",
    newPriceAvg: 4899,
    secondHandAvg: 2900,
    dealPriceThreshold: 2500,
    secondHandRisk: "Düşük Risk",
    riskReason: "USB alıcı (dongle) eksiksiz olmalı, kafa bandı ve deri kulak yastığı yıpranması incelenmeli.",
    specsSummary: "120 Saat Pil, 53mm Sürücüler, Kristal Mikrofon",
    directBuyUrl: "https://www.hepsiburada.com/ara?q=HyperX+Cloud+III+Wireless&utm_source=kasaradar",
    direct2ndHandUrl: "https://www.sahibinden.com/kelime-ile-arama?query_text=Cloud+III+Wireless"
  },
  {
    id: "zowie-xl2566k-arbitrage",
    name: "BenQ ZOWIE XL2566K 360Hz DyAc+",
    type: "monitor",
    tier: 98,
    brand: "BenQ ZOWIE",
    newPriceAvg: 24999,
    secondHandAvg: 17500,
    dealPriceThreshold: 15500,
    secondHandRisk: "Orta Risk",
    riskReason: "360Hz modunda ölü piksel, panel çizikleri ve DyAc+ netlik modülü kesinlikle test edilmelidir.",
    specsSummary: "24.5 inç, 360Hz 0.5ms, DyAc+ Espor Standardı",
    directBuyUrl: "https://www.itopya.com/AramaSonuclari/?q=ZOWIE+XL2566K&ref=kasaradar",
    direct2ndHandUrl: "https://www.sahibinden.com/kelime-ile-arama?query_text=XL2566K"
  },
  {
    id: "viewsonic-vx2780-arbitrage",
    name: "ViewSonic VX2780-2K-PRO 27\" 170Hz",
    type: "monitor",
    tier: 88,
    brand: "ViewSonic",
    newPriceAvg: 7899,
    secondHandAvg: 5200,
    dealPriceThreshold: 4600,
    secondHandRisk: "Düşük Risk",
    riskReason: "IPS glow ve ölü piksel kontrolü yeterlidir, piyasası çok hızlı dönen 2K monitördür.",
    specsSummary: "27 inç 2K QHD (2560x1440), 170Hz Fast IPS 1ms",
    directBuyUrl: "https://www.amazon.com.tr/s?k=ViewSonic+VX2780-2K-PRO&tag=kasaradar-21",
    direct2ndHandUrl: "https://www.sahibinden.com/kelime-ile-arama?query_text=VX2780-2K-PRO"
  }
];

export const STREAMER_SETUPS: StreamerSetup[] = [
  // 1. ELRAENN
  {
    id: "elraenn",
    name: "Tuğkan Gönültaş",
    alias: "Elraenn",
    platform: "Twitch / YouTube",
    avatar: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&w=300&q=80",
    banner: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80",
    description: "Türkiye'nin en çok izlenen yayıncısı. GTA RP, RDR2 ve hikayeli oyunları 4K yayın kalitesinde oynar.",
    primaryGame: "GTA RP / RDR2 / Hikayeli Oyunlar",
    pcSpecs: {
      cpu: "AMD Ryzen 9 7950X (16C/32T 5.7GHz)",
      gpu: "Nvidia GeForce RTX 4090 24GB GDDR6X",
      ram: "64GB DDR5 6000MHz CL30",
      motherboard: "ASUS ROG Crosshair X670E Hero",
      storage: "4TB Samsung 990 Pro NVMe Gen4",
      cooling: "Corsair iCUE H150i Elite 360mm LCD"
    },
    gear: {
      monitor: "Samsung Odyssey Neo G9 49\" 240Hz",
      mouse: "Logitech G Pro X Superlight 2 (Siyah)",
      keyboard: "SteelSeries Apex Pro TKL OmniPoint",
      headset: "Sennheiser HD 660S2 Açık Akustik",
      microphone: "Shure SM7B + TC Helicon GoXLR",
      mousepad: "SteelSeries QcK Heavy XXL",
      chair: "Herman Miller Embody Gaming Chair"
    },
    closestSystemId: "sinerji-vesper-7800x3d"
  },

  // 2. WTCN
  {
    id: "wtcn",
    name: "Ferit Karakaya",
    alias: "wtcN",
    platform: "Kick / YouTube",
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=300&q=80",
    banner: "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1200&q=80",
    description: "Eski profesyonel LoL ve Valorant oyuncusu, BBL Esports kurucusu. Yüksek FPS ve sıfır gecikme odaklı donanım kullanır.",
    primaryGame: "Valorant / CS2 / Rekabetçi",
    pcSpecs: {
      cpu: "AMD Ryzen 7 7800X3D (3D V-Cache Kralı)",
      gpu: "Nvidia GeForce RTX 4080 SUPER 16GB",
      ram: "32GB G.Skill Flare X5 6000MHz CL30",
      motherboard: "ASUS ROG Strix B650E-F Gaming WiFi",
      storage: "2TB Kingston KC3000 Gen4 7000MB/s",
      cooling: "NZXT Kraken Elite 360 RGB White"
    },
    gear: {
      monitor: "BenQ ZOWIE XL2566K 360Hz 0.5ms DyAc+",
      mouse: "Razer Viper V3 Pro Wireless (Beyaz)",
      keyboard: "Wooting 60HE (Analog Rapid Trigger)",
      headset: "HyperX Cloud Alpha Wireless (300 Saat)",
      microphone: "Shure SM7B + Rodecaster Pro II",
      mousepad: "Artisan Ninja FX Zero Soft XL",
      chair: "Secretlab TITAN Evo 2022 Dark Knight"
    },
    closestSystemId: "sinerji-vesper-7800x3d"
  },

  // 3. KENDİNE MÜZİSYEN
  {
    id: "kendinemuzisyen",
    name: "Kemal Can Parlak",
    alias: "Kendine Müzisyen",
    platform: "Twitch / YouTube",
    avatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=300&q=80",
    banner: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=1200&q=80",
    description: "Türkiye'nin en popüler eğlence ve IRL yayıncısı. Ağır oyunları ve müzik kayıtlarını tek makinada işler.",
    primaryGame: "Çeşitli Oyunlar / IRL / Simülasyon",
    pcSpecs: {
      cpu: "AMD Ryzen 9 7900X (12C/24T)",
      gpu: "Nvidia GeForce RTX 4080 16GB",
      ram: "64GB Corsair Dominator Titanium 6000MHz",
      motherboard: "MSI MPG B650 Carbon WiFi",
      storage: "4TB Kingston Fury Renegade NVMe",
      cooling: "MSI MAG CoreLiquid 360R V2"
    },
    gear: {
      monitor: "ASUS ROG Swift PG279QM 240Hz 2K",
      mouse: "Logitech G Pro X Superlight (Beyaz)",
      keyboard: "Corsair K70 RGB TKL Champion",
      headset: "Beyerdynamic DT 990 Pro 250 Ohm",
      microphone: "Neumann TLM 103 + GoXLR",
      mousepad: "SteelSeries QcK Prism Cloth XL",
      chair: "Hawk Gaming Chair Future Serisi"
    },
    closestSystemId: "gamegaraj-hero-4070super"
  },

  // 4. MITHRAIN
  {
    id: "mithrain",
    name: "Cem Karakoç",
    alias: "Mithrain",
    platform: "Twitch / YouTube",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
    banner: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80",
    description: "Eski profesyonel PUBG ve FPS oyuncusu. Keskin aim refleksleri ve saf rekabetçi donanım odaklıdır.",
    primaryGame: "PUBG / Apex Legends / CS2",
    pcSpecs: {
      cpu: "AMD Ryzen 7 7800X3D",
      gpu: "Nvidia GeForce RTX 4070 Ti SUPER 16GB",
      ram: "32GB Kingston Fury Beast 6000MHz",
      motherboard: "ASUS TUF Gaming B650-Plus WiFi",
      storage: "2TB Samsung 990 Pro NVMe",
      cooling: "Thermalright Frozen Horizon 360 ARGB"
    },
    gear: {
      monitor: "BenQ ZOWIE XL2546K 240Hz DyAc+",
      mouse: "Razer DeathAdder V3 Pro Wireless",
      keyboard: "Wooting 60HE Hall Effect",
      headset: "HyperX Cloud II Pro Gaming",
      microphone: "Shure MV7 USB/XLR",
      mousepad: "BenQ ZOWIE G-SR II",
      chair: "DXRacer Master Series"
    },
    closestSystemId: "gamegaraj-hero-4070super"
  },

  // 5. UNLOST
  {
    id: "unlost",
    name: "Cantuğ Özsoy",
    alias: "Unlost",
    platform: "Twitch / YouTube",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80",
    banner: "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1200&q=80",
    description: "CS ve Half-Life efsanesi, Türkiye'nin ilk donanım ve FPS optimizasyon rehberlerini yapan ismi.",
    primaryGame: "Counter-Strike 2 / Half-Life",
    pcSpecs: {
      cpu: "Intel Core i9 14900K (6.0 GHz)",
      gpu: "Nvidia GeForce RTX 4080 16GB",
      ram: "32GB G.Skill Ripjaws S5 6400MHz",
      motherboard: "ASUS Prime Z790-A WiFi",
      storage: "2TB Kingston NV2 Gen4",
      cooling: "DeepCool LS720 360mm Sıvı Soğutma"
    },
    gear: {
      monitor: "Alienware AW2524H 500Hz Fast IPS",
      mouse: "Logitech G Pro X Superlight 2 (Kırmızı)",
      keyboard: "Razer Huntsman V3 Pro TKL",
      headset: "HyperX Cloud III Wireless",
      microphone: "Rode PodMic + USB",
      mousepad: "Unlost Özel Tasarım Espor Pad",
      chair: "xDrive SANCAK Profesyonel Oyuncu Koltuğu"
    },
    closestSystemId: "gaminggen-blade-7500f"
  },

  // 6. JAHREIN
  {
    id: "jahrein",
    name: "Ahmet Sonuç",
    alias: "Jahrein",
    platform: "Kick / YouTube",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=300&q=80",
    banner: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80",
    description: "Türkiye'nin en kıdemli yayıncılarından. Ağır strateji, simülasyon ve açık dünya RPG oyunları oynar.",
    primaryGame: "Tarkov / Total War / Simülasyon",
    pcSpecs: {
      cpu: "AMD Ryzen 9 7950X3D",
      gpu: "Nvidia GeForce RTX 4090 24GB",
      ram: "64GB Corsair Vengeance 6000MHz",
      motherboard: "GIGABYTE X670 AORUS Elite AX",
      storage: "4TB Samsung 990 Pro",
      cooling: "Noctua NH-D15 chromax.black Çift Kule"
    },
    gear: {
      monitor: "Samsung Odyssey Neo G8 32\" 4K 240Hz",
      mouse: "Logitech MX Master 3S / G502X Plus",
      keyboard: "Keychron Q1 Pro Kablosuz Mekanik",
      headset: "Sennheiser HD 600 Açık Kulaklık",
      microphone: "Electro-Voice RE20 Yayıncı Mikrofonu",
      mousepad: "Razer Gigantus V2 3XL",
      chair: "Herman Miller Aeron Ergonomic Chair"
    },
    closestSystemId: "sinerji-vesper-7800x3d"
  },

  // 7. S1MPLE
  {
    id: "s1mple",
    name: "Oleksandr Kostyliev",
    alias: "s1mple (CS2 GOAT)",
    platform: "Pro Espor",
    avatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=300&q=80",
    banner: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=1200&q=80",
    description: "CS:GO ve CS2 tarihinin en iyi oyuncusu (GOAT). Tüm ayarlarını 500+ FPS ve 4:3 çözünürlük için optimize eder.",
    primaryGame: "Counter-Strike 2",
    pcSpecs: {
      cpu: "Intel Core i9 14900KS (6.2 GHz)",
      gpu: "Nvidia GeForce RTX 4090 24GB",
      ram: "32GB Kingston Fury Renegade 7200MHz",
      motherboard: "Z790 AORUS Master",
      storage: "2TB WD Black SN850X",
      cooling: "Lian Li Galahad II LCD 360"
    },
    gear: {
      monitor: "BenQ ZOWIE XL2566K 360Hz DyAc+",
      mouse: "Logitech G Pro X Superlight 2 (Magenta)",
      keyboard: "Logitech G715 Tactile White",
      headset: "Logitech G PRO X 2 Lightspeed",
      microphone: "Audio-Technica AT2020",
      mousepad: "Hator It's Nice to be s1mple Özel",
      chair: "Anda Seat Kaiser 3 XL"
    },
    closestSystemId: "gamegaraj-hero-4070super"
  },

  // 8. TENZ
  {
    id: "tenz",
    name: "Tyson Ngo",
    alias: "TenZ (Valorant Şampiyonu)",
    platform: "Pro Espor",
    avatar: "https://images.unsplash.com/photo-1527980965255-d3b416303d12?auto=format&fit=crop&w=300&q=80",
    banner: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80",
    description: "Sentinels takımının dünya şampiyonu Valorant yıldızı. Mouse ve klavye hassasiyetinde dünya çapında trend belirleyicidir.",
    primaryGame: "Valorant / Aim Lab",
    pcSpecs: {
      cpu: "AMD Ryzen 7 7800X3D",
      gpu: "Nvidia GeForce RTX 4080 16GB",
      ram: "32GB DDR5 6000MHz",
      motherboard: "ASUS ROG Strix X670E",
      storage: "2TB Samsung 980 Pro",
      cooling: "Arctic Liquid Freezer III 360"
    },
    gear: {
      monitor: "BenQ ZOWIE XL2566K 360Hz",
      mouse: "Finalmouse UltralightX TenZ Edition",
      keyboard: "Wooting 60HE Hall Effect",
      headset: "Xtrfy H1 Pro Gaming",
      microphone: "Shure MV7X XLR",
      mousepad: "Artisan Ninja FX Zero Soft XL",
      chair: "Herman Miller Aeron Graphite"
    },
    closestSystemId: "gaminggen-blade-7500f"
  },

  // 9. SHROUD
  {
    id: "shroud",
    name: "Michael Grzesiek",
    alias: "shroud (İnsan Aim Botu)",
    platform: "Twitch / YouTube",
    avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=300&q=80",
    banner: "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1200&q=80",
    description: "Eski Cloud9 CS:GO profesyoneli, tüm FPS dünyasının en saygı duyulan aim ustası.",
    primaryGame: "Tüm FPS Oyunları / Rekabetçi",
    pcSpecs: {
      cpu: "AMD Ryzen 9 7950X3D",
      gpu: "Nvidia GeForce RTX 4090 24GB",
      ram: "64GB G.Skill Trident Z5 6000MHz",
      motherboard: "ASUS ROG Crosshair X670E Extreme",
      storage: "4TB Samsung 990 Pro",
      cooling: "Corsair iCUE LINK H150i LCD"
    },
    gear: {
      monitor: "ASUS ROG Swift OLED PG27AQDM 240Hz",
      mouse: "Logitech G303 Shroud Edition Wireless",
      keyboard: "Logitech G PRO X TKL Lightspeed",
      headset: "Logitech G PRO X 2 Lightspeed",
      microphone: "Shure SM7B + Cloudlifter CL-1",
      mousepad: "Logitech G840 Shroud Edition XL",
      chair: "Herman Miller Embody Cyan"
    },
    closestSystemId: "sinerji-vesper-7800x3d"
  },

  // 10. NIKO
  {
    id: "niko",
    name: "Nikola Kovač",
    alias: "NiKo (CS2 Deagle Kralı)",
    platform: "Pro Espor",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80",
    banner: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=1200&q=80",
    description: "G2 Esports ve Falcons yıldızı, CS tarihinin tartışmasız en iyi rifler oyuncusu.",
    primaryGame: "Counter-Strike 2",
    pcSpecs: {
      cpu: "AMD Ryzen 7 7800X3D (3D V-Cache)",
      gpu: "Nvidia GeForce RTX 4080 SUPER 16GB",
      ram: "32GB Kingston Fury 6000MHz",
      motherboard: "ASUS ROG Strix B650E-E",
      storage: "2TB Samsung 990 Pro",
      cooling: "Lian Li Galahad II Trinity 360"
    },
    gear: {
      monitor: "BenQ ZOWIE XL2566K 360Hz 0.5ms",
      mouse: "Logitech G Pro X Superlight 2 (Siyah)",
      keyboard: "Wooting 60HE Hall Effect (Snap Tap)",
      headset: "Logitech G PRO X Lightspeed",
      microphone: "HyperX QuadCast S",
      mousepad: "Lethal Gaming Gear Saturn Pro XL",
      chair: "Secretlab TITAN Evo G2 Esports Edition"
    },
    closestSystemId: "gamegaraj-hero-4070super"
  },

  // 11. XANTARES (Eternal Fire)
  {
    id: "xantares",
    name: "İsmailcan Dörtkardeş",
    alias: "XANTARES (Eternal Fire Efsanesi)",
    platform: "Pro Espor / Twitch",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80",
    banner: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80",
    description: "Eternal Fire takımının dünya çapındaki gururu. 'XANTARES PEEK' teriminin yaratıcısı, CS tarihinin en ölümcül aim ustalarından.",
    primaryGame: "Counter-Strike 2",
    pcSpecs: {
      cpu: "AMD Ryzen 7 7800X3D (3D V-Cache Espor Canavarı)",
      gpu: "Nvidia GeForce RTX 4080 SUPER 16GB",
      ram: "32GB Kingston Fury Renegade 6000MHz CL30",
      motherboard: "ASUS ROG Strix B650E-F Gaming WiFi",
      storage: "2TB Samsung 990 Pro NVMe Gen4",
      cooling: "NZXT Kraken Elite 360 RGB"
    },
    gear: {
      monitor: "BenQ ZOWIE XL2566K 360Hz 0.5ms DyAc+",
      mouse: "ZOWIE EC2-CW Kablosuz Espor Faresi",
      keyboard: "HyperX Alloy Origins Core (Aqua Switch)",
      headset: "HyperX Cloud II Pro Gaming (Kırmızı/Siyah)",
      microphone: "Shure SM7B + TC Helicon GoXLR",
      mousepad: "SteelSeries QcK Heavy XXL (6mm)",
      chair: "xDrive Eternal Fire Özel Seri Oyuncu Koltuğu"
    },
    closestSystemId: "sinerji-vesper-7800x3d"
  },

  // 12. CNED (FUT Esports / Dünya Şampiyonu)
  {
    id: "cned",
    name: "Mehmet Yağız İpek",
    alias: "cNed (Valorant Dünya Şampiyonu)",
    platform: "Pro Espor / Twitch",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
    banner: "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1200&q=80",
    description: "Acend ile Valorant Champions 2021 Dünya Şampiyonu, şu an FUT Esports yıldızı. Jett operatör vuruşlarıyla dünya espor tarihine geçti.",
    primaryGame: "Valorant / Aim Lab",
    pcSpecs: {
      cpu: "AMD Ryzen 7 7800X3D",
      gpu: "Nvidia GeForce RTX 4070 Ti SUPER 16GB",
      ram: "32GB G.Skill Flare X5 6000MHz CL30",
      motherboard: "MSI MAG B650 Tomahawk WiFi",
      storage: "2TB Kingston KC3000 Gen4",
      cooling: "DeepCool LT720 360mm Sıvı Soğutma"
    },
    gear: {
      monitor: "BenQ ZOWIE XL2566K 360Hz DyAc+",
      mouse: "Logitech G Pro X Superlight 2 (Beyaz)",
      keyboard: "Wooting 60HE+ (Rapid Trigger Analog)",
      headset: "HyperX Cloud Alpha Wireless",
      microphone: "HyperX QuadCast S RGB",
      mousepad: "Artisan Ninja FX Zero Soft XL",
      chair: "Secretlab TITAN Evo FUT Esports Edition"
    },
    closestSystemId: "gamegaraj-hero-4070super"
  },

  // 13. RRAENEE
  {
    id: "rraenee",
    name: "Alp Eren",
    alias: "Rraenee",
    platform: "Kick / YouTube",
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=300&q=80",
    banner: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=1200&q=80",
    description: "Türkiye'nin en popüler yayıncılarından. GTA RP, Valorant ve eğlenceli sohbet yayınlarıyla her gün on binlerce izleyiciye hitap eder.",
    primaryGame: "GTA RP / Valorant / CS2",
    pcSpecs: {
      cpu: "AMD Ryzen 9 7900X (12C/24T 5.6GHz)",
      gpu: "Nvidia GeForce RTX 4080 SUPER 16GB",
      ram: "32GB Corsair Vengeance RGB 6000MHz DDR5",
      motherboard: "ASUS ROG Strix X670E-A Gaming WiFi",
      storage: "2TB Samsung 980 Pro NVMe",
      cooling: "Corsair iCUE H150i Elite LCD XT"
    },
    gear: {
      monitor: "ASUS ROG Swift OLED PG27AQDM 240Hz 2K",
      mouse: "Logitech G Pro X Superlight (Siyah)",
      keyboard: "SteelSeries Apex Pro TKL OmniPoint",
      headset: "SteelSeries Arctis Nova Pro Wireless",
      microphone: "Shure SM7B + TC Helicon GoXLR",
      mousepad: "SteelSeries QcK Prism Cloth XL",
      chair: "Hawk Gaming Chair FAB V4"
    },
    closestSystemId: "sinerji-vesper-7800x3d"
  },

  // 14. ERAY
  {
    id: "eray",
    name: "Eray Özkenar",
    alias: "Eray",
    platform: "Twitch / YouTube",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80",
    banner: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80",
    description: "CS2, korku oyunları, GTA RP ve eğlenceli yayınlarıyla Türk Twitch topluluğunun en sevilen yayıncılarından.",
    primaryGame: "CS2 / Korku / Çeşitli Oyunlar",
    pcSpecs: {
      cpu: "Intel Core i7 14700K (20C/28T 5.6GHz)",
      gpu: "Nvidia GeForce RTX 4070 Ti 12GB",
      ram: "32GB Kingston Fury Beast 5600MHz DDR5",
      motherboard: "ASUS Prime Z790-P WiFi",
      storage: "2TB Kioxia Exceria Plus G3 Gen4",
      cooling: "Thermalright Peerless Assassin 120 SE"
    },
    gear: {
      monitor: "BenQ ZOWIE XL2546K 240Hz DyAc+",
      mouse: "Razer DeathAdder V3 Pro Wireless",
      keyboard: "SteelSeries Apex Pro TKL Gen 3",
      headset: "HyperX Cloud III Wireless (120h Pil)",
      microphone: "Rode NT-USB Mini",
      mousepad: "BenQ ZOWIE G-SR-II",
      chair: "xDrive Tufan Profesyonel Oyuncu Koltuğu"
    },
    closestSystemId: "vatan-intel-14400f-4070"
  }
];

export const LIVE_DEAL_ALERTS: DealAlert[] = [
  {
    id: "deal-1",
    systemTitle: "ModArt-X1 V2 Gaming Sistem",
    seller: "İtopya",
    oldPrice: 25499,
    newPrice: 22999,
    dropPercentage: 10,
    timeAgo: "22 dakika önce",
    systemId: "itopya-modart-pc"
  },
  {
    id: "deal-2",
    systemTitle: "HERO 7A-RTX4070 Super Beast",
    seller: "GameGaraj",
    oldPrice: 49999,
    newPrice: 45999,
    dropPercentage: 8,
    timeAgo: "1 saat önce",
    systemId: "gamegaraj-hero-4070super"
  },
  {
    id: "deal-3",
    systemTitle: "Vatan OEM Entry / RTX 3050 8GB",
    seller: "Vatan Bilgisayar",
    oldPrice: 19500,
    newPrice: 16999,
    dropPercentage: 13,
    timeAgo: "2 saat önce",
    systemId: "vatan-oem-rtx3050"
  },
  {
    id: "deal-4",
    systemTitle: "Tebilon Zenith-X / i5 12400F",
    seller: "Tebilon",
    oldPrice: 22800,
    newPrice: 20499,
    dropPercentage: 11,
    timeAgo: "3 saat önce",
    systemId: "tebilon-zenith-4060"
  },
  {
    id: "deal-5",
    systemTitle: "BLADE-7500F / RTX 4060 Ti DDR5",
    seller: "Gaming.Gen.TR",
    oldPrice: 34999,
    newPrice: 31499,
    dropPercentage: 10,
    timeAgo: "5 saat önce",
    systemId: "gaminggen-blade-7500f"
  }
];
