import { GameRequirement } from "./types";

export const GAMES: GameRequirement[] = [
  {
    "id": "cs2",
    "title": "Counter-Strike 2",
    "genre": "Rekabetçi E-Spor FPS",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/header.jpg",
    "releaseYear": 2023,
    "description": "Valve'ın Source 2 motoruyla yenilenen rekabetçi FPS devi. İşlemci önbelleğine (L3 Cache) ve tek çekirdek gücüne aşırı duyarlıdır.",
    "minCpuTier": 45,
    "recCpuTier": 75,
    "minGpuTier": 40,
    "recGpuTier": 68,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 85,
    "cpuWeight": 0.65,
    "gpuWeight": 0.35,
    "ramWeight": 0.1,
    "baseFps1080pLow": 240,
    "steamAppId": 730,
    "platform": "steam"
  },
  {
    "id": "valorant",
    "title": "Valorant",
    "genre": "Taktiksel E-Spor Nişancı",
    "coverImage": "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=600&q=80",
    "releaseYear": 2020,
    "description": "Riot Games'in taktiksel nişancı oyunu. Neredeyse tamamen işlemciye bakar, iyi bir CPU ile 300+ FPS görmek çok kolaydır.",
    "minCpuTier": 35,
    "recCpuTier": 65,
    "minGpuTier": 30,
    "recGpuTier": 50,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 45,
    "cpuWeight": 0.8,
    "gpuWeight": 0.2,
    "ramWeight": 0.05,
    "baseFps1080pLow": 320,
    "platform": "riot"
  },
  {
    "id": "warzone",
    "title": "Call of Duty: Warzone & MW3",
    "genre": "Battle Royale / E-Spor",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1938090/header.jpg",
    "releaseYear": 2024,
    "description": "Aşırı RAM ve VRAM tüketen, optimizasyon gerektiren devasa haritalı savaş oyunu. 16GB RAM yetersiz kalabilmektedir.",
    "minCpuTier": 60,
    "recCpuTier": 82,
    "minGpuTier": 62,
    "recGpuTier": 82,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 125,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.25,
    "baseFps1080pLow": 110,
    "steamAppId": 1938090,
    "platform": "steam"
  },
  {
    "id": "apex",
    "title": "Apex Legends",
    "genre": "Battle Royale / Hızlı FPS",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1172470/header.jpg",
    "releaseYear": 2020,
    "description": "Respawn Entertainment'ın akıcı hareket mekaniklerine sahip battle royale oyunu. Yüksek FPS ve stabil 144Hz+ için dengeli donanım ister.",
    "minCpuTier": 45,
    "recCpuTier": 72,
    "minGpuTier": 45,
    "recGpuTier": 70,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 75,
    "cpuWeight": 0.55,
    "gpuWeight": 0.45,
    "ramWeight": 0.15,
    "baseFps1080pLow": 190,
    "steamAppId": 1172470,
    "platform": "steam"
  },
  {
    "id": "fortnite",
    "title": "Fortnite (Unreal Engine 5.4)",
    "genre": "Battle Royale / Sandbox",
    "coverImage": "https://images.unsplash.com/photo-1589241062272-c0a000072dfa?auto=format&fit=crop&w=600&q=80",
    "releaseYear": 2024,
    "description": "UE 5.4 Nanite ve Lumen teknolojisine geçen Fortnite, performans modunda yüksek FPS verirken Epik grafiklerde güçlü GPU ister.",
    "minCpuTier": 40,
    "recCpuTier": 74,
    "minGpuTier": 38,
    "recGpuTier": 72,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 50,
    "cpuWeight": 0.6,
    "gpuWeight": 0.4,
    "ramWeight": 0.15,
    "baseFps1080pLow": 210,
    "platform": "epic"
  },
  {
    "id": "pubg",
    "title": "PUBG: BATTLEGROUNDS",
    "genre": "Taktiksel Battle Royale",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/578080/header.jpg",
    "releaseYear": 2017,
    "description": "Geniş haritalarda render mesafesi ve RAM gecikmesine (RAM Timings) aşırı hassas, optimizasyon canavarı battle royale.",
    "minCpuTier": 50,
    "recCpuTier": 76,
    "minGpuTier": 46,
    "recGpuTier": 72,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 40,
    "cpuWeight": 0.6,
    "gpuWeight": 0.4,
    "ramWeight": 0.2,
    "baseFps1080pLow": 160,
    "steamAppId": 578080,
    "platform": "steam"
  },
  {
    "id": "r6siege",
    "title": "Tom Clancy's Rainbow Six Siege",
    "genre": "Taktiksel E-Spor Nişancı",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/359550/header.jpg",
    "releaseYear": 2015,
    "description": "Yıkılabilir çevre fizikleri ve Vulkan API desteğiyle optimize edilmiş, 240Hz/360Hz monitörlerde harika çalışan espor klasiği.",
    "minCpuTier": 35,
    "recCpuTier": 65,
    "minGpuTier": 35,
    "recGpuTier": 60,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 85,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.1,
    "baseFps1080pLow": 260,
    "steamAppId": 359550,
    "platform": "steam"
  },
  {
    "id": "overwatch2",
    "title": "Overwatch 2",
    "genre": "Hero Shooter / E-Spor",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2357570/header.jpg",
    "releaseYear": 2023,
    "description": "Blizzard'ın akıcı takım bazlı nişancı oyunu. Mükemmel optimizasyonu sayesinde orta segment kasalarda bile 200+ FPS verir.",
    "minCpuTier": 35,
    "recCpuTier": 62,
    "minGpuTier": 35,
    "recGpuTier": 58,
    "minRamGb": 6,
    "recRamGb": 16,
    "storageGb": 50,
    "cpuWeight": 0.55,
    "gpuWeight": 0.45,
    "ramWeight": 0.1,
    "baseFps1080pLow": 250,
    "steamAppId": 2357570,
    "platform": "steam"
  },
  {
    "id": "lol",
    "title": "League of Legends",
    "genre": "MOBA / E-Spor",
    "coverImage": "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=600&q=80",
    "releaseYear": 2009,
    "description": "Dünyanın en popüler rekabetçi MOBA oyunu. Hemen hemen her bilgisayarda çalışır, işlemci tek çekirdek performansına bakar.",
    "minCpuTier": 25,
    "recCpuTier": 50,
    "minGpuTier": 20,
    "recGpuTier": 40,
    "minRamGb": 4,
    "recRamGb": 8,
    "storageGb": 22,
    "cpuWeight": 0.85,
    "gpuWeight": 0.15,
    "ramWeight": 0.05,
    "baseFps1080pLow": 350,
    "platform": "riot"
  },
  {
    "id": "dota2",
    "title": "Dota 2",
    "genre": "MOBA / E-Spor",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/570/header.jpg",
    "releaseYear": 2013,
    "description": "Valve'ın Source 2 motorlu derin MOBA oyunu. Takım savaşlarında onlarca partikül efekti CPU yükünü artırır.",
    "minCpuTier": 35,
    "recCpuTier": 65,
    "minGpuTier": 30,
    "recGpuTier": 55,
    "minRamGb": 4,
    "recRamGb": 16,
    "storageGb": 60,
    "cpuWeight": 0.75,
    "gpuWeight": 0.25,
    "ramWeight": 0.1,
    "baseFps1080pLow": 240,
    "steamAppId": 570,
    "platform": "steam"
  },
  {
    "id": "wukong",
    "title": "Black Myth: Wukong",
    "genre": "Unreal Engine 5 Aksiyon / RPG",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2358720/header.jpg",
    "releaseYear": 2024,
    "description": "Unreal Engine 5 Lumen ve Nanite motorunu kullanan yeni nesil başyapıt. Ekran kartının shader birimlerini yoğun kullanır.",
    "minCpuTier": 65,
    "recCpuTier": 84,
    "minGpuTier": 65,
    "recGpuTier": 86,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 130,
    "cpuWeight": 0.4,
    "gpuWeight": 0.6,
    "ramWeight": 0.15,
    "baseFps1080pLow": 80,
    "steamAppId": 2358720,
    "platform": "steam"
  },
  {
    "id": "cyberpunk",
    "title": "Cyberpunk 2077: Phantom Liberty",
    "genre": "Açık Dünya / Ray Tracing RPG",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1091500/header.jpg",
    "releaseYear": 2023,
    "description": "Grafik teknolojisinin zirvesi. Path Tracing ve DLSS 3 testlerinin vazgeçilmez kıyaslama oyunu. Ekran kartını son damlasına kadar zorlar.",
    "minCpuTier": 60,
    "recCpuTier": 82,
    "minGpuTier": 60,
    "recGpuTier": 85,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 90,
    "cpuWeight": 0.35,
    "gpuWeight": 0.65,
    "ramWeight": 0.15,
    "baseFps1080pLow": 85,
    "steamAppId": 1091500,
    "platform": "steam"
  },
  {
    "id": "gta6",
    "title": "Grand Theft Auto VI",
    "genre": "Açık Dünya / Yeni Nesil Aksiyon",
    "coverImage": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80",
    "releaseYear": 2025,
    "description": "Rockstar Games'in yeni nesil RAGE motoru. Yoğun NPC yapay zekası, gelişmiş ışın izleme ve devasa harita nedeniyle hem güçlü CPU hem 12GB+ GPU VRAM isteyecek.",
    "minCpuTier": 70,
    "recCpuTier": 88,
    "minGpuTier": 68,
    "recGpuTier": 86,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 150,
    "cpuWeight": 0.45,
    "gpuWeight": 0.55,
    "ramWeight": 0.2,
    "baseFps1080pLow": 75,
    "platform": "all"
  },
  {
    "id": "gta5",
    "title": "Grand Theft Auto V",
    "genre": "Açık Dünya / Aksiyon",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/271590/header.jpg",
    "releaseYear": 2015,
    "description": "Tarihin en çok satan açık dünya oyunu ve FiveM RP modları. Geniş araba filoları ve sunucu modları için 16GB+ RAM gereklidir.",
    "minCpuTier": 35,
    "recCpuTier": 60,
    "minGpuTier": 35,
    "recGpuTier": 55,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 110,
    "cpuWeight": 0.55,
    "gpuWeight": 0.45,
    "ramWeight": 0.15,
    "baseFps1080pLow": 170,
    "steamAppId": 271590,
    "platform": "steam"
  },
  {
    "id": "rdr2",
    "title": "Red Dead Redemption 2",
    "genre": "Açık Dünya / Western Başyapıt",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1174180/header.jpg",
    "releaseYear": 2019,
    "description": "Rockstar'ın muazzam detay seviyesine ve volumetrik ışıklandırmaya sahip şaheseri. Ultra ayarlarda güçlü GPU ve çift kanal RAM ister.",
    "minCpuTier": 50,
    "recCpuTier": 75,
    "minGpuTier": 50,
    "recGpuTier": 76,
    "minRamGb": 12,
    "recRamGb": 16,
    "storageGb": 150,
    "cpuWeight": 0.4,
    "gpuWeight": 0.6,
    "ramWeight": 0.15,
    "baseFps1080pLow": 105,
    "steamAppId": 1174180,
    "platform": "steam"
  },
  {
    "id": "eafc25",
    "title": "EA SPORTS FC™ 25",
    "genre": "Futbol Simülasyonu / Spor",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2669320/header.jpg",
    "releaseYear": 2024,
    "description": "HyperMotionV teknolojisi ve FC IQ taktik motoru ile EA'in en son futbol oyunu. 144Hz akıcı maç deneyimi için dengeli ekran kartı ister.",
    "minCpuTier": 50,
    "recCpuTier": 75,
    "minGpuTier": 48,
    "recGpuTier": 72,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 100,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.1,
    "baseFps1080pLow": 145,
    "steamAppId": 2669320,
    "platform": "steam"
  },
  {
    "id": "bg3",
    "title": "Baldur's Gate 3",
    "genre": "Sıra Tabanlı RPG Başyapıt",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1086940/header.jpg",
    "releaseYear": 2023,
    "description": "Yılın Oyunu ödüllü D&D şaheseri. 3. Bölüm şehir sokaklarındaki binlerce NPC nedeniyle güçlü çok çekirdekli işlemci ister.",
    "minCpuTier": 55,
    "recCpuTier": 80,
    "minGpuTier": 52,
    "recGpuTier": 76,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 150,
    "cpuWeight": 0.55,
    "gpuWeight": 0.45,
    "ramWeight": 0.15,
    "baseFps1080pLow": 110,
    "steamAppId": 1086940,
    "platform": "steam"
  },
  {
    "id": "eldenring",
    "title": "Elden Ring: Shadow of the Erdtree",
    "genre": "Açık Dünya Soulsborne",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/header.jpg",
    "releaseYear": 2024,
    "description": "FromSoftware'in efsanevi açık dünya aksiyon RPG'si. 60 FPS kilitli motorunda ani FPS düşüşü yaşamamak için sağlam CPU ve RAM ister.",
    "minCpuTier": 55,
    "recCpuTier": 78,
    "minGpuTier": 52,
    "recGpuTier": 74,
    "minRamGb": 12,
    "recRamGb": 16,
    "storageGb": 80,
    "cpuWeight": 0.45,
    "gpuWeight": 0.55,
    "ramWeight": 0.15,
    "baseFps1080pLow": 115,
    "steamAppId": 1245620,
    "platform": "steam"
  },
  {
    "id": "forza5",
    "title": "Forza Horizon 5",
    "genre": "Açık Dünya Yarış",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1551360/header.jpg",
    "releaseYear": 2021,
    "description": "Meksika'nın eşsiz coğrafyasında harika grafikler sunan yarış klasiği. Optimizasyonu çok iyi olup yüksek çözünürlükte VRAM sever.",
    "minCpuTier": 45,
    "recCpuTier": 74,
    "minGpuTier": 46,
    "recGpuTier": 74,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 110,
    "cpuWeight": 0.4,
    "gpuWeight": 0.6,
    "ramWeight": 0.15,
    "baseFps1080pLow": 130,
    "steamAppId": 1551360,
    "platform": "steam"
  },
  {
    "id": "helldivers2",
    "title": "Helldivers 2",
    "genre": "Kooperatif PvE Nişancı",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/553850/header.jpg",
    "releaseYear": 2024,
    "description": "Böcek orduları, patlama fizikleri ve yoğun düşman akınları nedeniyle CPU yükü tavan yapan süper eğlenceli kooperatif nişancı.",
    "minCpuTier": 60,
    "recCpuTier": 82,
    "minGpuTier": 58,
    "recGpuTier": 78,
    "minRamGb": 16,
    "recRamGb": 16,
    "storageGb": 100,
    "cpuWeight": 0.6,
    "gpuWeight": 0.4,
    "ramWeight": 0.15,
    "baseFps1080pLow": 95,
    "steamAppId": 553850,
    "platform": "steam"
  },
  {
    "id": "gow_ragnarok",
    "title": "God of War Ragnarök",
    "genre": "Sinematik Aksiyon / Macera",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2322010/header.jpg",
    "releaseYear": 2024,
    "description": "Kratos ve Atreus'un İskandinav destanı. PC sürümünde 6GB+ VRAM zorunluluğu ve gelişmiş ölçeklendirme (FSR/DLSS) desteği bulunur.",
    "minCpuTier": 55,
    "recCpuTier": 78,
    "minGpuTier": 55,
    "recGpuTier": 78,
    "minRamGb": 16,
    "recRamGb": 16,
    "storageGb": 190,
    "cpuWeight": 0.45,
    "gpuWeight": 0.55,
    "ramWeight": 0.15,
    "baseFps1080pLow": 95,
    "steamAppId": 2322010,
    "platform": "steam"
  },
  {
    "id": "stalker2",
    "title": "S.T.A.L.K.E.R. 2: Heart of Chornobyl",
    "genre": "Unreal Engine 5 Kıyamet Sonrası Hayatta Kalma",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1643320/header.jpg",
    "releaseYear": 2024,
    "description": "Çernobil Bölgesi'nde UE5 Nanite ve Lumen teknolojisiyle donatılmış, ağır donanım ve 32GB RAM isteyen yeni nesil hayatta kalma FPS.",
    "minCpuTier": 68,
    "recCpuTier": 86,
    "minGpuTier": 65,
    "recGpuTier": 85,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 160,
    "cpuWeight": 0.45,
    "gpuWeight": 0.55,
    "ramWeight": 0.2,
    "baseFps1080pLow": 75,
    "steamAppId": 1643320,
    "platform": "steam"
  },
  {
    "id": "silenthill2",
    "title": "Silent Hill 2 Remake",
    "genre": "Unreal Engine 5 Psikolojik Korku",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2124490/header.jpg",
    "releaseYear": 2024,
    "description": "Bloober Team tarafından UE5 ile baştan yaratılan sisli korku klasiği. Yoğun volumetrik sis ve ışın izleme için güçlü GPU şarttır.",
    "minCpuTier": 62,
    "recCpuTier": 82,
    "minGpuTier": 62,
    "recGpuTier": 82,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 50,
    "cpuWeight": 0.4,
    "gpuWeight": 0.6,
    "ramWeight": 0.15,
    "baseFps1080pLow": 80,
    "steamAppId": 2124490,
    "platform": "steam"
  },
  {
    "id": "mhw_wilds",
    "title": "Monster Hunter Wilds",
    "genre": "Yeni Nesil Avcılık / Açık Dünya",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2246340/header.jpg",
    "releaseYear": 2025,
    "description": "Capcom'un RE Engine motoruyla devasa ekosistemleri canlandırdığı yeni nesil avcılık oyunu. Çoklu canavar kapışmalarında güçlü CPU ister.",
    "minCpuTier": 68,
    "recCpuTier": 86,
    "minGpuTier": 65,
    "recGpuTier": 84,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 140,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.2,
    "baseFps1080pLow": 80,
    "steamAppId": 2246340,
    "platform": "steam"
  },
  {
    "id": "starfield",
    "title": "Starfield",
    "genre": "Uzay RPG / Açık Dünya",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1716740/header.jpg",
    "releaseYear": 2023,
    "description": "Bethesda'nın Creation Engine 2 motorlu uzay macerası. Şehir merkezlerinde CPU'yu, açık gezegenlerde GPU ve hızlı SSD'yi zorlar.",
    "minCpuTier": 65,
    "recCpuTier": 84,
    "minGpuTier": 62,
    "recGpuTier": 82,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 125,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.2,
    "baseFps1080pLow": 85,
    "steamAppId": 1716740,
    "platform": "steam"
  },
  {
    "id": "hogwarts",
    "title": "Hogwarts Legacy",
    "genre": "Açık Dünya Büyücülük RPG",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/990080/header.jpg",
    "releaseYear": 2023,
    "description": "Hogwarts şatosu ve çevre köylerde devasa açık dünya. 16GB RAM'de takılmalar olabileceğinden 32GB RAM ve 8GB+ VRAM tavsiye edilir.",
    "minCpuTier": 55,
    "recCpuTier": 78,
    "minGpuTier": 52,
    "recGpuTier": 76,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 85,
    "cpuWeight": 0.45,
    "gpuWeight": 0.55,
    "ramWeight": 0.2,
    "baseFps1080pLow": 95,
    "steamAppId": 990080,
    "platform": "steam"
  },
  {
    "id": "witcher3",
    "title": "The Witcher 3: Wild Hunt (Next-Gen)",
    "genre": "Açık Dünya RPG Başyapıt",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/292030/header.jpg",
    "releaseYear": 2022,
    "description": "Next-Gen güncellemesiyle Ray Tracing ve DLSS/FSR eklenen Geralt'ın efsanevi macerası. Klasik modda çok akıcı, RT modda ağırdır.",
    "minCpuTier": 45,
    "recCpuTier": 74,
    "minGpuTier": 45,
    "recGpuTier": 74,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 60,
    "cpuWeight": 0.45,
    "gpuWeight": 0.55,
    "ramWeight": 0.15,
    "baseFps1080pLow": 125,
    "steamAppId": 292030,
    "platform": "steam"
  },
  {
    "id": "re4_remake",
    "title": "Resident Evil 4 Remake",
    "genre": "Hayatta Kalma Korku / Aksiyon",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2050650/header.jpg",
    "releaseYear": 2023,
    "description": "Capcom RE Engine harikası. Kusursuz optimizasyona sahip olup VRAM kullanımını doğru ayarladığında yüksek FPS garantidir.",
    "minCpuTier": 52,
    "recCpuTier": 74,
    "minGpuTier": 50,
    "recGpuTier": 74,
    "minRamGb": 16,
    "recRamGb": 16,
    "storageGb": 65,
    "cpuWeight": 0.4,
    "gpuWeight": 0.6,
    "ramWeight": 0.15,
    "baseFps1080pLow": 115,
    "steamAppId": 2050650,
    "platform": "steam"
  },
  {
    "id": "spiderman",
    "title": "Marvel's Spider-Man Remastered",
    "genre": "Açık Dünya Süper Kahraman",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1817070/header.jpg",
    "releaseYear": 2022,
    "description": "Manhattan gökdelenleri arasında ağ atarken yüksek hızda asset yüklemesi için güçlü CPU ve hızlı NVMe SSD gerektirir.",
    "minCpuTier": 50,
    "recCpuTier": 76,
    "minGpuTier": 48,
    "recGpuTier": 74,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 75,
    "cpuWeight": 0.55,
    "gpuWeight": 0.45,
    "ramWeight": 0.15,
    "baseFps1080pLow": 120,
    "steamAppId": 1817070,
    "platform": "steam"
  },
  {
    "id": "ac_mirage",
    "title": "Assassin's Creed Mirage",
    "genre": "Tarihsel Gizlilik / Aksiyon",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2842100/header.jpg",
    "releaseYear": 2023,
    "description": "9. yüzyıl Bağdat sokaklarında geçen klasik Assassin hissiyatı. Anvil motoru kalabalık şehirlerde dengeli CPU ve GPU ister.",
    "minCpuTier": 50,
    "recCpuTier": 74,
    "minGpuTier": 48,
    "recGpuTier": 72,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 40,
    "cpuWeight": 0.45,
    "gpuWeight": 0.55,
    "ramWeight": 0.15,
    "baseFps1080pLow": 110,
    "steamAppId": 2842100,
    "platform": "steam"
  },
  {
    "id": "alanwake2",
    "title": "Alan Wake 2",
    "genre": "Hayatta Kalma Korku / Mesh Shader Devi",
    "coverImage": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80",
    "releaseYear": 2023,
    "description": "Mesh Shaders ve Full Path Tracing kullanan teknoloji demosu ayarında başyapıt. En az RTX 2060 / RX 6600 gerektirir.",
    "minCpuTier": 65,
    "recCpuTier": 85,
    "minGpuTier": 65,
    "recGpuTier": 88,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 90,
    "cpuWeight": 0.35,
    "gpuWeight": 0.65,
    "ramWeight": 0.2,
    "baseFps1080pLow": 70,
    "platform": "epic"
  },
  {
    "id": "tlou1",
    "title": "The Last of Us Part I",
    "genre": "Sinematik Hayatta Kalma / Aksiyon",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1888930/header.jpg",
    "releaseYear": 2023,
    "description": "Naughty Dog'un duygu yüklü klasiği. Shader derleme süreci ve yoğun dokular nedeniyle en az 8GB VRAM ve güçlü CPU ister.",
    "minCpuTier": 62,
    "recCpuTier": 82,
    "minGpuTier": 60,
    "recGpuTier": 80,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 100,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.2,
    "baseFps1080pLow": 85,
    "steamAppId": 1888930,
    "platform": "steam"
  },
  {
    "id": "rust",
    "title": "Rust",
    "genre": "Çok Oyunculu Hayatta Kalma",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/252490/header.jpg",
    "releaseYear": 2018,
    "description": "Unity motorunun en ağır hayatta kalma oyunu. Yüz binlerce base parçası ve oyuncu nedeniyle 16GB değil 32GB RAM ve hızlı CPU şarttır.",
    "minCpuTier": 55,
    "recCpuTier": 80,
    "minGpuTier": 50,
    "recGpuTier": 76,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 25,
    "cpuWeight": 0.65,
    "gpuWeight": 0.35,
    "ramWeight": 0.3,
    "baseFps1080pLow": 110,
    "steamAppId": 252490,
    "platform": "steam"
  },
  {
    "id": "tarkov",
    "title": "Escape from Tarkov",
    "genre": "Gerçekçi Taktiksel Extraction Shooter",
    "coverImage": "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=600&q=80",
    "releaseYear": 2024,
    "description": "L3 Cache boyutuna (özellikle Ryzen 7800X3D/5800X3D) ve 32GB RAM'e aşırı muhtaç, Streets of Tarkov gibi ağır haritalara sahip taktik FPS.",
    "minCpuTier": 70,
    "recCpuTier": 92,
    "minGpuTier": 60,
    "recGpuTier": 80,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 40,
    "cpuWeight": 0.75,
    "gpuWeight": 0.25,
    "ramWeight": 0.35,
    "baseFps1080pLow": 90,
    "platform": "all"
  },
  {
    "id": "palworld",
    "title": "Palworld",
    "genre": "Açık Dünya Yaratık Toplama / Hayatta Kalma",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1623730/header.jpg",
    "releaseYear": 2024,
    "description": "Unreal Engine 5 ile rekorlar kıran hayatta kalma oyunu. Kalabalık üslerde otomasyon çalışırken CPU ve RAM tüketimi artar.",
    "minCpuTier": 55,
    "recCpuTier": 78,
    "minGpuTier": 52,
    "recGpuTier": 76,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 40,
    "cpuWeight": 0.55,
    "gpuWeight": 0.45,
    "ramWeight": 0.2,
    "baseFps1080pLow": 115,
    "steamAppId": 1623730,
    "platform": "steam"
  },
  {
    "id": "ark_ascended",
    "title": "ARK: Survival Ascended",
    "genre": "Unreal Engine 5 Dinozor Hayatta Kalma",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2399830/header.jpg",
    "releaseYear": 2023,
    "description": "UE5 Nanite ormanları ve dev dinozorlar. Piyasanın en ağır sistem isteyen oyunlarından biridir; güçlü RTX GPU ve 32GB RAM ister.",
    "minCpuTier": 65,
    "recCpuTier": 86,
    "minGpuTier": 68,
    "recGpuTier": 88,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 85,
    "cpuWeight": 0.45,
    "gpuWeight": 0.55,
    "ramWeight": 0.25,
    "baseFps1080pLow": 65,
    "steamAppId": 2399830,
    "platform": "steam"
  },
  {
    "id": "sons_forest",
    "title": "Sons of the Forest",
    "genre": "Ada Hayatta Kalma Korku",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1326470/header.jpg",
    "releaseYear": 2024,
    "description": "Yamyamlarla dolu adada dinamik mevsimler ve ağaç kesme fizikleri. Çok oyunculu modda dengeli sistem ile çok zevklidir.",
    "minCpuTier": 55,
    "recCpuTier": 76,
    "minGpuTier": 52,
    "recGpuTier": 74,
    "minRamGb": 12,
    "recRamGb": 16,
    "storageGb": 20,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.15,
    "baseFps1080pLow": 110,
    "steamAppId": 1326470,
    "platform": "steam"
  },
  {
    "id": "ets2",
    "title": "Euro Truck Simulator 2",
    "genre": "Kamyon / Yol Simülasyonu",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/227300/header.jpg",
    "releaseYear": 2012,
    "description": "Türkiye haritası ve ProMods ile saatlerce oynanan TIR simülasyonu klasiği. Şehir merkezlerinde ve yağmurda CPU tek çekirdeğe yüklenir.",
    "minCpuTier": 35,
    "recCpuTier": 62,
    "minGpuTier": 35,
    "recGpuTier": 60,
    "minRamGb": 6,
    "recRamGb": 16,
    "storageGb": 25,
    "cpuWeight": 0.65,
    "gpuWeight": 0.35,
    "ramWeight": 0.1,
    "baseFps1080pLow": 170,
    "steamAppId": 227300,
    "platform": "steam"
  },
  {
    "id": "farm_sim25",
    "title": "Farming Simulator 25",
    "genre": "Çiftçilik & Arazi Simülasyonu",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2300320/header.jpg",
    "releaseYear": 2024,
    "description": "Yeni nesil zemin deformasyonu, çeltik tarlaları ve gelişmiş traktör fizikleri sunan en popüler çiftlik simülasyonu.",
    "minCpuTier": 50,
    "recCpuTier": 74,
    "minGpuTier": 48,
    "recGpuTier": 72,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 45,
    "cpuWeight": 0.55,
    "gpuWeight": 0.45,
    "ramWeight": 0.15,
    "baseFps1080pLow": 120,
    "steamAppId": 2300320,
    "platform": "steam"
  },
  {
    "id": "msfs2024",
    "title": "Microsoft Flight Simulator 2024",
    "genre": "Tüm Dünya Uçuş Simülasyonu",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2537590/header.jpg",
    "releaseYear": 2024,
    "description": "Dünyanın tamamını 1:1 ölçekte buluttan aktaran teknoloji harikası. İdeal deneyim için 32GB+ RAM ve yüksek hızlı internet/SSD şarttır.",
    "minCpuTier": 70,
    "recCpuTier": 92,
    "minGpuTier": 68,
    "recGpuTier": 88,
    "minRamGb": 16,
    "recRamGb": 64,
    "storageGb": 50,
    "cpuWeight": 0.65,
    "gpuWeight": 0.35,
    "ramWeight": 0.35,
    "baseFps1080pLow": 65,
    "steamAppId": 2537590,
    "platform": "steam"
  },
  {
    "id": "bannerlord",
    "title": "Mount & Blade II: Bannerlord",
    "genre": "Orta Çağ Savaş / Strateji Simülatörü",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/261550/header.jpg",
    "releaseYear": 2020,
    "description": "TaleWorlds'ün Türk yapımı dünya devi. 1000 kişilik meydan savaşlarında atlı ve okçu yapay zekası işlemciyi sonuna kadar terletir.",
    "minCpuTier": 55,
    "recCpuTier": 82,
    "minGpuTier": 46,
    "recGpuTier": 72,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 60,
    "cpuWeight": 0.7,
    "gpuWeight": 0.3,
    "ramWeight": 0.15,
    "baseFps1080pLow": 140,
    "steamAppId": 261550,
    "platform": "steam"
  },
  {
    "id": "manorlords",
    "title": "Manor Lords",
    "genre": "Orta Çağ Şehir Kurma & Taktik Savaş",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1363080/header.jpg",
    "releaseYear": 2024,
    "description": "Unreal Engine motoruyla tarihi doğruluğa sahip şehir kurma fenomeni. Büyüyen köylerde vatandaş lojistiği işlemci gücüne bakar.",
    "minCpuTier": 50,
    "recCpuTier": 74,
    "minGpuTier": 46,
    "recGpuTier": 70,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 16,
    "cpuWeight": 0.6,
    "gpuWeight": 0.4,
    "ramWeight": 0.15,
    "baseFps1080pLow": 130,
    "steamAppId": 1363080,
    "platform": "steam"
  },
  {
    "id": "deadbydaylight",
    "title": "Dead by Daylight",
    "genre": "4v1 Asimetrik Korku",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/381210/header.jpg",
    "releaseYear": 2016,
    "description": "Katil ve 4 kurbanın gerilimli mücadelesi. Unreal Engine motorunda orta düzey bilgisayarlarda bile akıcı 60-120 FPS verir.",
    "minCpuTier": 40,
    "recCpuTier": 64,
    "minGpuTier": 40,
    "recGpuTier": 62,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 50,
    "cpuWeight": 0.45,
    "gpuWeight": 0.55,
    "ramWeight": 0.1,
    "baseFps1080pLow": 160,
    "steamAppId": 381210,
    "platform": "steam"
  },
  {
    "id": "rocketleague",
    "title": "Rocket League",
    "genre": "Fizik Tabanlı Araba Futbolu",
    "coverImage": "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=600&q=80",
    "releaseYear": 2015,
    "description": "Roket motorlu arabalarla futbol heyecanı. Çok iyi optimize edilmiştir, 240Hz+ espor monitörlerinde kaymak gibi akar.",
    "minCpuTier": 30,
    "recCpuTier": 55,
    "minGpuTier": 30,
    "recGpuTier": 50,
    "minRamGb": 4,
    "recRamGb": 8,
    "storageGb": 20,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.05,
    "baseFps1080pLow": 300,
    "platform": "epic"
  },
  {
    "id": "warthunder",
    "title": "War Thunder",
    "genre": "Askeri Araç & Hava Savaşları",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/236390/header.jpg",
    "releaseYear": 2013,
    "description": "Tank, uçak ve gemilerle gerçekçi askeri simülasyon. Dagor Engine motoru modern donanımlarda inanılmaz yüksek FPS verir.",
    "minCpuTier": 35,
    "recCpuTier": 65,
    "minGpuTier": 35,
    "recGpuTier": 62,
    "minRamGb": 4,
    "recRamGb": 16,
    "storageGb": 95,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.1,
    "baseFps1080pLow": 220,
    "steamAppId": 236390,
    "platform": "steam"
  },
  {
    "id": "destiny2",
    "title": "Destiny 2",
    "genre": "Çok Oyunculu Bilim Kurgu Looter Shooter",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1085660/header.jpg",
    "releaseYear": 2019,
    "description": "Bungie'nin güneş sistemi boyunca uzanan uzay operası. Raid etkinliklerinde partikül efektleri için iyi bir ekran kartı ister.",
    "minCpuTier": 45,
    "recCpuTier": 70,
    "minGpuTier": 45,
    "recGpuTier": 68,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 105,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.15,
    "baseFps1080pLow": 175,
    "steamAppId": 1085660,
    "platform": "steam"
  },
  {
    "id": "diablo4",
    "title": "Diablo IV",
    "genre": "Karanlık İzometrik ARPG",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2344520/header.jpg",
    "releaseYear": 2023,
    "description": "Sığınak dünyasında iblis biçme şöleni. Ultra dokularda VRAM tüketimi artar, DLSS/FSR ile tüm modern kasalarda harika çalışır.",
    "minCpuTier": 48,
    "recCpuTier": 72,
    "minGpuTier": 48,
    "recGpuTier": 72,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 90,
    "cpuWeight": 0.45,
    "gpuWeight": 0.55,
    "ramWeight": 0.15,
    "baseFps1080pLow": 145,
    "steamAppId": 2344520,
    "platform": "steam"
  },
  {
    "id": "tf2",
    "title": "Team Fortress 2",
    "genre": "Klasik Çizgi E-Spor FPS",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/440/header.jpg",
    "releaseYear": 2007,
    "description": "Valve'ın efsanevi 9 sınıflı nişancı klasiği. Neredeyse tost makinesinde bile 100+ FPS çalışacak kadar hafiftir.",
    "minCpuTier": 20,
    "recCpuTier": 40,
    "minGpuTier": 20,
    "recGpuTier": 35,
    "minRamGb": 2,
    "recRamGb": 8,
    "storageGb": 15,
    "cpuWeight": 0.8,
    "gpuWeight": 0.2,
    "ramWeight": 0.05,
    "baseFps1080pLow": 350,
    "steamAppId": 440,
    "platform": "steam"
  }
];
