import { GameRequirement } from "./types";

export const GAMES: GameRequirement[] = [
  {
    "id": "cs2",
    "title": "Counter-Strike 2",
    "genre": "Rekabetçi E-Spor FPS",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/header.jpg",
    "releaseYear": 2023,
    "description": "Valve'ın Source 2 motorlu rekabetçi FPS devi. İşlemci önbelleğine (L3 Cache) ve tek çekirdek performansına aşırı duyarlıdır.",
    "minCpuTier": 45,
    "recCpuTier": 75,
    "minGpuTier": 40,
    "recGpuTier": 68,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 85,
    "cpuWeight": 0.65,
    "gpuWeight": 0.35,
    "ramWeight": 0.1,
    "baseFps1080pLow": 240,
    "steamAppId": 730,
    "platform": "steam"
  },
  {
    "id": "valorant",
    "title": "Valorant",
    "genre": "Taktiksel E-Spor Nişancı",
    "coverImage": "/games/valorant.jpg",
    "releaseYear": 2020,
    "description": "Riot Games'in taktiksel nişancı oyunu. Neredeyse tamamen işlemciye bakar, iyi bir CPU ile 300+ FPS görmek çok kolaydır.",
    "minCpuTier": 35,
    "recCpuTier": 65,
    "minGpuTier": 30,
    "recGpuTier": 50,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 45,
    "cpuWeight": 0.8,
    "gpuWeight": 0.2,
    "ramWeight": 0.05,
    "baseFps1080pLow": 320,
    "platform": "riot"
  },
  {
    "id": "warzone",
    "title": "Call of Duty: Warzone & MW3",
    "genre": "Battle Royale / E-Spor",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1938090/header.jpg",
    "releaseYear": 2024,
    "description": "Aşırı RAM ve VRAM tüketen, optimizasyon gerektiren devasa haritalı savaş oyunu. 16GB RAM yetersiz kalabilmektedir.",
    "minCpuTier": 60,
    "recCpuTier": 82,
    "minGpuTier": 62,
    "recGpuTier": 82,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 125,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.25,
    "baseFps1080pLow": 110,
    "steamAppId": 1938090,
    "platform": "steam"
  },
  {
    "id": "apex",
    "title": "Apex Legends",
    "genre": "Battle Royale / Hızlı FPS",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1172470/header.jpg",
    "releaseYear": 2020,
    "description": "Respawn Entertainment'ın akıcı hareket mekaniklerine sahip battle royale oyunu. Yüksek FPS ve stabil 144Hz+ için dengeli donanım ister.",
    "minCpuTier": 45,
    "recCpuTier": 72,
    "minGpuTier": 45,
    "recGpuTier": 70,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 75,
    "cpuWeight": 0.55,
    "gpuWeight": 0.45,
    "ramWeight": 0.15,
    "baseFps1080pLow": 190,
    "steamAppId": 1172470,
    "platform": "steam"
  },
  {
    "id": "fortnite",
    "title": "Fortnite (Unreal Engine 5.4)",
    "genre": "Battle Royale / Sandbox",
    "coverImage": "/games/fortnite.jpg",
    "releaseYear": 2024,
    "description": "UE 5.4 Nanite ve Lumen teknolojisine geçen Fortnite, performans modunda yüksek FPS verirken Epik grafiklerde güçlü GPU ister.",
    "minCpuTier": 40,
    "recCpuTier": 74,
    "minGpuTier": 38,
    "recGpuTier": 72,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 50,
    "cpuWeight": 0.6,
    "gpuWeight": 0.4,
    "ramWeight": 0.15,
    "baseFps1080pLow": 210,
    "platform": "epic"
  },
  {
    "id": "pubg",
    "title": "PUBG: BATTLEGROUNDS",
    "genre": "Taktiksel Battle Royale",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/578080/header.jpg",
    "releaseYear": 2017,
    "description": "Geniş haritalarda render mesafesi ve RAM gecikmesine (RAM Timings) aşırı hassas, optimizasyon canavarı battle royale.",
    "minCpuTier": 50,
    "recCpuTier": 76,
    "minGpuTier": 46,
    "recGpuTier": 72,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 40,
    "cpuWeight": 0.6,
    "gpuWeight": 0.4,
    "ramWeight": 0.2,
    "baseFps1080pLow": 160,
    "steamAppId": 578080,
    "platform": "steam"
  },
  {
    "id": "r6siege",
    "title": "Tom Clancy's Rainbow Six Siege",
    "genre": "Taktiksel E-Spor Nişancı",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/359550/header.jpg",
    "releaseYear": 2015,
    "description": "Yıkılabilir çevre fizikleri ve Vulkan API desteğiyle optimize edilmiş, 240Hz/360Hz monitörlerde harika çalışan espor klasiği.",
    "minCpuTier": 35,
    "recCpuTier": 65,
    "minGpuTier": 35,
    "recGpuTier": 60,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 85,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.1,
    "baseFps1080pLow": 260,
    "steamAppId": 359550,
    "platform": "steam"
  },
  {
    "id": "overwatch2",
    "title": "Overwatch 2",
    "genre": "Hero Shooter / E-Spor",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2357570/header.jpg",
    "releaseYear": 2023,
    "description": "Blizzard'ın akıcı takım bazlı nişancı oyunu. Mükemmel optimizasyonu sayesinde orta segment kasalarda bile 200+ FPS verir.",
    "minCpuTier": 35,
    "recCpuTier": 62,
    "minGpuTier": 35,
    "recGpuTier": 58,
    "minRamGb": 6,
    "recRamGb": 16,
    "storageGb": 50,
    "cpuWeight": 0.55,
    "gpuWeight": 0.45,
    "ramWeight": 0.1,
    "baseFps1080pLow": 250,
    "steamAppId": 2357570,
    "platform": "steam"
  },
  {
    "id": "thefinals",
    "title": "THE FINALS",
    "genre": "Yıkım Fiziği / Hızlı FPS",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2073850/header.jpg",
    "releaseYear": 2023,
    "description": "Sunucu ve istemci taraflı gerçek zamanlı bina yıkım fizikleri sunan dinamik arena FPS. İşlemci çok çekirdeğine yüklenir.",
    "minCpuTier": 55,
    "recCpuTier": 78,
    "minGpuTier": 52,
    "recGpuTier": 76,
    "minRamGb": 12,
    "recRamGb": 16,
    "storageGb": 20,
    "cpuWeight": 0.55,
    "gpuWeight": 0.45,
    "ramWeight": 0.15,
    "baseFps1080pLow": 135,
    "steamAppId": 2073850,
    "platform": "steam"
  },
  {
    "id": "lol",
    "title": "League of Legends",
    "genre": "MOBA / E-Spor",
    "coverImage": "/games/lol.jpg",
    "releaseYear": 2009,
    "description": "Dünyanın en popüler rekabetçi MOBA oyunu. Hemen hemen her bilgisayarda çalışır, işlemci tek çekirdek performansına bakar.",
    "minCpuTier": 25,
    "recCpuTier": 50,
    "minGpuTier": 20,
    "recGpuTier": 40,
    "minRamGb": 4,
    "recRamGb": 8,
    "storageGb": 22,
    "cpuWeight": 0.85,
    "gpuWeight": 0.15,
    "ramWeight": 0.05,
    "baseFps1080pLow": 350,
    "platform": "riot"
  },
  {
    "id": "dota2",
    "title": "Dota 2",
    "genre": "MOBA / E-Spor",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/570/header.jpg",
    "releaseYear": 2013,
    "description": "Valve'ın Source 2 motorlu derin MOBA oyunu. Takım savaşlarında onlarca partikül efekti CPU yükünü artırır.",
    "minCpuTier": 35,
    "recCpuTier": 65,
    "minGpuTier": 30,
    "recGpuTier": 55,
    "minRamGb": 4,
    "recRamGb": 16,
    "storageGb": 60,
    "cpuWeight": 0.75,
    "gpuWeight": 0.25,
    "ramWeight": 0.1,
    "baseFps1080pLow": 240,
    "steamAppId": 570,
    "platform": "steam"
  },
  {
    "id": "rocketleague",
    "title": "Rocket League",
    "genre": "Fizik Tabanlı Araba Futbolu",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/252950/header.jpg",
    "releaseYear": 2015,
    "description": "Roket motorlu arabalarla futbol heyecanı. Çok iyi optimize edilmiştir, 240Hz+ espor monitörlerinde kaymak gibi akar.",
    "minCpuTier": 30,
    "recCpuTier": 55,
    "minGpuTier": 30,
    "recGpuTier": 50,
    "minRamGb": 4,
    "recRamGb": 8,
    "storageGb": 20,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.05,
    "baseFps1080pLow": 300,
    "steamAppId": 252950,
    "platform": "epic"
  },
  {
    "id": "brawlhalla",
    "title": "Brawlhalla",
    "genre": "2D Platform Dövüş / E-Spor",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/291550/header.jpg",
    "releaseYear": 2017,
    "description": "Ücretsiz 2D Smash Bros tarzı platform dövüş oyunu. En düşük donanımlı dizüstü bilgisayarlarda bile tam hızda çalışır.",
    "minCpuTier": 20,
    "recCpuTier": 35,
    "minGpuTier": 15,
    "recGpuTier": 30,
    "minRamGb": 2,
    "recRamGb": 4,
    "storageGb": 2,
    "cpuWeight": 0.6,
    "gpuWeight": 0.4,
    "ramWeight": 0.05,
    "baseFps1080pLow": 350,
    "steamAppId": 291550,
    "platform": "steam"
  },
  {
    "id": "fallguys",
    "title": "Fall Guys",
    "genre": "Parti / Engel Parkuru Battle Royale",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1097150/header.jpg",
    "releaseYear": 2020,
    "description": "60 kişinin çılgın engelli parkurlarda yarıştığı renkli ve eğlenceli parti oyunu.",
    "minCpuTier": 35,
    "recCpuTier": 60,
    "minGpuTier": 35,
    "recGpuTier": 55,
    "minRamGb": 8,
    "recRamGb": 8,
    "storageGb": 8,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.1,
    "baseFps1080pLow": 180,
    "steamAppId": 1097150,
    "platform": "epic"
  },
  {
    "id": "tf2",
    "title": "Team Fortress 2",
    "genre": "Klasik Çizgi E-Spor FPS",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/440/header.jpg",
    "releaseYear": 2007,
    "description": "Valve'ın efsanevi 9 sınıflı nişancı klasiği. Neredeyse tost makinesinde bile 100+ FPS çalışacak kadar hafiftir.",
    "minCpuTier": 20,
    "recCpuTier": 40,
    "minGpuTier": 20,
    "recGpuTier": 35,
    "minRamGb": 2,
    "recRamGb": 8,
    "storageGb": 15,
    "cpuWeight": 0.8,
    "gpuWeight": 0.2,
    "ramWeight": 0.05,
    "baseFps1080pLow": 350,
    "steamAppId": 440,
    "platform": "steam"
  },
  {
    "id": "warthunder",
    "title": "War Thunder",
    "genre": "Askeri Araç & Hava Savaşları",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/236390/header.jpg",
    "releaseYear": 2013,
    "description": "Tank, uçak ve gemilerle gerçekçi askeri simülasyon. Dagor Engine motoru modern donanımlarda inanılmaz yüksek FPS verir.",
    "minCpuTier": 35,
    "recCpuTier": 65,
    "minGpuTier": 35,
    "recGpuTier": 62,
    "minRamGb": 4,
    "recRamGb": 16,
    "storageGb": 95,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.1,
    "baseFps1080pLow": 220,
    "steamAppId": 236390,
    "platform": "steam"
  },
  {
    "id": "destiny2",
    "title": "Destiny 2",
    "genre": "Çok Oyunculu Bilim Kurgu Looter Shooter",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1085660/header.jpg",
    "releaseYear": 2019,
    "description": "Bungie'nin güneş sistemi boyunca uzanan uzay operası. Raid etkinliklerinde partikül efektleri için iyi bir ekran kartı ister.",
    "minCpuTier": 45,
    "recCpuTier": 70,
    "minGpuTier": 45,
    "recGpuTier": 68,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 105,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.15,
    "baseFps1080pLow": 175,
    "steamAppId": 1085660,
    "platform": "steam"
  },
  {
    "id": "warframe",
    "title": "Warframe",
    "genre": "Hızlı Bilim Kurgu Aksiyon / Co-Op",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/230410/header.jpg",
    "releaseYear": 2013,
    "description": "Uzay ninjalarıyla yıldızlararası akıcı aksiyon. Evrimleşen grafik motoru çok düşük donanımlarda bile yüksek FPS sağlar.",
    "minCpuTier": 35,
    "recCpuTier": 65,
    "minGpuTier": 35,
    "recGpuTier": 62,
    "minRamGb": 4,
    "recRamGb": 16,
    "storageGb": 50,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.1,
    "baseFps1080pLow": 210,
    "steamAppId": 230410,
    "platform": "steam"
  },
  {
    "id": "lethalcompany",
    "title": "Lethal Company",
    "genre": "Viral Eşli Korku / Hurdacılık",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1966720/header.jpg",
    "releaseYear": 2023,
    "description": "Terk edilmiş endüstriyel uydulardan hurda topladığın viral bağımsız başyapıt. Her türlü ortalama bilgisayarda akıcı çalışır.",
    "minCpuTier": 30,
    "recCpuTier": 55,
    "minGpuTier": 30,
    "recGpuTier": 50,
    "minRamGb": 4,
    "recRamGb": 8,
    "storageGb": 2,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.05,
    "baseFps1080pLow": 180,
    "steamAppId": 1966720,
    "platform": "steam"
  },
  {
    "id": "liarsbar",
    "title": "Liar's Bar",
    "genre": "Viral Rus Ruleti & Kart Blöfü",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3097560/header.jpg",
    "releaseYear": 2024,
    "description": "Karanlık bir barda arkadaşlarla zar ve kart blöfü yaparak hayatta kalmaya çalıştığın rekor kıran viral parti oyunu.",
    "minCpuTier": 40,
    "recCpuTier": 65,
    "minGpuTier": 40,
    "recGpuTier": 62,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 10,
    "cpuWeight": 0.45,
    "gpuWeight": 0.55,
    "ramWeight": 0.1,
    "baseFps1080pLow": 140,
    "steamAppId": 3097560,
    "platform": "steam"
  },
  {
    "id": "chainedtogether",
    "title": "Chained Together",
    "genre": "Zincirli Tırmanış Co-Op (Türk Yapımı)",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2567870/header.jpg",
    "releaseYear": 2024,
    "description": "Cehennemin dibinden birbirine zincirli şekilde tırmandığın global çapta fırtınalar estiren Türk yapımı co-op platform fenomeni.",
    "minCpuTier": 45,
    "recCpuTier": 70,
    "minGpuTier": 45,
    "recGpuTier": 68,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 12,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.1,
    "baseFps1080pLow": 125,
    "steamAppId": 2567870,
    "platform": "steam"
  },
  {
    "id": "phasmophobia",
    "title": "Phasmophobia",
    "genre": "4 Kişilik Psikolojik Hayalet Avı",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/739630/header.jpg",
    "releaseYear": 2020,
    "description": "Sesli iletişimle hayaletleri tespit ettiğin en popüler paranormal korku oyunu. Orta seviye kasalarda yağ gibi akar.",
    "minCpuTier": 40,
    "recCpuTier": 65,
    "minGpuTier": 40,
    "recGpuTier": 60,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 21,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.1,
    "baseFps1080pLow": 150,
    "steamAppId": 739630,
    "platform": "steam"
  },
  {
    "id": "amongus",
    "title": "Among Us",
    "genre": "Sosyal Çıkarım / Parti Oyunu",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/945360/header.jpg",
    "releaseYear": 2018,
    "description": "Uzay gemisinde hainleri (impostor) bulmaya çalıştığın tüm dünyayı kasıp kavuran eğlenceli parti oyunu.",
    "minCpuTier": 15,
    "recCpuTier": 30,
    "minGpuTier": 15,
    "recGpuTier": 25,
    "minRamGb": 1,
    "recRamGb": 4,
    "storageGb": 1,
    "cpuWeight": 0.7,
    "gpuWeight": 0.3,
    "ramWeight": 0.05,
    "baseFps1080pLow": 400,
    "steamAppId": 945360,
    "platform": "steam"
  },
  {
    "id": "contentwarning",
    "title": "Content Warning",
    "genre": "Viral SpookTube Kamera Çekimi",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2881650/header.jpg",
    "releaseYear": 2024,
    "description": "Korkunç yaratıkları videoya çekip SpookTube'da viral olmaya çalıştığın komik ve gerilimli co-op macera.",
    "minCpuTier": 35,
    "recCpuTier": 60,
    "minGpuTier": 35,
    "recGpuTier": 58,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 4,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.1,
    "baseFps1080pLow": 160,
    "steamAppId": 2881650,
    "platform": "steam"
  },
  {
    "id": "buckshot",
    "title": "Buckshot Roulette",
    "genre": "Taktiksel Pompalı Rulet",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2835570/header.jpg",
    "releaseYear": 2024,
    "description": "Yeraltı kulübünde gizemli bir dağıtıcıya karşı 12 kalibrelik pompalı tüfekle oynadığın gerilim dolu indie hit.",
    "minCpuTier": 25,
    "recCpuTier": 45,
    "minGpuTier": 25,
    "recGpuTier": 40,
    "minRamGb": 2,
    "recRamGb": 4,
    "storageGb": 1,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.05,
    "baseFps1080pLow": 300,
    "steamAppId": 2835570,
    "platform": "steam"
  },
  {
    "id": "balatro",
    "title": "Balatro",
    "genre": "Poker Roguelike / Deste Oluşturma",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2379780/header.jpg",
    "releaseYear": 2024,
    "description": "Poker ellerini çılgın joker kartlarıyla birleştirip skor rekorları kırdığın bağımlılık yapan 2024 indie şaheseri.",
    "minCpuTier": 20,
    "recCpuTier": 35,
    "minGpuTier": 20,
    "recGpuTier": 30,
    "minRamGb": 2,
    "recRamGb": 4,
    "storageGb": 1,
    "cpuWeight": 0.6,
    "gpuWeight": 0.4,
    "ramWeight": 0.05,
    "baseFps1080pLow": 350,
    "steamAppId": 2379780,
    "platform": "steam"
  },
  {
    "id": "hades",
    "title": "Hades",
    "genre": "İzometrik Roguelike Aksiyon",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1145360/header.jpg",
    "releaseYear": 2020,
    "description": "Yeraltı dünyasının prensi Zagreus ile Olimpos tanrılarının lütuflarını toplayarak kaçtığın sanat harikası.",
    "minCpuTier": 30,
    "recCpuTier": 55,
    "minGpuTier": 30,
    "recGpuTier": 50,
    "minRamGb": 4,
    "recRamGb": 8,
    "storageGb": 15,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.05,
    "baseFps1080pLow": 250,
    "steamAppId": 1145360,
    "platform": "steam"
  },
  {
    "id": "hades2",
    "title": "Hades II",
    "genre": "Büyücülük & Mitolojik Roguelike",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1145350/header.jpg",
    "releaseYear": 2024,
    "description": "Melinoë ile Zaman Titanı Chronos'a meydan okuduğun büyü temalı devam oyunu.",
    "minCpuTier": 40,
    "recCpuTier": 65,
    "minGpuTier": 40,
    "recGpuTier": 62,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 10,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.1,
    "baseFps1080pLow": 190,
    "steamAppId": 1145350,
    "platform": "steam"
  },
  {
    "id": "hollowknight",
    "title": "Hollow Knight",
    "genre": "2D Metroidvania Efsanesi",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/367520/header.jpg",
    "releaseYear": 2017,
    "description": "Hallownest'in gizemli harabelerinde böcekler ve canavarlarla savaştığın efsanevi 2D aksiyon.",
    "minCpuTier": 25,
    "recCpuTier": 45,
    "minGpuTier": 25,
    "recGpuTier": 40,
    "minRamGb": 4,
    "recRamGb": 8,
    "storageGb": 9,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.05,
    "baseFps1080pLow": 280,
    "steamAppId": 367520,
    "platform": "steam"
  },
  {
    "id": "terraria",
    "title": "Terraria",
    "genre": "2D Sandbox / Macera",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/105600/header.jpg",
    "releaseYear": 2011,
    "description": "Kaz, savaş, keşfet ve inşa et. Milyonlarca oyuncunun yüzlerce saat geçirdiği 2D hayatta kalma efsanesi.",
    "minCpuTier": 20,
    "recCpuTier": 40,
    "minGpuTier": 15,
    "recGpuTier": 35,
    "minRamGb": 2,
    "recRamGb": 4,
    "storageGb": 1,
    "cpuWeight": 0.65,
    "gpuWeight": 0.35,
    "ramWeight": 0.05,
    "baseFps1080pLow": 300,
    "steamAppId": 105600,
    "platform": "steam"
  },
  {
    "id": "stardewvalley",
    "title": "Stardew Valley",
    "genre": "Çiftlik & Köy Hayatı RPG",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/413150/header.jpg",
    "releaseYear": 2016,
    "description": "Büyükbabanın eski çiftliğini devralıp huzurlu bir yaşam kurduğun efsanevi piksel çiftlik simülatörü.",
    "minCpuTier": 15,
    "recCpuTier": 30,
    "minGpuTier": 15,
    "recGpuTier": 25,
    "minRamGb": 2,
    "recRamGb": 4,
    "storageGb": 1,
    "cpuWeight": 0.6,
    "gpuWeight": 0.4,
    "ramWeight": 0.05,
    "baseFps1080pLow": 350,
    "steamAppId": 413150,
    "platform": "steam"
  },
  {
    "id": "vampiresurvivors",
    "title": "Vampire Survivors",
    "genre": "Mermi Cehennemi Hayatta Kalma",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1794680/header.jpg",
    "releaseYear": 2022,
    "description": "Binlerce canavar akınına karşı otomatik ateş eden silahlarla hayatta kalmaya çalıştığın viral bağımsız oyun.",
    "minCpuTier": 20,
    "recCpuTier": 40,
    "minGpuTier": 15,
    "recGpuTier": 30,
    "minRamGb": 2,
    "recRamGb": 4,
    "storageGb": 1,
    "cpuWeight": 0.7,
    "gpuWeight": 0.3,
    "ramWeight": 0.05,
    "baseFps1080pLow": 300,
    "steamAppId": 1794680,
    "platform": "steam"
  },
  {
    "id": "projectzomboid",
    "title": "Project Zomboid",
    "genre": "Gerçekçi İzometrik Zombi Kıyameti",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/108600/header.jpg",
    "releaseYear": 2013,
    "description": "En küçük bir ısırıkta öldüğün, aşırı derin sağlık ve inşa mekaniklerine sahip hardcore zombi simülatörü.",
    "minCpuTier": 40,
    "recCpuTier": 70,
    "minGpuTier": 35,
    "recGpuTier": 60,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 5,
    "cpuWeight": 0.65,
    "gpuWeight": 0.35,
    "ramWeight": 0.2,
    "baseFps1080pLow": 140,
    "steamAppId": 108600,
    "platform": "steam"
  },
  {
    "id": "deeprockgalactic",
    "title": "Deep Rock Galactic",
    "genre": "Cüce Uzay Madenciliği / Co-Op",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/548430/header.jpg",
    "releaseYear": 2020,
    "description": "%100 yıkılabilir mağaralarda uzaylı böceklere karşı savaşan 4 kişilik cüce madenci takımı.",
    "minCpuTier": 45,
    "recCpuTier": 70,
    "minGpuTier": 45,
    "recGpuTier": 68,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 3,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.1,
    "baseFps1080pLow": 160,
    "steamAppId": 548430,
    "platform": "steam"
  },
  {
    "id": "valheim",
    "title": "Valheim",
    "genre": "Viking Hayatta Kalma / Açık Dünya",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/892970/header.jpg",
    "releaseYear": 2021,
    "description": "İskandinav mitolojisinde usulca inşa edip boss kovaladığın, hafif dokulu ama atmosferik ışıklandırmalı hayatta kalma.",
    "minCpuTier": 45,
    "recCpuTier": 72,
    "minGpuTier": 45,
    "recGpuTier": 70,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 2,
    "cpuWeight": 0.55,
    "gpuWeight": 0.45,
    "ramWeight": 0.1,
    "baseFps1080pLow": 130,
    "steamAppId": 892970,
    "platform": "steam"
  },
  {
    "id": "subnautica",
    "title": "Subnautica",
    "genre": "Sualtı Açık Dünya Hayatta Kalma",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/264710/header.jpg",
    "releaseYear": 2018,
    "description": "Yabancı bir okyanus gezegeninde denizaltı inşa edip derinlerdeki dev leviathanlarla yüzleştiğin başyapıt.",
    "minCpuTier": 40,
    "recCpuTier": 68,
    "minGpuTier": 40,
    "recGpuTier": 65,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 20,
    "cpuWeight": 0.45,
    "gpuWeight": 0.55,
    "ramWeight": 0.1,
    "baseFps1080pLow": 120,
    "steamAppId": 264710,
    "platform": "steam"
  },
  {
    "id": "seaofthieves",
    "title": "Sea of Thieves",
    "genre": "Korsan Açık Dünya Macera",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1172620/header.jpg",
    "releaseYear": 2020,
    "description": "Gemini tayfanla yönettiğin, hazine arayıp düşman gemileriyle top savaşına girdiğin korsan dünyası.",
    "minCpuTier": 45,
    "recCpuTier": 70,
    "minGpuTier": 45,
    "recGpuTier": 68,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 50,
    "cpuWeight": 0.45,
    "gpuWeight": 0.55,
    "ramWeight": 0.1,
    "baseFps1080pLow": 135,
    "steamAppId": 1172620,
    "platform": "steam"
  },
  {
    "id": "theforest",
    "title": "The Forest",
    "genre": "Ada Hayatta Kalma Korku",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/242760/header.jpg",
    "releaseYear": 2018,
    "description": "Uçak kazası sonrası yerlilerle dolu adada oğlunu ararken sığınak kurup hayatta kalma mücadelesi.",
    "minCpuTier": 40,
    "recCpuTier": 65,
    "minGpuTier": 40,
    "recGpuTier": 62,
    "minRamGb": 4,
    "recRamGb": 8,
    "storageGb": 5,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.1,
    "baseFps1080pLow": 140,
    "steamAppId": 242760,
    "platform": "steam"
  },
  {
    "id": "raft",
    "title": "Raft",
    "genre": "Okyanus Sal Hayatta Kalma",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/648800/header.jpg",
    "releaseYear": 2018,
    "description": "Plastik kancayla okyanustan çöp toplayıp salını devasa bir yüzen kaleye dönüştürdüğün eğlenceli co-op.",
    "minCpuTier": 40,
    "recCpuTier": 65,
    "minGpuTier": 40,
    "recGpuTier": 62,
    "minRamGb": 6,
    "recRamGb": 8,
    "storageGb": 10,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.1,
    "baseFps1080pLow": 140,
    "steamAppId": 648800,
    "platform": "steam"
  },
  {
    "id": "slaythespire",
    "title": "Slay the Spire",
    "genre": "Kart Deste Oluşturma Roguelike",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/646570/header.jpg",
    "releaseYear": 2019,
    "description": "Kendi desteni oluşturarak kuleden yukarı tırmandığın roguelike kart türünün öncüsü.",
    "minCpuTier": 20,
    "recCpuTier": 35,
    "minGpuTier": 20,
    "recGpuTier": 30,
    "minRamGb": 2,
    "recRamGb": 4,
    "storageGb": 1,
    "cpuWeight": 0.6,
    "gpuWeight": 0.4,
    "ramWeight": 0.05,
    "baseFps1080pLow": 350,
    "steamAppId": 646570,
    "platform": "steam"
  },
  {
    "id": "deadcells",
    "title": "Dead Cells",
    "genre": "Rogue-lite Metroidvania Aksiyon",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/588650/header.jpg",
    "releaseYear": 2018,
    "description": "Hızlı tempolu, akıcı kombolara sahip, sürekli değişen kale odalarında savaştığın başyapıt.",
    "minCpuTier": 25,
    "recCpuTier": 45,
    "minGpuTier": 25,
    "recGpuTier": 40,
    "minRamGb": 2,
    "recRamGb": 4,
    "storageGb": 1,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.05,
    "baseFps1080pLow": 300,
    "steamAppId": 588650,
    "platform": "steam"
  },
  {
    "id": "satisfactory",
    "title": "Satisfactory",
    "genre": "Birinci Şahıs Fabrika Otomasyonu",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/526870/header.jpg",
    "releaseYear": 2024,
    "description": "Yabancı bir gezegende dev konveyör hatları ve otomatik fabrikalar kurduğun 1.0 sürümüne ulaşan devasa simülatör.",
    "minCpuTier": 55,
    "recCpuTier": 80,
    "minGpuTier": 52,
    "recGpuTier": 76,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 20,
    "cpuWeight": 0.6,
    "gpuWeight": 0.4,
    "ramWeight": 0.2,
    "baseFps1080pLow": 120,
    "steamAppId": 526870,
    "platform": "steam"
  },
  {
    "id": "factorio",
    "title": "Factorio",
    "genre": "2D Fabrika & Lojistik Otomasyonu",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/427520/header.jpg",
    "releaseYear": 2020,
    "description": "'Fabrika büyümeli!' Milyonlarca parçayı optimize ettiğin efsanevi otomasyon klasiği.",
    "minCpuTier": 30,
    "recCpuTier": 60,
    "minGpuTier": 25,
    "recGpuTier": 45,
    "minRamGb": 4,
    "recRamGb": 8,
    "storageGb": 3,
    "cpuWeight": 0.8,
    "gpuWeight": 0.2,
    "ramWeight": 0.1,
    "baseFps1080pLow": 250,
    "steamAppId": 427520,
    "platform": "steam"
  },
  {
    "id": "cuphead",
    "title": "Cuphead",
    "genre": "1930'lar Çizgi Film Zorlu Aksiyon",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/268910/header.jpg",
    "releaseYear": 2017,
    "description": "Geleneksel elle çizilmiş animasyonlara sahip, efsanevi caz müzikleri ve zorlu boss kapışmaları sunan görsel şölen.",
    "minCpuTier": 25,
    "recCpuTier": 45,
    "minGpuTier": 25,
    "recGpuTier": 40,
    "minRamGb": 3,
    "recRamGb": 4,
    "storageGb": 4,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.05,
    "baseFps1080pLow": 250,
    "steamAppId": 268910,
    "platform": "steam"
  },
  {
    "id": "celeste",
    "title": "Celeste",
    "genre": "Hassas Platform Şaheseri",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/504230/header.jpg",
    "releaseYear": 2018,
    "description": "Madeline ile Celeste Dağı'na tırmanırken içsel hesaplaşmalarını çözdüğün ödüllü platform oyunu.",
    "minCpuTier": 20,
    "recCpuTier": 35,
    "minGpuTier": 15,
    "recGpuTier": 30,
    "minRamGb": 2,
    "recRamGb": 4,
    "storageGb": 1,
    "cpuWeight": 0.6,
    "gpuWeight": 0.4,
    "ramWeight": 0.05,
    "baseFps1080pLow": 350,
    "steamAppId": 504230,
    "platform": "steam"
  },
  {
    "id": "undertale",
    "title": "Undertale",
    "genre": "Kült Bağımsız RPG",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/391540/header.jpg",
    "releaseYear": 2015,
    "description": "Kimseyi öldürmek zorunda olmadığın, duygusal ve unutulmaz karakterlere sahip kült RPG klasiği.",
    "minCpuTier": 15,
    "recCpuTier": 30,
    "minGpuTier": 15,
    "recGpuTier": 25,
    "minRamGb": 2,
    "recRamGb": 4,
    "storageGb": 1,
    "cpuWeight": 0.7,
    "gpuWeight": 0.3,
    "ramWeight": 0.05,
    "baseFps1080pLow": 400,
    "steamAppId": 391540,
    "platform": "steam"
  },
  {
    "id": "isaac",
    "title": "The Binding of Isaac: Rebirth",
    "genre": "Rogue-like Zindan Keşfi",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/250900/header.jpg",
    "releaseYear": 2014,
    "description": "Yüzlerce eşya kombosuyla bodrum katında canavarlarla savaştığın efsanevi zindan oyunu.",
    "minCpuTier": 25,
    "recCpuTier": 45,
    "minGpuTier": 20,
    "recGpuTier": 35,
    "minRamGb": 2,
    "recRamGb": 4,
    "storageGb": 1,
    "cpuWeight": 0.6,
    "gpuWeight": 0.4,
    "ramWeight": 0.05,
    "baseFps1080pLow": 300,
    "steamAppId": 250900,
    "platform": "steam"
  },
  {
    "id": "ultrakill",
    "title": "ULTRAKILL",
    "genre": "Retro Kanlı Hızlı FPS",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1229490/header.jpg",
    "releaseYear": 2020,
    "description": "'İnsanlık öldü, kan yakıttır, cehennem doludur.' İnanılmaz refleks isteyen retro esintili FPS devi.",
    "minCpuTier": 30,
    "recCpuTier": 55,
    "minGpuTier": 30,
    "recGpuTier": 50,
    "minRamGb": 4,
    "recRamGb": 8,
    "storageGb": 2,
    "cpuWeight": 0.55,
    "gpuWeight": 0.45,
    "ramWeight": 0.05,
    "baseFps1080pLow": 280,
    "steamAppId": 1229490,
    "platform": "steam"
  },
  {
    "id": "geometrydash",
    "title": "Geometry Dash",
    "genre": "Ritim Tabanlı Platform",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/322170/header.jpg",
    "releaseYear": 2014,
    "description": "Müziğin ritmine göre zıplayıp engelleri aştığın milyonlarca kullanıcı yapımı haritaya sahip ritim oyunu.",
    "minCpuTier": 20,
    "recCpuTier": 35,
    "minGpuTier": 15,
    "recGpuTier": 30,
    "minRamGb": 1,
    "recRamGb": 2,
    "storageGb": 1,
    "cpuWeight": 0.6,
    "gpuWeight": 0.4,
    "ramWeight": 0.05,
    "baseFps1080pLow": 350,
    "steamAppId": 322170,
    "platform": "steam"
  },
  {
    "id": "brotato",
    "title": "Brotato",
    "genre": "Yukarıdan Aşağı Arena Nişancı",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1942280/header.jpg",
    "releaseYear": 2023,
    "description": "Aynı anda 6 silah taşıyan patatesle uzaylı akınlarına karşı savaştığın bağımlılık yapıcı arena oyunu.",
    "minCpuTier": 20,
    "recCpuTier": 40,
    "minGpuTier": 15,
    "recGpuTier": 30,
    "minRamGb": 2,
    "recRamGb": 4,
    "storageGb": 1,
    "cpuWeight": 0.6,
    "gpuWeight": 0.4,
    "ramWeight": 0.05,
    "baseFps1080pLow": 320,
    "steamAppId": 1942280,
    "platform": "steam"
  },
  {
    "id": "dontstarve",
    "title": "Don't Starve Together",
    "genre": "Çok Oyunculu Gotik Hayatta Kalma",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/322330/header.jpg",
    "releaseYear": 2016,
    "description": "Karanlık bir dünyada arkadaşlarınla akıl sağlığını koruyup aç kalmamaya çalıştığın Tim Burton tarzı macera.",
    "minCpuTier": 25,
    "recCpuTier": 45,
    "minGpuTier": 25,
    "recGpuTier": 40,
    "minRamGb": 2,
    "recRamGb": 4,
    "storageGb": 3,
    "cpuWeight": 0.6,
    "gpuWeight": 0.4,
    "ramWeight": 0.05,
    "baseFps1080pLow": 250,
    "steamAppId": 322330,
    "platform": "steam"
  },
  {
    "id": "bloonstd6",
    "title": "Bloons TD 6",
    "genre": "Kule Savunma (Tower Defense)",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/960090/header.jpg",
    "releaseYear": 2018,
    "description": "Maymun kuleleriyle rengarenk balon ordularını patlattığın en popüler kule savunma oyunu.",
    "minCpuTier": 25,
    "recCpuTier": 50,
    "minGpuTier": 20,
    "recGpuTier": 40,
    "minRamGb": 4,
    "recRamGb": 8,
    "storageGb": 2,
    "cpuWeight": 0.7,
    "gpuWeight": 0.3,
    "ramWeight": 0.05,
    "baseFps1080pLow": 250,
    "steamAppId": 960090,
    "platform": "steam"
  },
  {
    "id": "partyanimals",
    "title": "Party Animals",
    "genre": "Fizik Tabanlı Hayvan Dövüşü",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1260320/header.jpg",
    "releaseYear": 2023,
    "description": "Sevimli yavru köpek, kedi ve ördeklerle arkadaşlarını uçurumlardan attığın eğlenceli fizik partisi.",
    "minCpuTier": 45,
    "recCpuTier": 68,
    "minGpuTier": 45,
    "recGpuTier": 65,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 8,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.1,
    "baseFps1080pLow": 140,
    "steamAppId": 1260320,
    "platform": "steam"
  },
  {
    "id": "humanfallflat",
    "title": "Human Fall Flat",
    "genre": "Sakar Fizik Bulmaca / Co-Op",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/477160/header.jpg",
    "releaseYear": 2016,
    "description": "Pelte gibi sallanan karakterlerle bulmacaları çözmeye çalıştığın komik fizik klasiği.",
    "minCpuTier": 30,
    "recCpuTier": 55,
    "minGpuTier": 30,
    "recGpuTier": 50,
    "minRamGb": 4,
    "recRamGb": 8,
    "storageGb": 2,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.05,
    "baseFps1080pLow": 200,
    "steamAppId": 477160,
    "platform": "steam"
  },
  {
    "id": "overcooked2",
    "title": "Overcooked! 2",
    "genre": "Kaotik Mutfak Co-Op",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/448510/header.jpg",
    "releaseYear": 2018,
    "description": "Hareket eden mutfaklarda siparişleri yetiştirmeye çalışırken yangın söndürdüğün dostluk test eden kaos.",
    "minCpuTier": 30,
    "recCpuTier": 50,
    "minGpuTier": 30,
    "recGpuTier": 48,
    "minRamGb": 4,
    "recRamGb": 6,
    "storageGb": 3,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.05,
    "baseFps1080pLow": 220,
    "steamAppId": 448510,
    "platform": "steam"
  },
  {
    "id": "picopark",
    "title": "PICO PARK",
    "genre": "2-8 Kişilik Eşli İş Birliği",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1509960/header.jpg",
    "releaseYear": 2021,
    "description": "Anahtarı alıp kapıya ulaşmak için tüm takımın senkronize olması gereken eğlenceli parti oyunu.",
    "minCpuTier": 15,
    "recCpuTier": 30,
    "minGpuTier": 15,
    "recGpuTier": 25,
    "minRamGb": 1,
    "recRamGb": 2,
    "storageGb": 1,
    "cpuWeight": 0.6,
    "gpuWeight": 0.4,
    "ramWeight": 0.05,
    "baseFps1080pLow": 350,
    "steamAppId": 1509960,
    "platform": "steam"
  },
  {
    "id": "left4dead2",
    "title": "Left 4 Dead 2",
    "genre": "Efsanevi Eşli Zombi Nişancı",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/550/header.jpg",
    "releaseYear": 2009,
    "description": "Valve'ın zamanın ötesindeki Source motorlu 4 kişilik zombi katliamı klasiği.",
    "minCpuTier": 25,
    "recCpuTier": 45,
    "minGpuTier": 25,
    "recGpuTier": 40,
    "minRamGb": 2,
    "recRamGb": 4,
    "storageGb": 13,
    "cpuWeight": 0.6,
    "gpuWeight": 0.4,
    "ramWeight": 0.05,
    "baseFps1080pLow": 280,
    "steamAppId": 550,
    "platform": "steam"
  },
  {
    "id": "garrysmod",
    "title": "Garry's Mod",
    "genre": "Fizik Sandbox / Mod Cenneti",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/4000/header.jpg",
    "releaseYear": 2006,
    "description": "Prop Hunt, TTT ve yüz binlerce modla sınırsız eğlence sunan Valve klasiği.",
    "minCpuTier": 25,
    "recCpuTier": 50,
    "minGpuTier": 25,
    "recGpuTier": 45,
    "minRamGb": 4,
    "recRamGb": 8,
    "storageGb": 5,
    "cpuWeight": 0.7,
    "gpuWeight": 0.3,
    "ramWeight": 0.1,
    "baseFps1080pLow": 240,
    "steamAppId": 4000,
    "platform": "steam"
  },
  {
    "id": "supermarketsim",
    "title": "Supermarket Simulator",
    "genre": "Market Yönetim Simülatörü",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2670630/header.jpg",
    "releaseYear": 2024,
    "description": "Rafları dizdiğin, kasiyerlik yapıp marketini devasa bir süpermarkete dönüştürdüğün viral Türk simülasyonu.",
    "minCpuTier": 45,
    "recCpuTier": 70,
    "minGpuTier": 45,
    "recGpuTier": 68,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 5,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.1,
    "baseFps1080pLow": 135,
    "steamAppId": 2670630,
    "platform": "steam"
  },
  {
    "id": "tcgcardshop",
    "title": "TCG Card Shop Simulator",
    "genre": "Kart Dükkanı Simülatörü",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3070070/header.jpg",
    "releaseYear": 2024,
    "description": "Kart paketleri açıp dükkanında sattığın, müşterileri ağırladığın 2024'ün en çok oynanan simülatörlerinden biri.",
    "minCpuTier": 45,
    "recCpuTier": 70,
    "minGpuTier": 45,
    "recGpuTier": 68,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 5,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.1,
    "baseFps1080pLow": 135,
    "steamAppId": 3070070,
    "platform": "steam"
  },
  {
    "id": "internetcafe2",
    "title": "Internet Cafe Simulator 2",
    "genre": "İnternet Kafe Yönetim Simülatörü",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1563180/header.jpg",
    "releaseYear": 2024,
    "description": "Yeraltı kimya ve ticaret imparatorluğunu kurduğun yeni nesil gerçekçi simülasyon oyunu.",
    "minCpuTier": 50,
    "recCpuTier": 74,
    "minGpuTier": 48,
    "recGpuTier": 72,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 15,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.15,
    "baseFps1080pLow": 120,
    "steamAppId": 1563180,
    "platform": "steam"
  },
  {
    "id": "beamng",
    "title": "BeamNG.drive",
    "genre": "Yumuşak Gövde Araba Fizik Simülatörü",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/284160/header.jpg",
    "releaseYear": 2015,
    "description": "Her bir somun ve cıvatayı gerçek zamanlı simüle eden dünyanın en detaylı araç kaza ve sürüş simülasyonu.",
    "minCpuTier": 55,
    "recCpuTier": 82,
    "minGpuTier": 50,
    "recGpuTier": 78,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 50,
    "cpuWeight": 0.7,
    "gpuWeight": 0.3,
    "ramWeight": 0.2,
    "baseFps1080pLow": 115,
    "steamAppId": 284160,
    "platform": "steam"
  },
  {
    "id": "ets2",
    "title": "Euro Truck Simulator 2",
    "genre": "Kamyon / Yol Simülasyonu",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/227300/header.jpg",
    "releaseYear": 2012,
    "description": "Türkiye haritası ve ProMods ile saatlerce oynanan TIR simülasyonu klasiği. Şehir merkezlerinde CPU tek çekirdeğe yüklenir.",
    "minCpuTier": 35,
    "recCpuTier": 62,
    "minGpuTier": 35,
    "recGpuTier": 60,
    "minRamGb": 6,
    "recRamGb": 16,
    "storageGb": 25,
    "cpuWeight": 0.65,
    "gpuWeight": 0.35,
    "ramWeight": 0.1,
    "baseFps1080pLow": 170,
    "steamAppId": 227300,
    "platform": "steam"
  },
  {
    "id": "farm_sim25",
    "title": "Farming Simulator 25",
    "genre": "Çiftçilik & Arazi Simülasyonu",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2300320/header.jpg",
    "releaseYear": 2024,
    "description": "Yeni nesil zemin deformasyonu, çeltik tarlaları ve gelişmiş traktör fizikleri sunan en popüler çiftlik simülasyonu.",
    "minCpuTier": 50,
    "recCpuTier": 74,
    "minGpuTier": 48,
    "recGpuTier": 72,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 45,
    "cpuWeight": 0.55,
    "gpuWeight": 0.45,
    "ramWeight": 0.15,
    "baseFps1080pLow": 120,
    "steamAppId": 2300320,
    "platform": "steam"
  },
  {
    "id": "msfs2024",
    "title": "Microsoft Flight Simulator 2024",
    "genre": "Tüm Dünya Uçuş Simülasyonu",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2537590/header.jpg",
    "releaseYear": 2024,
    "description": "Dünyanın tamamını 1:1 ölçekte buluttan aktaran teknoloji harikası. İdeal deneyim için 32GB+ RAM ve yüksek hızlı internet/SSD şarttır.",
    "minCpuTier": 70,
    "recCpuTier": 92,
    "minGpuTier": 68,
    "recGpuTier": 88,
    "minRamGb": 16,
    "recRamGb": 64,
    "storageGb": 50,
    "cpuWeight": 0.65,
    "gpuWeight": 0.35,
    "ramWeight": 0.35,
    "baseFps1080pLow": 65,
    "steamAppId": 2537590,
    "platform": "steam"
  },
  {
    "id": "teardown",
    "title": "Teardown",
    "genre": "Voxel Yıkım & Soygun Simülasyonu",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1167630/header.jpg",
    "releaseYear": 2022,
    "description": "Tamamen yıkılabilir voksel dünyasında patlayıcılar ve balyozla kaçış rotası açtığın fizik harikası.",
    "minCpuTier": 55,
    "recCpuTier": 78,
    "minGpuTier": 52,
    "recGpuTier": 76,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 4,
    "cpuWeight": 0.6,
    "gpuWeight": 0.4,
    "ramWeight": 0.15,
    "baseFps1080pLow": 120,
    "steamAppId": 1167630,
    "platform": "steam"
  },
  {
    "id": "rimworld",
    "title": "RimWorld",
    "genre": "Bilim Kurgu Koloni Yönetim Simülatörü",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/294100/header.jpg",
    "releaseYear": 2018,
    "description": "Yapay zeka hikaye anlatıcısıyla koloni sakinlerinin psikolojisini ve hayatta kalmasını yönettiğin derin strateji.",
    "minCpuTier": 35,
    "recCpuTier": 65,
    "minGpuTier": 25,
    "recGpuTier": 45,
    "minRamGb": 4,
    "recRamGb": 8,
    "storageGb": 1,
    "cpuWeight": 0.85,
    "gpuWeight": 0.15,
    "ramWeight": 0.1,
    "baseFps1080pLow": 250,
    "steamAppId": 294100,
    "platform": "steam"
  },
  {
    "id": "citiesskylines",
    "title": "Cities: Skylines",
    "genre": "Şehir Kurma & Trafik Simülasyonu",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/255710/header.jpg",
    "releaseYear": 2015,
    "description": "Dev metropoller kurup kavşak ve toplu taşıma hatlarıyla trafiği çözdüğün şehir kurma klasiği.",
    "minCpuTier": 45,
    "recCpuTier": 74,
    "minGpuTier": 40,
    "recGpuTier": 65,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 10,
    "cpuWeight": 0.7,
    "gpuWeight": 0.3,
    "ramWeight": 0.2,
    "baseFps1080pLow": 130,
    "steamAppId": 255710,
    "platform": "steam"
  },
  {
    "id": "citiesskylines2",
    "title": "Cities: Skylines II",
    "genre": "Yeni Nesil Şehir Kurma",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/949230/header.jpg",
    "releaseYear": 2023,
    "description": "Bireysel vatandaş yaşam döngüsü ve mevsimsel hava simülasyonu sunan ağır sistem isteyen devam oyunu.",
    "minCpuTier": 68,
    "recCpuTier": 88,
    "minGpuTier": 65,
    "recGpuTier": 85,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 60,
    "cpuWeight": 0.65,
    "gpuWeight": 0.35,
    "ramWeight": 0.25,
    "baseFps1080pLow": 60,
    "steamAppId": 949230,
    "platform": "steam"
  },
  {
    "id": "manorlords",
    "title": "Manor Lords",
    "genre": "Orta Çağ Şehir Kurma & Taktik Savaş",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1363080/header.jpg",
    "releaseYear": 2024,
    "description": "Unreal Engine motoruyla tarihi doğruluğa sahip şehir kurma fenomeni. Büyüyen köylerde vatandaş lojistiği işlemci gücüne bakar.",
    "minCpuTier": 50,
    "recCpuTier": 74,
    "minGpuTier": 46,
    "recGpuTier": 70,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 16,
    "cpuWeight": 0.6,
    "gpuWeight": 0.4,
    "ramWeight": 0.15,
    "baseFps1080pLow": 130,
    "steamAppId": 1363080,
    "platform": "steam"
  },
  {
    "id": "bannerlord",
    "title": "Mount & Blade II: Bannerlord",
    "genre": "Orta Çağ Savaş / Strateji Simülatörü",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/261550/header.jpg",
    "releaseYear": 2020,
    "description": "TaleWorlds'ün Türk yapımı dünya devi. 1000 kişilik meydan savaşlarında atlı ve okçu yapay zekası işlemciyi sonuna kadar terletir.",
    "minCpuTier": 55,
    "recCpuTier": 82,
    "minGpuTier": 46,
    "recGpuTier": 72,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 60,
    "cpuWeight": 0.7,
    "gpuWeight": 0.3,
    "ramWeight": 0.15,
    "baseFps1080pLow": 140,
    "steamAppId": 261550,
    "platform": "steam"
  },
  {
    "id": "wukong",
    "title": "Black Myth: Wukong",
    "genre": "Unreal Engine 5 Aksiyon / RPG",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2358720/header.jpg",
    "releaseYear": 2024,
    "description": "Unreal Engine 5 Lumen ve Nanite motorunu kullanan yeni nesil başyapıt. Ekran kartının shader birimlerini yoğun kullanır.",
    "minCpuTier": 65,
    "recCpuTier": 84,
    "minGpuTier": 65,
    "recGpuTier": 86,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 130,
    "cpuWeight": 0.4,
    "gpuWeight": 0.6,
    "ramWeight": 0.15,
    "baseFps1080pLow": 80,
    "steamAppId": 2358720,
    "platform": "steam"
  },
  {
    "id": "spacemarine2",
    "title": "Warhammer 40,000: Space Marine 2",
    "genre": "Yeni Nesil TPS / Sürü Katliamı",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2183900/header.jpg",
    "releaseYear": 2024,
    "description": "Ekranda binlerce Tyranid canavarının aktığı Swarm motoruyla donatılmış muazzam sinematik aksiyon.",
    "minCpuTier": 65,
    "recCpuTier": 84,
    "minGpuTier": 62,
    "recGpuTier": 84,
    "minRamGb": 16,
    "recRamGb": 16,
    "storageGb": 75,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.15,
    "baseFps1080pLow": 85,
    "steamAppId": 2183900,
    "platform": "steam"
  },
  {
    "id": "cyberpunk",
    "title": "Cyberpunk 2077: Phantom Liberty",
    "genre": "Açık Dünya / Ray Tracing RPG",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1091500/header.jpg",
    "releaseYear": 2023,
    "description": "Grafik teknolojisinin zirvesi. Path Tracing ve DLSS 3 testlerinin vazgeçilmez kıyaslama oyunu. Ekran kartını son damlasına kadar zorlar.",
    "minCpuTier": 60,
    "recCpuTier": 82,
    "minGpuTier": 60,
    "recGpuTier": 85,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 90,
    "cpuWeight": 0.35,
    "gpuWeight": 0.65,
    "ramWeight": 0.15,
    "baseFps1080pLow": 85,
    "steamAppId": 1091500,
    "platform": "steam"
  },
  {
    "id": "gta6",
    "title": "Grand Theft Auto VI",
    "genre": "Açık Dünya / Yeni Nesil Aksiyon",
    "coverImage": "/games/gta6.jpg",
    "releaseYear": 2025,
    "description": "Rockstar Games'in yeni nesil RAGE motoru. Yoğun NPC yapay zekası, gelişmiş ışın izleme ve devasa harita nedeniyle hem güçlü CPU hem 12GB+ GPU VRAM isteyecek.",
    "minCpuTier": 70,
    "recCpuTier": 88,
    "minGpuTier": 68,
    "recGpuTier": 86,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 150,
    "cpuWeight": 0.45,
    "gpuWeight": 0.55,
    "ramWeight": 0.2,
    "baseFps1080pLow": 75,
    "platform": "all"
  },
  {
    "id": "gta5",
    "title": "Grand Theft Auto V",
    "genre": "Açık Dünya / Aksiyon",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/271590/header.jpg",
    "releaseYear": 2015,
    "description": "Tarihin en çok satan açık dünya oyunu ve FiveM RP modları. Geniş araba filoları ve sunucu modları için 16GB+ RAM gereklidir.",
    "minCpuTier": 35,
    "recCpuTier": 60,
    "minGpuTier": 35,
    "recGpuTier": 55,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 110,
    "cpuWeight": 0.55,
    "gpuWeight": 0.45,
    "ramWeight": 0.15,
    "baseFps1080pLow": 170,
    "steamAppId": 271590,
    "platform": "steam"
  },
  {
    "id": "rdr2",
    "title": "Red Dead Redemption 2",
    "genre": "Açık Dünya / Western Başyapıt",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1174180/header.jpg",
    "releaseYear": 2019,
    "description": "Rockstar'ın muazzam detay seviyesine ve volumetrik ışıklandırmaya sahip şaheseri. Ultra ayarlarda güçlü GPU ve çift kanal RAM ister.",
    "minCpuTier": 50,
    "recCpuTier": 75,
    "minGpuTier": 50,
    "recGpuTier": 76,
    "minRamGb": 12,
    "recRamGb": 16,
    "storageGb": 150,
    "cpuWeight": 0.4,
    "gpuWeight": 0.6,
    "ramWeight": 0.15,
    "baseFps1080pLow": 105,
    "steamAppId": 1174180,
    "platform": "steam"
  },
  {
    "id": "eafc25",
    "title": "EA SPORTS FC™ 25",
    "genre": "Futbol Simülasyonu / Spor",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2669320/header.jpg",
    "releaseYear": 2024,
    "description": "HyperMotionV teknolojisi ve FC IQ taktik motoru ile EA'in en son futbol oyunu. 144Hz akıcı maç deneyimi için dengeli ekran kartı ister.",
    "minCpuTier": 50,
    "recCpuTier": 75,
    "minGpuTier": 48,
    "recGpuTier": 72,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 100,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.1,
    "baseFps1080pLow": 145,
    "steamAppId": 2669320,
    "platform": "steam"
  },
  {
    "id": "bg3",
    "title": "Baldur's Gate 3",
    "genre": "Sıra Tabanlı RPG Başyapıt",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1086940/header.jpg",
    "releaseYear": 2023,
    "description": "Yılın Oyunu ödüllü D&D şaheseri. 3. Bölüm şehir sokaklarındaki binlerce NPC nedeniyle güçlü çok çekirdekli işlemci ister.",
    "minCpuTier": 55,
    "recCpuTier": 80,
    "minGpuTier": 52,
    "recGpuTier": 76,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 150,
    "cpuWeight": 0.55,
    "gpuWeight": 0.45,
    "ramWeight": 0.15,
    "baseFps1080pLow": 110,
    "steamAppId": 1086940,
    "platform": "steam"
  },
  {
    "id": "eldenring",
    "title": "Elden Ring: Shadow of the Erdtree",
    "genre": "Açık Dünya Soulsborne",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/header.jpg",
    "releaseYear": 2024,
    "description": "FromSoftware'in efsanevi açık dünya aksiyon RPG'si. 60 FPS kilitli motorunda ani FPS düşüşü yaşamamak için sağlam CPU ve RAM ister.",
    "minCpuTier": 55,
    "recCpuTier": 78,
    "minGpuTier": 52,
    "recGpuTier": 74,
    "minRamGb": 12,
    "recRamGb": 16,
    "storageGb": 80,
    "cpuWeight": 0.45,
    "gpuWeight": 0.55,
    "ramWeight": 0.15,
    "baseFps1080pLow": 115,
    "steamAppId": 1245620,
    "platform": "steam"
  },
  {
    "id": "forza5",
    "title": "Forza Horizon 5",
    "genre": "Açık Dünya Yarış",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1551360/header.jpg",
    "releaseYear": 2021,
    "description": "Meksika'nın eşsiz coğrafyasında harika grafikler sunan yarış klasiği. Optimizasyonu çok iyi olup yüksek çözünürlükte VRAM sever.",
    "minCpuTier": 45,
    "recCpuTier": 74,
    "minGpuTier": 46,
    "recGpuTier": 74,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 110,
    "cpuWeight": 0.4,
    "gpuWeight": 0.6,
    "ramWeight": 0.15,
    "baseFps1080pLow": 130,
    "steamAppId": 1551360,
    "platform": "steam"
  },
  {
    "id": "helldivers2",
    "title": "Helldivers 2",
    "genre": "Kooperatif PvE Nişancı",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/553850/header.jpg",
    "releaseYear": 2024,
    "description": "Böcek orduları, patlama fizikleri ve yoğun düşman akınları nedeniyle CPU yükü tavan yapan süper eğlenceli kooperatif nişancı.",
    "minCpuTier": 60,
    "recCpuTier": 82,
    "minGpuTier": 58,
    "recGpuTier": 78,
    "minRamGb": 16,
    "recRamGb": 16,
    "storageGb": 100,
    "cpuWeight": 0.6,
    "gpuWeight": 0.4,
    "ramWeight": 0.15,
    "baseFps1080pLow": 95,
    "steamAppId": 553850,
    "platform": "steam"
  },
  {
    "id": "gow_ragnarok",
    "title": "God of War Ragnarök",
    "genre": "Sinematik Aksiyon / Macera",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2322010/header.jpg",
    "releaseYear": 2024,
    "description": "Kratos ve Atreus'un İskandinav destanı. PC sürümünde 6GB+ VRAM zorunluluğu ve gelişmiş ölçeklendirme (FSR/DLSS) desteği bulunur.",
    "minCpuTier": 55,
    "recCpuTier": 78,
    "minGpuTier": 55,
    "recGpuTier": 78,
    "minRamGb": 16,
    "recRamGb": 16,
    "storageGb": 190,
    "cpuWeight": 0.45,
    "gpuWeight": 0.55,
    "ramWeight": 0.15,
    "baseFps1080pLow": 95,
    "steamAppId": 2322010,
    "platform": "steam"
  },
  {
    "id": "stalker2",
    "title": "S.T.A.L.K.E.R. 2: Heart of Chornobyl",
    "genre": "Unreal Engine 5 Kıyamet Sonrası Hayatta Kalma",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1643320/header.jpg",
    "releaseYear": 2024,
    "description": "Çernobil Bölgesi'nde UE5 Nanite ve Lumen teknolojisiyle donatılmış, ağır donanım ve 32GB RAM isteyen yeni nesil hayatta kalma FPS.",
    "minCpuTier": 68,
    "recCpuTier": 86,
    "minGpuTier": 65,
    "recGpuTier": 85,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 160,
    "cpuWeight": 0.45,
    "gpuWeight": 0.55,
    "ramWeight": 0.2,
    "baseFps1080pLow": 75,
    "steamAppId": 1643320,
    "platform": "steam"
  },
  {
    "id": "silenthill2",
    "title": "Silent Hill 2 Remake",
    "genre": "Unreal Engine 5 Psikolojik Korku",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2124490/header.jpg",
    "releaseYear": 2024,
    "description": "Bloober Team tarafından UE5 ile baştan yaratılan sisli korku klasiği. Yoğun volumetrik sis ve ışın izleme için güçlü GPU şarttır.",
    "minCpuTier": 62,
    "recCpuTier": 82,
    "minGpuTier": 62,
    "recGpuTier": 82,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 50,
    "cpuWeight": 0.4,
    "gpuWeight": 0.6,
    "ramWeight": 0.15,
    "baseFps1080pLow": 80,
    "steamAppId": 2124490,
    "platform": "steam"
  },
  {
    "id": "mhw_wilds",
    "title": "Monster Hunter Wilds",
    "genre": "Yeni Nesil Avcılık / Açık Dünya",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2246340/header.jpg",
    "releaseYear": 2025,
    "description": "Capcom'un RE Engine motoruyla devasa ekosistemleri canlandırdığı yeni nesil avcılık oyunu. Çoklu canavar kapışmalarında güçlü CPU ister.",
    "minCpuTier": 68,
    "recCpuTier": 86,
    "minGpuTier": 65,
    "recGpuTier": 84,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 140,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.2,
    "baseFps1080pLow": 80,
    "steamAppId": 2246340,
    "platform": "steam"
  },
  {
    "id": "starfield",
    "title": "Starfield",
    "genre": "Uzay RPG / Açık Dünya",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1716740/header.jpg",
    "releaseYear": 2023,
    "description": "Bethesda'nın Creation Engine 2 motorlu uzay macerası. Şehir merkezlerinde CPU'yu, açık gezegenlerde GPU ve hızlı SSD'yi zorlar.",
    "minCpuTier": 65,
    "recCpuTier": 84,
    "minGpuTier": 62,
    "recGpuTier": 82,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 125,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.2,
    "baseFps1080pLow": 85,
    "steamAppId": 1716740,
    "platform": "steam"
  },
  {
    "id": "hogwarts",
    "title": "Hogwarts Legacy",
    "genre": "Açık Dünya Büyücülük RPG",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/990080/header.jpg",
    "releaseYear": 2023,
    "description": "Hogwarts şatosu ve çevre köylerde devasa açık dünya. 16GB RAM'de takılmalar olabileceğinden 32GB RAM ve 8GB+ VRAM tavsiye edilir.",
    "minCpuTier": 55,
    "recCpuTier": 78,
    "minGpuTier": 52,
    "recGpuTier": 76,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 85,
    "cpuWeight": 0.45,
    "gpuWeight": 0.55,
    "ramWeight": 0.2,
    "baseFps1080pLow": 95,
    "steamAppId": 990080,
    "platform": "steam"
  },
  {
    "id": "witcher3",
    "title": "The Witcher 3: Wild Hunt (Next-Gen)",
    "genre": "Açık Dünya RPG Başyapıt",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/292030/header.jpg",
    "releaseYear": 2022,
    "description": "Next-Gen güncellemesiyle Ray Tracing ve DLSS/FSR eklenen Geralt'ın efsanevi macerası. Klasik modda çok akıcı, RT modda ağırdır.",
    "minCpuTier": 45,
    "recCpuTier": 74,
    "minGpuTier": 45,
    "recGpuTier": 74,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 60,
    "cpuWeight": 0.45,
    "gpuWeight": 0.55,
    "ramWeight": 0.15,
    "baseFps1080pLow": 125,
    "steamAppId": 292030,
    "platform": "steam"
  },
  {
    "id": "re4_remake",
    "title": "Resident Evil 4 Remake",
    "genre": "Hayatta Kalma Korku / Aksiyon",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2050650/header.jpg",
    "releaseYear": 2023,
    "description": "Capcom RE Engine harikası. Kusursuz optimizasyona sahip olup VRAM kullanımını doğru ayarladığında yüksek FPS garantidir.",
    "minCpuTier": 52,
    "recCpuTier": 74,
    "minGpuTier": 50,
    "recGpuTier": 74,
    "minRamGb": 16,
    "recRamGb": 16,
    "storageGb": 65,
    "cpuWeight": 0.4,
    "gpuWeight": 0.6,
    "ramWeight": 0.15,
    "baseFps1080pLow": 115,
    "steamAppId": 2050650,
    "platform": "steam"
  },
  {
    "id": "spiderman",
    "title": "Marvel's Spider-Man Remastered",
    "genre": "Açık Dünya Süper Kahraman",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1817070/header.jpg",
    "releaseYear": 2022,
    "description": "Manhattan gökdelenleri arasında ağ atarken yüksek hızda asset yüklemesi için güçlü CPU ve hızlı NVMe SSD gerektirir.",
    "minCpuTier": 50,
    "recCpuTier": 76,
    "minGpuTier": 48,
    "recGpuTier": 74,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 75,
    "cpuWeight": 0.55,
    "gpuWeight": 0.45,
    "ramWeight": 0.15,
    "baseFps1080pLow": 120,
    "steamAppId": 1817070,
    "platform": "steam"
  },
  {
    "id": "ac_mirage",
    "title": "Assassin's Creed Mirage",
    "genre": "Tarihsel Gizlilik / Aksiyon",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2842100/header.jpg",
    "releaseYear": 2023,
    "description": "9. yüzyıl Bağdat sokaklarında geçen klasik Assassin hissiyatı. Anvil motoru kalabalık şehirlerde dengeli CPU ve GPU ister.",
    "minCpuTier": 50,
    "recCpuTier": 74,
    "minGpuTier": 48,
    "recGpuTier": 72,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 40,
    "cpuWeight": 0.45,
    "gpuWeight": 0.55,
    "ramWeight": 0.15,
    "baseFps1080pLow": 110,
    "steamAppId": 2842100,
    "platform": "steam"
  },
  {
    "id": "alanwake2",
    "title": "Alan Wake 2",
    "genre": "Hayatta Kalma Korku / Mesh Shader Devi",
    "coverImage": "/games/alanwake2.jpg",
    "releaseYear": 2023,
    "description": "Mesh Shaders ve Full Path Tracing kullanan teknoloji demosu ayarında başyapıt. En az RTX 2060 / RX 6600 gerektirir.",
    "minCpuTier": 65,
    "recCpuTier": 85,
    "minGpuTier": 65,
    "recGpuTier": 88,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 90,
    "cpuWeight": 0.35,
    "gpuWeight": 0.65,
    "ramWeight": 0.2,
    "baseFps1080pLow": 70,
    "platform": "epic"
  },
  {
    "id": "tlou1",
    "title": "The Last of Us Part I",
    "genre": "Sinematik Hayatta Kalma / Aksiyon",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1888930/header.jpg",
    "releaseYear": 2023,
    "description": "Naughty Dog'un duygu yüklü klasiği. Shader derleme süreci ve yoğun dokular nedeniyle en az 8GB VRAM ve güçlü CPU ister.",
    "minCpuTier": 62,
    "recCpuTier": 82,
    "minGpuTier": 60,
    "recGpuTier": 80,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 100,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.2,
    "baseFps1080pLow": 85,
    "steamAppId": 1888930,
    "platform": "steam"
  },
  {
    "id": "ghostoftsushima",
    "title": "Ghost of Tsushima DIRECTOR'S CUT",
    "genre": "Samuray Açık Dünya Başyapıt",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2215430/header.jpg",
    "releaseYear": 2024,
    "description": "Moğol işgali altındaki Tsuşima adasında rüzgarı takip ettiğin, muhteşem optimizasyona sahip samuray destanı.",
    "minCpuTier": 52,
    "recCpuTier": 76,
    "minGpuTier": 50,
    "recGpuTier": 76,
    "minRamGb": 16,
    "recRamGb": 16,
    "storageGb": 75,
    "cpuWeight": 0.45,
    "gpuWeight": 0.55,
    "ramWeight": 0.15,
    "baseFps1080pLow": 115,
    "steamAppId": 2215430,
    "platform": "steam"
  },
  {
    "id": "sekiro",
    "title": "Sekiro: Shadows Die Twice",
    "genre": "Hızlı Kılıç Savunma / Soulsborne",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/814380/header.jpg",
    "releaseYear": 2019,
    "description": "Kusursuz parry mekaniklerine ve nefes kesen boss savaşlarına sahip Yılın Oyunu ödüllü FromSoftware şaheseri.",
    "minCpuTier": 45,
    "recCpuTier": 70,
    "minGpuTier": 45,
    "recGpuTier": 68,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 25,
    "cpuWeight": 0.45,
    "gpuWeight": 0.55,
    "ramWeight": 0.1,
    "baseFps1080pLow": 130,
    "steamAppId": 814380,
    "platform": "steam"
  },
  {
    "id": "darksouls3",
    "title": "DARK SOULS™ III",
    "genre": "Karanlık Fantezi Aksiyon RPG",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/374320/header.jpg",
    "releaseYear": 2016,
    "description": "Külleri alevlendirmeye çalıştığın efsanevi Souls üçlemesinin zirve noktası.",
    "minCpuTier": 40,
    "recCpuTier": 65,
    "minGpuTier": 40,
    "recGpuTier": 62,
    "minRamGb": 8,
    "recRamGb": 8,
    "storageGb": 25,
    "cpuWeight": 0.45,
    "gpuWeight": 0.55,
    "ramWeight": 0.1,
    "baseFps1080pLow": 140,
    "steamAppId": 374320,
    "platform": "steam"
  },
  {
    "id": "skyrim",
    "title": "The Elder Scrolls V: Skyrim Special Edition",
    "genre": "Açık Dünya Fantezi RPG",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/489830/header.jpg",
    "releaseYear": 2016,
    "description": "Dovahkiin olarak ejderhalarla savaştığın, binlerce mod desteğiyle ölümsüzleşen efsanevi RPG.",
    "minCpuTier": 35,
    "recCpuTier": 60,
    "minGpuTier": 35,
    "recGpuTier": 55,
    "minRamGb": 8,
    "recRamGb": 8,
    "storageGb": 12,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.1,
    "baseFps1080pLow": 180,
    "steamAppId": 489830,
    "platform": "steam"
  },
  {
    "id": "fallout4",
    "title": "Fallout 4",
    "genre": "Kıyamet Sonrası Açık Dünya",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/377160/header.jpg",
    "releaseYear": 2015,
    "description": "Nükleer kıyamet sonrası Boston çöllerinde üs kurup oğlunu aradığın devasa açık dünya.",
    "minCpuTier": 40,
    "recCpuTier": 65,
    "minGpuTier": 40,
    "recGpuTier": 60,
    "minRamGb": 8,
    "recRamGb": 8,
    "storageGb": 30,
    "cpuWeight": 0.55,
    "gpuWeight": 0.45,
    "ramWeight": 0.1,
    "baseFps1080pLow": 150,
    "steamAppId": 377160,
    "platform": "steam"
  },
  {
    "id": "doometernal",
    "title": "DOOM Eternal",
    "genre": "Hızlı Cehennem Katliamı FPS",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/782330/header.jpg",
    "releaseYear": 2020,
    "description": "id Tech 7 motoruyla 300+ FPS'lere ulaşabilen, sektörün en iyi optimize edilmiş FPS şaheseri.",
    "minCpuTier": 45,
    "recCpuTier": 74,
    "minGpuTier": 45,
    "recGpuTier": 72,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 50,
    "cpuWeight": 0.4,
    "gpuWeight": 0.6,
    "ramWeight": 0.1,
    "baseFps1080pLow": 190,
    "steamAppId": 782330,
    "platform": "steam"
  },
  {
    "id": "diablo4",
    "title": "Diablo IV",
    "genre": "Karanlık İzometrik ARPG",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2344520/header.jpg",
    "releaseYear": 2023,
    "description": "Sığınak dünyasında iblis biçme şöleni. Ultra dokularda VRAM tüketimi artar, DLSS/FSR ile tüm modern kasalarda harika çalışır.",
    "minCpuTier": 48,
    "recCpuTier": 72,
    "minGpuTier": 48,
    "recGpuTier": 72,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 90,
    "cpuWeight": 0.45,
    "gpuWeight": 0.55,
    "ramWeight": 0.15,
    "baseFps1080pLow": 145,
    "steamAppId": 2344520,
    "platform": "steam"
  },
  {
    "id": "rust",
    "title": "Rust",
    "genre": "Çok Oyunculu Hayatta Kalma",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/252490/header.jpg",
    "releaseYear": 2018,
    "description": "Unity motorunun en ağır hayatta kalma oyunu. Yüz binlerce base parçası ve oyuncu nedeniyle 16GB değil 32GB RAM ve hızlı CPU şarttır.",
    "minCpuTier": 55,
    "recCpuTier": 80,
    "minGpuTier": 50,
    "recGpuTier": 76,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 25,
    "cpuWeight": 0.65,
    "gpuWeight": 0.35,
    "ramWeight": 0.3,
    "baseFps1080pLow": 110,
    "steamAppId": 252490,
    "platform": "steam"
  },
  {
    "id": "tarkov",
    "title": "Escape from Tarkov",
    "genre": "Gerçekçi Taktiksel Extraction Shooter",
    "coverImage": "/games/tarkov.jpg",
    "releaseYear": 2024,
    "description": "L3 Cache boyutuna (özellikle Ryzen 7800X3D/5800X3D) ve 32GB RAM'e aşırı muhtaç, Streets of Tarkov gibi ağır haritalara sahip taktik FPS.",
    "minCpuTier": 70,
    "recCpuTier": 92,
    "minGpuTier": 60,
    "recGpuTier": 80,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 40,
    "cpuWeight": 0.75,
    "gpuWeight": 0.25,
    "ramWeight": 0.35,
    "baseFps1080pLow": 90,
    "platform": "all"
  },
  {
    "id": "palworld",
    "title": "Palworld",
    "genre": "Açık Dünya Yaratık Toplama / Hayatta Kalma",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1623730/header.jpg",
    "releaseYear": 2024,
    "description": "Unreal Engine 5 ile rekorlar kıran hayatta kalma oyunu. Kalabalık üslerde otomasyon çalışırken CPU ve RAM tüketimi artar.",
    "minCpuTier": 55,
    "recCpuTier": 78,
    "minGpuTier": 52,
    "recGpuTier": 76,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 40,
    "cpuWeight": 0.55,
    "gpuWeight": 0.45,
    "ramWeight": 0.2,
    "baseFps1080pLow": 115,
    "steamAppId": 1623730,
    "platform": "steam"
  },
  {
    "id": "ark_ascended",
    "title": "ARK: Survival Ascended",
    "genre": "Unreal Engine 5 Dinozor Hayatta Kalma",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2399830/header.jpg",
    "releaseYear": 2023,
    "description": "UE5 Nanite ormanları ve dev dinozorlar. Piyasanın en ağır sistem isteyen oyunlarından biridir; güçlü RTX GPU ve 32GB RAM ister.",
    "minCpuTier": 65,
    "recCpuTier": 86,
    "minGpuTier": 68,
    "recGpuTier": 88,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 85,
    "cpuWeight": 0.45,
    "gpuWeight": 0.55,
    "ramWeight": 0.25,
    "baseFps1080pLow": 65,
    "steamAppId": 2399830,
    "platform": "steam"
  },
  {
    "id": "sons_forest",
    "title": "Sons of the Forest",
    "genre": "Ada Hayatta Kalma Korku",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1326470/header.jpg",
    "releaseYear": 2024,
    "description": "Yamyamlarla dolu adada dinamik mevsimler ve ağaç kesme fizikleri. Çok oyunculu modda dengeli sistem ile çok zevklidir.",
    "minCpuTier": 55,
    "recCpuTier": 76,
    "minGpuTier": 52,
    "recGpuTier": 74,
    "minRamGb": 12,
    "recRamGb": 16,
    "storageGb": 20,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.15,
    "baseFps1080pLow": 110,
    "steamAppId": 1326470,
    "platform": "steam"
  },
  {
    "id": "readyornot",
    "title": "Ready or Not",
    "genre": "Taktiksel SWAT Baskın Simülatörü",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1144200/header.jpg",
    "releaseYear": 2023,
    "description": "Kapı kırma, şüpheli etkisiz hale getirme ve rehine kurtarma odaklı son yılların en iyi taktiksel SWAT oyunu.",
    "minCpuTier": 55,
    "recCpuTier": 78,
    "minGpuTier": 52,
    "recGpuTier": 76,
    "minRamGb": 16,
    "recRamGb": 16,
    "storageGb": 90,
    "cpuWeight": 0.5,
    "gpuWeight": 0.5,
    "ramWeight": 0.15,
    "baseFps1080pLow": 110,
    "steamAppId": 1144200,
    "platform": "steam"
  },
  {
    "id": "enshrouded",
    "title": "Enshrouded",
    "genre": "Voksel Tabanlı Açık Dünya Hayatta Kalma",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1203620/header.jpg",
    "releaseYear": 2024,
    "description": "Sis kaplı topraklarda 16 kişiye kadar inşaat ve zindan yağması yaptığın voxel motorlu açık dünya RPG.",
    "minCpuTier": 55,
    "recCpuTier": 78,
    "minGpuTier": 55,
    "recGpuTier": 78,
    "minRamGb": 16,
    "recRamGb": 16,
    "storageGb": 60,
    "cpuWeight": 0.45,
    "gpuWeight": 0.55,
    "ramWeight": 0.15,
    "baseFps1080pLow": 105,
    "steamAppId": 1203620,
    "platform": "steam"
  },
  {
    "id": "bodycam",
    "title": "Bodycam",
    "genre": "Unreal Engine 5 Vücut Kamerası Nişancı",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2406770/header.jpg",
    "releaseYear": 2024,
    "description": "Foto-gerçekçi aydınlatma ve vücut kamerası perspektifiyle sinematik gerçekçilik sunan yeni nesil FPS.",
    "minCpuTier": 65,
    "recCpuTier": 85,
    "minGpuTier": 65,
    "recGpuTier": 86,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 50,
    "cpuWeight": 0.4,
    "gpuWeight": 0.6,
    "ramWeight": 0.2,
    "baseFps1080pLow": 75,
    "steamAppId": 2406770,
    "platform": "steam"
  },
  {
    "id": "dayz",
    "title": "DayZ",
    "genre": "Açık Dünya Zombi Hayatta Kalma",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/221100/header.jpg",
    "releaseYear": 2018,
    "description": "Çernarus'un uçsuz bucaksız topraklarında yiyecek arayıp hayatta kalmaya çalıştığın hardcore efsane.",
    "minCpuTier": 45,
    "recCpuTier": 72,
    "minGpuTier": 45,
    "recGpuTier": 70,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 25,
    "cpuWeight": 0.6,
    "gpuWeight": 0.4,
    "ramWeight": 0.15,
    "baseFps1080pLow": 130,
    "steamAppId": 221100,
    "platform": "steam"
  },
  {
    "id": "squad",
    "title": "Squad",
    "genre": "50v50 Gerçekçi Askeri İletişim",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/393380/header.jpg",
    "releaseYear": 2020,
    "description": "Telsiz iletişimi, lojistik hatları ve manga liderliğiyle gerçek muharebe ortamı sunan taktiksel FPS.",
    "minCpuTier": 55,
    "recCpuTier": 80,
    "minGpuTier": 52,
    "recGpuTier": 76,
    "minRamGb": 16,
    "recRamGb": 32,
    "storageGb": 65,
    "cpuWeight": 0.65,
    "gpuWeight": 0.35,
    "ramWeight": 0.2,
    "baseFps1080pLow": 105,
    "steamAppId": 393380,
    "platform": "steam"
  },
  {
    "id": "deadbydaylight",
    "title": "Dead by Daylight",
    "genre": "4v1 Asimetrik Korku",
    "coverImage": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/381210/header.jpg",
    "releaseYear": 2016,
    "description": "Katil ve 4 kurbanın gerilimli mücadelesi. Unreal Engine motorunda orta düzey bilgisayarlarda bile akıcı 60-120 FPS verir.",
    "minCpuTier": 40,
    "recCpuTier": 64,
    "minGpuTier": 40,
    "recGpuTier": 62,
    "minRamGb": 8,
    "recRamGb": 16,
    "storageGb": 50,
    "cpuWeight": 0.45,
    "gpuWeight": 0.55,
    "ramWeight": 0.1,
    "baseFps1080pLow": 160,
    "steamAppId": 381210,
    "platform": "steam"
  }
];
